### ISSUE TITLE
Ability to group repsitories in the web interface

### ISSUE THREAD

**Issue by RedX2501** [jakubgarfield/Bonobo-Git-Server#134]
It would be nice if one was able to group the repositories in the web interface.

I personally don't care about grouping them in the filesystem as that might make things more complicated.

**Comment by EmaDev** [comment]
This is very usefull feature

**Comment by LennardF1989** [comment]
I actually miss the grouping feature in a lot of repository services, including GitHub. I'll make a pull-request for this as I properly added it in a few hours of work.

**Comment by kiddailey** [comment]
Thank you for this.  I hadn't realize it was already in Bonobo until I went searching and found this issue and pull request.  Much appreciated.
