### ISSUE TITLE
Add support for user certificates for pushing/pulling instead of username+password

### ISSUE THREAD

**Issue by Raffo84** [jakubgarfield/Bonobo-Git-Server#149]
In other web-based repository Managers it's possible to store a private SSL certificate with your user profile. That way you can push/pull/communicate with the server through your certificate, and you don't have to enter credentials all the time.

**Comment by alexchandel** [comment]
@jakubgarfield He's probably talking about SSH keys. Those would be nice, except Bonobo isn't an SSH server afaik.

@Raffo84 Have you looked into a credentials manager like git-credential-store? I believe one is integrated into Git Extensions on Windows.

**Comment by jakubgarfield** [comment]
Implementing SSH access under Windows is unfortunately very complicated and it would be a project for itself.

I stumbled upon git-credential-store recently and it looks like an awesome way to store the git passwords in much more secure way than I was proposing.

**Comment by Setitch** [comment]
Use pageant + tortoise git - it works VERY good.
