### ISSUE TITLE
Usernames with @ doesn't work

### ISSUE THREAD

**Issue by jakubgarfield** [jakubgarfield/Bonobo-Git-Server#163]
AD styled usernames (domain\\user) replaces the character \\ with @ and that converts  @ to \\ back again even for non AD names unfortunately (like usernames as an email format). 

https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/UsernameUrl.cs

**Comment by alexchandel** [comment]
I believe this is fixed in 3.5. Close?
