### ISSUE TITLE
Can't edit repository after "disallow special characters for repository name pull request"

### ISSUE THREAD

**Issue by alexkuznetsov** [jakubgarfield/Bonobo-Git-Server#194]
Hello!
I repeat my comment from #159.

After #159  we can't edit several ours repos. They have a dots in names - name like namespace in C# (Blah.Blah2.Blah3 or Blah.BlahBlah).

What about to use something like that:
```csharp
var repositoryName = repositoryName.Trim('.');
```

It will be removed dots from start and end of repository name.

**Comment by mbedded** [comment]
What exception do you occur?
I made this PR and i just disallow special characters if you create a new repository. The existing repos shouldn't be affected.

I will check this, too. But it could need some time..
To remove the dot in the end is a possible solution, too.
Intention with the limit to a-Z,_ and - was that the Browser/URL could have problems, if you use other characters.

**Comment by alexkuznetsov** [comment]
Our error:
![screenshot_1](https://cloud.githubusercontent.com/assets/1185266/5661521/fdb8e6f2-9756-11e4-8fe8-dbf415ab2be5.png)

It happens in browser, then i try to save repository. 
![screenshot_3](https://cloud.githubusercontent.com/assets/1185266/5661581/b2337426-9757-11e4-870c-a15b4f56e359.png)

In second screenshot you can see hidden field with validation.

I understand that my proposal is not a fix for #142, so if i can help you with something - just tell me.
If refactoring for regex is complicated, may be we can replace it to something like [that](http://msdn.microsoft.com/en-us/library/gg508808%28VS.98%29.aspx)?

And in remote validator action we can:
 1. Check for dots;
 2. Check for forbidden (special) characters

**Comment by mbedded** [comment]
Ah okay, i think i got the problem. I thought first, its in the git-client you use.
But this error occurs if you update your repo during the website.

I will update that Regex-Statement so that dot is allowed, but not in the end.
I think i can do a PR in a few days (perhaps today evening).

**Comment by alexkuznetsov** [comment]
Good, thank  you very much for your help!

**Comment by mbedded** [comment]
@alexkuznetsov: Can you test the new Regex please?
In my Fork (https://github.com/mbedded/Bonobo-Git-Server/tree/PasswordPolicy) it works. You have to download the fork and compile the sources. If you can't do that (no Visual Studio or something) i can try to make the compiled code available to you on another way. Pls compile and check if the fixed-Regex works for your problem.

I fixed the Regex so you can write the following signs:
a-z/A-Z  0-9  .  -  _
I added the expression: "[^.]$"
Thats checks if the string doesn't end with a dot. If it ends with a dot, there will be the typical error-message.

Thank you and sorry for the inconvenience.

**Comment by alexkuznetsov** [comment]
@mbedded yes, sure.
I test is in LinqPad for all our repo names with dots and will write here about results.

I think, i can test your fork tommorow in office, approximately at 02:00-03:00 UTC.

**Comment by alexkuznetsov** [comment]
All names are passed.
My test:
```csharp
void Main()
{
	var names = new [] { 
		"Blah.Blah.Blh.Blaaah",
		".Blah.Blah.Blh.Blaaah"
	};
	
	foreach(var name in names)
	{
		Test(name);
	}
}

void Test(string name)
{
	TestOriginal(name);
	TestModified(name);
}

void TestOriginal(string name)
{
	var reg = new System.Text.RegularExpressions.Regex("([a-zA-Z0-9-_.])+([^.])$");
	var results = reg.IsMatch(name);
	results.Dump(name + ": Original Regex");
}

void TestModified(string name)
{
	var reg = new System.Text.RegularExpressions.Regex("^([^.])+([a-zA-Z0-9-_.])+([^.])$");
	var results = reg.IsMatch(name);
	results.Dump(name + ": Modified Regex");
}
```
In the modified regex more strict check. And a results in screenshot:
![screenshot_4](https://cloud.githubusercontent.com/assets/1185266/5665159/b860796a-9780-11e4-8e11-bd2c6e80fa16.png)

**Comment by mbedded** [comment]
The regex i have written doesn't check for a dot in the beginning of the string it has the following format: "([a-zA-Z0-9-_.])+([^.])$"
I think we should let it be so easy, because the main reason for that feature was that a user had a problem, if the name of a git-repository ended with a dot.

**Comment by alexkuznetsov** [comment]
>I think we should let it be so easy, because the main reason for that feature was that a user had a problem, if the name of a git-repository ended with a dot.

I think let it be original regex. As i write before it work for me.

**Comment by mbedded** [comment]
I made a PR with the updated regex. I opened a "thread" to ask other users, if they have some special characters. The format could affect other people, too and i want to prevent an issue like you had.
