### ISSUE TITLE
Truncate commits messages to one line in tree view

### ISSUE THREAD

**Issue by jafp** [jakubgarfield/Bonobo-Git-Server#195]
Consider truncating (with ellipsis) the commit messages in the tree view to one line, as it is annoying that the tree changes after the commit messages has finished loading if some of them takes up more than one line of space.

**Comment by jakubgarfield** [comment]
That would be a really useful feature, however there is no place with the full commit message at the moment. I think it needs be consolidated a little and PR addressing this issue would be super welcomed.

**Comment by anderswb** [comment]
How about something like gitscm's log/shortlog? I think that works pretty well.

**Comment by jakubgarfield** [comment]
Implemented recently
