### ISSUE TITLE
Add a CONTRIBUTING (or similar) document

### ISSUE THREAD

**Issue by jafp** [jakubgarfield/Bonobo-Git-Server#196]
Add a CONTRIBUTING document that explains how to contribute to the project, and additionally explains how to set-up the development environment with the required tools etc.

**Comment by jakubgarfield** [comment]
Do you find something challenging in setting up the development environment? My biased view is that you clone the project and you open it in Visual Studio.

There are also formatting settings as a part of the project as well - #183.

However, it might be useful to maintain a good quality commit messages and clean and atomic commits.

**Comment by jafp** [comment]
I do actually, but that is primarily because I'm not a Windows-guy! :+1: Even though it's that easy, I'm sure it would be helpful to many if it was written down somewhere.

Besides that, I was thinking about something like Angular's [contributing document](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md), which describes how issues should be formed, how to deal with feature requests, submitting a pull request and so on, all of which helps ensure a high quality product.

**Comment by jakubgarfield** [comment]
I put together a small list of things that came to my mind. Let me know if there is something essential missing.
