### ISSUE TITLE
ui sort order commits 

### ISSUE THREAD

**Issue by razvantim** [jakubgarfield/Bonobo-Git-Server#201]
Hi,

In the web interface the commits are not sorted correctly (sometimes). I assume that they should be sorted by date, but sometimes they get messed up.
![bonobo-git-server-sort-problem](https://cloud.githubusercontent.com/assets/979162/5756760/b6933b5a-9cbb-11e4-86ea-85a092c4f8ee.png)

**Comment by alexkuznetsov** [comment]
@razvantim, commits from several authors?

If yes, that is normal, commits are arranged by commit date.

**Comment by razvantim** [comment]
commits are from different users, but they are not arranged by commit date.

**Comment by jakubgarfield** [comment]
I believe that it would be related with the order strategy for multiple parents and how the libgit2 library deals with it.

Try to take a look at 
~~~
return _repository.Commits
                              .QueryBy(new CommitFilter { Since = commit, SortBy = CommitSortStrategies.Topological })
                              .Select(s => ToModel(s)).ToList();
~~~

In repository browser class - https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/RepositoryBrowser.cs#L44
