### ISSUE TITLE
Consider moving the pagination of commits to libgit2sharp

### ISSUE THREAD

**Issue by jafp** [jakubgarfield/Bonobo-Git-Server#203]
We're are experiencing the load time of the Commits page increases proportional to the number of commits in the project.

A short look at the implementation shows that all commits are loaded from the repository (using libgit2sharp), instead of only the ones to show at the current page. The pagination is handled one level higher, i.e. in the controller.

**Comment by anderswb** [comment]
I second this issue.

We recently started using Bonobo, and we can already see - on a project with 187 commits - a loading time of around 65 seconds from the time when i press the "Commits" button until the page is ready.

**Comment by alexkuznetsov** [comment]
@anderswb, in our case a page loads very quickly. May be the issue in your hardware?

Our instance works on virtual machine under windows 2012 server (hyper-v virtualization).

For VM used two cores (2 Ghz) and 4Gb RAM, as i remember.
