### ISSUE TITLE
Windows Authentication can be by pass using http://anynonomous@url/repository.git

### ISSUE THREAD

**Issue by kiocjw** [jakubgarfield/Bonobo-Git-Server#204]
I found an issue which the Windows Authentication can be by pass using http://anynonomous@url/repository.git.
I can just put any username even http://@url/repository.git is working.

**Comment by jakubgarfield** [comment]
Does it work like that from a Windows Account that doesn't have access to git server?

**Comment by kiocjw** [comment]
From the Windows Account that have access. It cannot login other Windows Account that have access if using Windows Account that doesn't have access. And I need visit url.domain.com/Bonobo.Git.Server/ everytime I need to git bash else it will fail
