### ISSUE TITLE
Set default clone branch

### ISSUE THREAD

**Issue by mikehaas763** [jakubgarfield/Bonobo-Git-Server#206]
I've never worked with libgit2 or libgit2sharp before so I'm not sure if this would entail a lot of work. Either way, if we can agree that it's useful to add a setting for the default cloning branch in the repository settings I would like to implement this feature.

It would simply be a dropdown menu that listed the current branches and allow you to pick one of them as the default. It's the same thing that Github offers as I put in a screenshot below.

![image](https://cloud.githubusercontent.com/assets/2096573/6050641/41aab6c2-ac8f-11e4-9f8a-05889e41534e.png)

Any thoughts?

**Comment by mikehaas763** [comment]
I'm trying to get a local dev environment set up so I can work on Bonobo. I've cloned the repo and opened the solution up in VS 2013. VS automatically set up an app in IIS. I run the app and I get the following error:

![capture](https://cloud.githubusercontent.com/assets/2096573/6054730/720303bc-acbf-11e4-8f9f-079e55ba3d94.PNG)

I'm hoping to get an instruction on the steps needed to get a dev env working.

**Comment by mikehaas763** [comment]
The only thing I've figured out to get the interop dll error fixed is detailed in this SO post: http://stackoverflow.com/a/15735328

As that person said though, I'm not sure that's a good way to fix it.

**Comment by jakubgarfield** [comment]
I'm pretty sure I ran into this issue and solve it for myself by setting Copy to output directory to Always (but that's already set, so it doesn't solve the issue for you).

To collaborate with IIS, I need to run VS as an administrator, but that's just a long shot for this.

Any luck? How about setting the deployment item as mentioned in that SO answer?
