### ISSUE TITLE
Lot commits

### ISSUE THREAD

**Issue by kostyrin** [jakubgarfield/Bonobo-Git-Server#215]
Hello Jakub.
I have trouble with commits.
I merged source from visualstudio.com with each TFS changeset.
When I open http://localhost/Bonobo.Git.Server/Repository/carnet/master/Commits.
I have trouble. Page is loading a long time..
Could you help me?
Repository is working good.

**Comment by alexchandel** [comment]
So you locally converted a TFS repository to Git, created a new repo in Bonobo, and then pushed your converted Git repo? Exactly how many commits are there on master?

**Comment by jakubgarfield** [comment]
Can you give us a rough estimate on the number of commits you have?

**Comment by LinkiH** [comment]
about 1000

**Comment by jakubgarfield** [comment]
What hardware are you running the server on?

**Comment by jakubgarfield** [comment]
But the commits are not very fast - it loads every commit from the start of the repository and build the tree for it - a convenience from the libgit2sharp library - there might be a better of doing it, especially if you consider that you page the commits. For your reference the rails repository with more than 50 000 commits took 15 seconds to load.

**Comment by kostyrin** [comment]
1 CPU 2,3Ghz, RAM 2Gb. Maybe that's reason.
