### ISSUE TITLE
fatal: Unable to find remote helper for 'https'

### ISSUE THREAD

**Issue by hugoj-goncalves** [jakubgarfield/Bonobo-Git-Server#219]
I'm trying to make a git push in my post-receive script, but I can't use git:// protocol on my company network.
It seems that Bonobo git from AppData folder is missing a few references to the https protocol.
I tried setting a full git version on Web.config (GitPath), but using this approach my git push never finished.

I made a bare repo without Bonobo just to test it out, and my post-receive scripts works fine... (which is basically a git push)

Any toughts or workarounds that I can try?

**Comment by alexkuznetsov** [comment]
In our office we always work via https protocol with Bonobo Git Server.
I correct understand, you have post-recive hook that make commits to the Bonobo Git Server?

If it correct (my proposal), my be the problem is in certificate? Do you use self-signed certificate on IIS?

**Comment by hugoj-goncalves** [comment]
Actually, we're currently using github.com.
But as long as I can tell, they don't allow server-side hooks, so we're creating a "middleware" using Bonobo server... so we'll be pushing directly to Bonobo, and after validations etc (using server side hooks) we're going to still push to github.com (it may change in the future, but for now that's the setup we're trying to achieve)

I'm not using a self-signed certificate yet, I didn't think it would be necessary in this case. Is it?
The failing push is from our "Bonobo server" to github.com (using https).

**Comment by alexkuznetsov** [comment]
Hm, now i understand that you mean. Thank you for explanation.
Tomorow, i will try to reproduce it on our server. Maybe i will see where the problem is.

**Comment by hugoj-goncalves** [comment]
Okay, thanks.

And sorry for my bad english ;x

**Comment by alexkuznetsov** [comment]
hi @hugoj-goncalves
i wrote you to your email.

I can "push" via git protocol, but via https got the problem from the subject. And no thoughts how to solve it.

**Comment by hugoj-goncalves** [comment]
Hello @alexkuznetsov 

Oh I see, thanks for trying to help me on this. The problem is that I can’t use git protocol on my work, making it impossible to solve the same way you did. (I’m being forced to use https here ffs)
I gave up on this for now, already set up a ssh server and I’m making the last adjustments so we can work from there.

I’ll try using it again when I find some free time.

Cya ;)

**Comment by alexkuznetsov** [comment]
So i, it is strange, why it throws that error. My thoughts - the problem is in curl, but how to make it work - that is the question ;)

So if you solve it - please get us to known, how you solve it. I take a break with it to :)

Have a nice day!

**Comment by hugoj-goncalves** [comment]
Why is it closed? o.O

**Comment by jakubgarfield** [comment]
I closed a few issues I haven't seen progress for a while and duplicates - this one maybe too prematurely. Happy to reopen.

**Comment by RedX2501** [comment]
I assume this got fixed as we have not heard anything else from you.
If the problem persists please reopen.
