### ISSUE TITLE
japanese translation is too slang.

### ISSUE THREAD

**Issue by mattn** [jakubgarfield/Bonobo-Git-Server#220]
For example:

https://github.com/jakubgarfield/Bonobo-Git-Server/blob/564556b0d03867d6a498aa7dff0cba2e4e16ab6f/Bonobo.Git.Server/App_GlobalResources/Resources.ja-JP.resx#L160
https://github.com/jakubgarfield/Bonobo-Git-Server/blob/564556b0d03867d6a498aa7dff0cba2e4e16ab6f/Bonobo.Git.Server/App_GlobalResources/Resources.ja-JP.resx#L160

I point to many sentences.

**Comment by RedX2501** [comment]
Please have a look at the latest version. if you still feel it is too slang please reopen the issue.

**Comment by mattn** [comment]
I forgot to close this when this commit had merged. https://github.com/jakubgarfield/Bonobo-Git-Server/commit/44f8c21f19f95e57afe89ca563cebd8a529cf513

thanks.
