### ISSUE TITLE
GIT Version

### ISSUE THREAD

**Issue by zAfLu** [jakubgarfield/Bonobo-Git-Server#223]
Hello,

any plans to update the included git version?

**Comment by jakubgarfield** [comment]
I ran into a compatibility issues with some git clients with the latest version and I don't have a capacity to investigate any further.

If you need to update your git version, use custom location of git.exe in the web.config. If you feel to do some testing and digging when submitting a PR with new git version, that would be the best!

**Comment by larshg** [comment]
This and #189 can be closed now :) ?

**Comment by jakubgarfield** [comment]
For sure, thanks!
