### ISSUE TITLE
Error:  Trying to load native SQLite library

### ISSUE THREAD

**Issue by emmilely** [jakubgarfield/Bonobo-Git-Server#224]
I installed the latest version of Bonobo (3.5.0) two weeks ago and had been enjoying it quite a lot.  About 4 days after installation, GIT started giving me the "is this a git repository?" error that signified a server issue.

In the logs, I found the error:
Trying to load native SQLite library "C:\inetpub\wwwroot\git\x64\SQLite.Interop.dll"...

This error occurred every time I attempted to connect to the Bonobo remote repository.

I deleted the entire Bonobo folder, reinstalled it from scratch, and everything worked perfectly fine until a few days ago, when this same issue came up again.

**Comment by jakubgarfield** [comment]
Can you paste the error message form the log?

**Comment by Excolo** [comment]
I get this error too and that is the entire error message.

**Comment by emmilely** [comment]
Here is my full error log:

    Trying to load native SQLite library "C:\inetpub\wwwroot\git\x64\SQLite.Interop.dll"...
    Trying to load native SQLite library "C:\inetpub\wwwroot\git\x64\SQLite.Interop.dll"...
    Trying to load native SQLite library "C:\inetpub\wwwroot\git\x64\SQLite.Interop.dll"...
    Trying to load native SQLite library "C:\inetpub\wwwroot\git\x64\SQLite.Interop.dll"...
    Trying to load native SQLite library "C:\inetpub\wwwroot\git\x64\SQLite.Interop.dll"...
    Trying to load native SQLite library "C:\inetpub\wwwroot\git\x64\SQLite.Interop.dll"...
    Trying to load native SQLite library "C:\inetpub\wwwroot\git\x64\SQLite.Interop.dll"...
    Trying to load native SQLite library "C:\inetpub\wwwroot\git\x64\SQLite.Interop.dll"...

The error is only logged the first time I try connecting to the repository after an IIS service restart.  Subsequent connection attempts do not add an error to the log.

Please let me know if there is anything else I can do to assist!

**Comment by jakubgarfield** [comment]
This error occurs when the server starts/restarts and it's actually not an error - the server loads 32bit version of the library.

So the problem is somewhere else - make sure that you are accessing the right URL from your git client.

**Comment by emmilely** [comment]
That's the strange part, it was working perfectly for days, and I saved the URL as a remote, so I know it's the correct one.  The only thing I can think of that's changed has been the fact that we've run Windows Update on the server.  Would that have caused a problem?

I am running Bonobo on Windows Server 2012.

**Comment by emmilely** [comment]
I ended up spinning up another server with Windows 2008 R2 on it, and this one seems to be working like a charm, as opposed to the two Windows 2012 ones that randomly started giving me the "is this a git repository?" error a few days after installation.

All servers were newly created and only had Bonobo and its prerequisites on them, so I'm just going to stick with the Windows 2008 R2 configuration for now, since I have no idea what else it could be.

**Comment by toomanylogins** [comment]
I have this problem on windows 2008 r2 and I cant connect from client. Web is ok..

**Comment by RedX2501** [comment]
@emmilely What is the status of this with the new Bonobo versions?

**Comment by emmilely** [comment]
@RedX2501 We haven't had an issue with the version we set up on our Windows 2008 R2 server back in March, so we haven't really checked, unfortunately.
