### ISSUE TITLE
Allow anonymous users to browse public repositories

### ISSUE THREAD

**Issue by glacasa** [jakubgarfield/Bonobo-Git-Server#226]
I think it would be a good idea to allow anonymous users to display the list of public repositories on the home page, instead of asking to login.

Also, I noted that repositories with the "Anonymous" option checked can't be seen in the browser.

I started to work on this feature on this branch :
https://github.com/glacasa/Bonobo-Git-Server/tree/anonymous-listing
but I'm not sure I'm doing it the right way.

**Comment by jakubgarfield** [comment]
Duplicate of #77
