### ISSUE TITLE
.NET based Build Server feature

### ISSUE THREAD

**Issue by Jalalx** [jakubgarfield/Bonobo-Git-Server#240]
Hi
Is there any idea for implementing a simple build server feature? [MSBuild](https://github.com/Microsoft/msbuild) is now open source and independent so I think it's easier to implement a build server for .NET based solutions.

**Comment by jakubgarfield** [comment]
I'd recommend connecting other tools (as Teamcity of Jenkins) and use Bonobo as a versioning software.
