### ISSUE TITLE
Bonobo Repositories/Commits showing up in Bing crawl information

### ISSUE THREAD

**Issue by nstuller** [jakubgarfield/Bonobo-Git-Server#242]
I setup the Bonobo Git Server about a week ago on my web server. Now, when I look in my Bing Webmaster, I see some concerning entries.

Under Dashboard | Reports & Data | Crawl Information | HTTP 400-499 Codes, I see the following URLs
http://<root-site>/Bonobo.Git.Server/Repository/<RepositoryName>/master/Commit/4e67...
http://<root-site>/Bonobo.Git.Server/Repository/<RepositoryName>/master/Commit/4452...
http://<root-site>/Bonobo.Git.Server/Repository/<RepositoryName>

I'd like to keep information about my repositories off the public Internet. Is there some setting I should set to make sure things are private?

I have all the anonymous settings turned off.

**Comment by jakubgarfield** [comment]
I don't understand how this would be possible if Bing didn't have a public access to your repos, if they are protected by password (forms authentication) they shouldn't be indexed.

Is it possible that you had the authentication turned off at the beginning?

**Comment by kiddailey** [comment]
What's the HTTP status code for these entries?  400-499 indicate client errors (like bad request, request denied, etc) which may indicate that the crawler failed at contacting those URLs.

**Comment by nstuller** [comment]
The HTTP code is 401, but I don't understand how Bing would even find such
a specific URL to try. Wouldn't it have to find a link to it somewhere?


On Wed, Apr 1, 2015 at 4:21 PM, kiddailey <notifications@github.com> wrote:

> What's the HTTP status code for these entries? 400-499 indicate client
> errors (like bad request, request denied, etc) which may indicate that the
> crawler failed at contacting those URLs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jakubgarfield/Bonobo-Git-Server/issues/242#issuecomment-88620290>
> .
>



-- 
Nathan Stuller
Lead Developer/Development Manager
nstuller@unstoppablesoftware.com
Unstoppable Software, Inc. <http://www.unstoppablesoftware.com>
513-304-7534

**Comment by kiddailey** [comment]
Hard to say how it happened and I'm not familiar with Bing Webmaster Tools, but my assumption is that yes, it would have to find the link somewhere.  Problem is that "somewhere" is easily accommodated -- even if accidentally -- these days ...

Do you have a _Bing Webmaster Tools_ sitemap?  Does it inadvertently include the URLs?  What about their server plugin that automatically builds sitemaps based on traffic to  the server.  Make sure that's not installed/enabled on your site :)

Beyond that ... Did someone on your team maybe post a URL somewhere thinking it was private when it wasn't?  If even a single commit was intercepted by any crawler, it could derive the path structure and attempt to crawl the root of each path.  Or maybe someone uses a cloud email service that scans emails?  Does someone using a anti-virus/malware that scans URLs intercepted via email or as they surf and maybe cataloged somewhere?  Or maybe a URL was emailed to someone who uses either of those?

In any case, I have a private deploy of Bonobo myself and I've never seen any web crawler traffic, so I doubt it's the fault of Bonobo leaking something.

**Comment by RedX2501** [comment]
@nstuller Is this still an issue with the latest Bonobo versions?

**Comment by RedX2501** [comment]
Since we have not heard back from you in 3 weeks I'm closing this.
If the problem still exists please reopen.
