### ISSUE TITLE
update font awesome

### ISSUE THREAD

**Issue by lkho** [jakubgarfield/Bonobo-Git-Server#246]
i have seen some pages used new font icons not exist in 4.0.3, should this be updated?

**Comment by jakubgarfield** [comment]
There is no reason to update font awesome unless something is broken, or it stops you from creating an awesome design. Would you benefit from the update?

**Comment by lkho** [comment]
Doesn't matter, I just came across a page with a "fa-history" which is 4.1, thinking if this is a mistake, or we can just change it to "fa-clock-o".

**Comment by jakubgarfield** [comment]
fa-history is a nice icon - it might be useful to upgrade then :)

**Comment by RedX2501** [comment]
@jakubgarfield Has the update been done? Can we close this?

**Comment by jakubgarfield** [comment]
I don't think I got a PR for this one yet.

**Comment by willdean** [comment]
There was an upgrade from F.A. 4.0.3 to 4.3.0 by @lkho in 727d1b87 about 9 months ago, so I'd guess this is done now.
