### ISSUE TITLE
SmartGit Client

### ISSUE THREAD

**Issue by toomanylogins** [jakubgarfield/Bonobo-Git-Server#251]
I'm trying this is as remote repository. I have installed the server without problem and web interfaces working okay basic authentication on my local network. When trying to connect from smart git I get failed authentication. The URL is correct is copied from the repository web page. I get the error after entering username. I have tried Windows authentication and also forms. With Windows authentication I also get failure. With forms I get  is this a valid repository.

Has anyone else had this working with smart git.
Thanks
 Paul

**Comment by toomanylogins** [comment]
Bit more info. If I use forms authentication  the error message is
../bonobo.git.server/front.git/info/refs not valid: is this valid git repository?
front.git is a new empty repository  the error appears before I enter a username or password.

**Comment by danielcirket** [comment]
Just run into this problem myself. I got mine working with the authentication mode set to "None" in the web config.

Granted this may not be a solution, but I'm only testing so far.

**Comment by RedX2501** [comment]
I assume this got fixed as we have not heard anything else from you.
If the problem persists please reopen.
