### ISSUE TITLE
Error in highlight.js = Preview of this file is not supported.

### ISSUE THREAD

**Issue by padremortius** [jakubgarfield/Bonobo-Git-Server#254]
Bonobo showed message "Preview of this file is not supported." when we have error in highlight.js (not correct detect template). For correction need make changes in FileDisplayHandler.GetBrushes and rebuild application. Maybe should make a correspondence table extension to the template to an external configuration file or database? This will allow to make changes without rebuilding project.

**Comment by padremortius** [comment]
For example, get file https://github.com/project-jedi/jvcl/blob/master/jvcl/run/JvAnimate.pas 
Change extension from *.pas to *.pp. Upload into git. Open this file in web-interface Bonobo. We see error 'Preview of this file is not supported.'. And push the button Raw (Error 404- File not found).

**Comment by jakubgarfield** [comment]
Confirmed bug that needs fixing, it might be due to different encoding of the file. Any takers?

**Comment by padremortius** [comment]
Return extention to *pas and we have not error.
I trying.
