### ISSUE TITLE
Add renaming features

### ISSUE THREAD

**Issue by Eagle3386** [jakubgarfield/Bonobo-Git-Server#255]
Please add options to rename repositories, teams and users.

**Comment by jakubgarfield** [comment]
This feature would be awesome. PR is much appreciated.

**Comment by Eagle3386** [comment]
Well, I was kind of an user requesting a feature, not an announcement about a planned PR.

**Comment by jakubgarfield** [comment]
It is not necessarily targeted at you. Anyone interested in contributing to Bonobo can pick up one of the bugs or requested features and especially with this one I'd be happy to merge it. It's better to discuss the feature upfront than reject implemented work that doesn't line with the project's direction.

**Comment by YopparaiNeko** [comment]
Just wanted to ping that this would be a nice feature.
