### ISSUE TITLE
[Question] Is there a way to enable read-only permissions in Bonobo by user or by group?

### ISSUE THREAD

**Issue by interested-party** [jakubgarfield/Bonobo-Git-Server#256]
Within our network, we'd like to enable certain groups (e.g., Product Quality) to access Bonobo on a read-only basis. Is this possible with Bonobo out of the box or with some additional scripts?

**Comment by jakubgarfield** [comment]
Unfortunately no. You can either allow anonymous users to have a read only access to the repository or you are giving read/write access to individuals/groups.

**Comment by arj060892** [comment]
How can we restric users from pushing their branches to Git Server

**Comment by fpattis** [comment]
could this be a possible feature? would be very nice! 😃

**Comment by chkpnt** [comment]
A work around could be a pre-receive hook script, see https://github.com/jakubgarfield/Bonobo-Git-Server/issues/798#issuecomment-1903517761
