### ISSUE TITLE
Could not clone repos with OS-X/Mac git client

### ISSUE THREAD

**Issue by amarbabuk** [jakubgarfield/Bonobo-Git-Server#261]
I could not connect to GIT Server (bonobo) with OS-X/Mac GIT client.

I tried with with Basic and Windows(AD) authentications  - always authentication fails

Please advise the fix.

Thanks,
Amar

**Comment by RedX2501** [comment]
I assume this got fixed as we have not heard anything else from you.
If the problem persists please reopen.
