### ISSUE TITLE
Configuration Steps for windows authentication fail on IIS 8

### ISSUE THREAD

**Issue by RedX2501** [jakubgarfield/Bonobo-Git-Server#264]
During setup i had errors complaining that <handlers> and <modules> could not be executed as they had been locked. Return error code was 500.19.

To resolve it i had to execute:

%windir%\system32\inetsrv\appcmd unlock config -section:system.webServer/handlers
%windir%\system32\inetsrv\appcmd unlock config -section:system.webServer/modules

Maybe this should be added to the readme.

**Comment by jakubgarfield** [comment]
It took me a while, but I finally updated FAQ.
