### ISSUE TITLE
Blob shows 404 error when trying to display .cfm, .cfc or .mxml files

### ISSUE THREAD

**Issue by kevinkl3** [jakubgarfield/Bonobo-Git-Server#265]
It can't display coldfusion or Flash Builder related files. Not sure if this is related to bug #93.

**Comment by padremortius** [comment]
Description is very similar to error #254.

**Comment by kevinkl3** [comment]
There seems to be a conflict when having the Coldfusion installed in the same server, we uninstalled the coldfusion and now it's working just fine.
Thanks.
