### ISSUE TITLE
401 - Unauthorized: Access is denied due to invalid credentials.

### ISSUE THREAD

**Issue by NgYueHong** [jakubgarfield/Bonobo-Git-Server#267]
When I click on tabs or navigate around repository after login for a while and the session has expired, I will receive the page error showing "401 - Unauthorized: Access is denied due to invalid credentials.". 

It will be much better to redirect me to the login page instead of showing the unauthorized access error. 

Hope to see the fix soon. Thank you.

**Comment by kiddailey** [comment]
+1

**Comment by Matt-17** [comment]
For me my commit is working. Can there be any side effects I'm not aware of?

**Comment by KY4U** [comment]
When can we expect Matt-17 commits to be merged with master branch?

**Comment by jakubgarfield** [comment]
@Matt-17 would you mind submitting a PR?

**Comment by Matt-17** [comment]
I just did. Haven't used GitHub a lot yet, so I hope that works ;)

**Comment by jakubgarfield** [comment]
Awesome, thank you! :)

Fixed #300
