### ISSUE TITLE
First push of the day to remote Bonobo sever takes about 15 - 30 min. to complete

### ISSUE THREAD

**Issue by lennartvdd** [jakubgarfield/Bonobo-Git-Server#271]
When making the first push of the day to our bonobo server we have to wait a long time for the push to complete. 

Any ideas what could cause this? 
Anyone else with this issue?

Once this first push completes, subsequent pushes are fast. 
Just the initial one takes **forever**!

**Comment by jakubgarfield** [comment]
Any special characteristics of your repository? Large files, many commits? 15-30 minute seems a lot - even repositories like rails with many commits shouldn't take that long.

**Comment by lennartvdd** [comment]
Not really. About ~4000 commits, but concidering most of the commit history is already on that server that shouldn't be the issue. No large files. Only small php and js files. 

two processes are fired up server side `git.exe receive-pack --stateless-rpc [path to repo under bonobo]` and `sh.exe hooks/post-receive`. Looking at the response client-side, It seems the latter is taking it's time. 

The sending happens in normal time. The following appears immediately after the push:
```
Counting objects: 9, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 328 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
```

now the waiting for response from post-receive script starts....

and ~30 min. later. there it is:

```
remote: starting deploy to worktree
remote: deploy to worktree done
remote: Running migrations
remote:
remote: Yii Migration Tool v1.0 (based on Yii v1.1.x)
remote:
remote: No new migration found. Your system is up-to-date.
To http://user@server/repo.git
   sha1no1..sha1no2  master -> master
```

post-receive is nothing fancy, containing the following code:
```sh
#!/bin/sh
echo "starting deploy to worktree"
git checkout -f
echo "deploy to worktree done"
echo "Running migrations"
php /c/inetpub/[repository name]/public_html/protected/yiic.php migrate --interactive=0
```

**Comment by jakubgarfield** [comment]
Sounds like most of the time is spent in the post receive hook. Would you mind trying to do without it?

**Comment by lennartvdd** [comment]
I can confirm that. Without the post-receive hook (file renamed) the push is instant (< 1 s.) 
With a cleared out post-receive hook (only containing the shebang and a single echo line) the push is slow. 

The post-receive hook is however crucial for us, because db schema migrations need te be performed together with the release of code.

**Comment by jakubgarfield** [comment]
Is it possible that the hook is run 4000x? I don't use hooks myself but as a workaround you can disable the hook for the first push and enable it afterwards.

**Comment by lennartvdd** [comment]
possible, but not likely. If that were the case, I'd also expect to see the output of the hook that many times. I guess this might be a problem in the git-receive-pack. 

Perhaps it has something to do with permission checks. 
(possibly) related issue: https://confluence.atlassian.com/display/STASHKB/Git+push+operations+extremely+slow+on+Windows

Will experiment a little bit with permissions later this month.

**Comment by RedX2501** [comment]
I assume this is no longer an issue since we have not heard back.
If the issue still persists please reopen.

**Comment by lennartvdd** [comment]
Yes. Weirdly enough the issue persisted for a while until PHP was upgraded from v5.3 to v5.4 in IIS.
Leaving this here for future reference.
