### ISSUE TITLE
Provide information on how to update bonobo

### ISSUE THREAD

**Issue by RedX2501** [jakubgarfield/Bonobo-Git-Server#274]
I am currently using 3.4.3 and would like to update to 3.6.

Unfortunately there does not seem to be any directions on how to update.

I'm afraid i might overwrite some existing configuration files.

**Comment by kensel** [comment]
When you installed 3.4.3 did you install with the basic authentication, or the default forms authentication? 
I stopped IIS, did a backup of my Bonbo.Git.Server folder and then just copied the new files over and it upgraded okay.  If you made any changes to the config when you started you will need to make the same changes or run a diff on the configuration file to see if there are any changes.

**Comment by RedX2501** [comment]
@jakubgarfield  I think this can be closed now as you have added the information. https://bonobogitserver.com/update/
