### ISSUE TITLE
Administrator role account can't edit repository if not also repository administrator

### ISSUE THREAD

**Issue by Eric-Brousseau-AIA** [jakubgarfield/Bonobo-Git-Server#275]
I recently updated my Bonobo server from 2.0.1 to 3.6.0 (Big upgrade, I know...)

With the new version, if I try to edit the properties of a repository, I get the following message: "You can't remove yourself from administrators" if my account is not already selected as an administrator of the repository.

Now, my account has the "Administrator" role checked and in the old version, I could edit the properties of all repositories with this account regardless of whether I was an administrator or not of the repositories themselves.

Is this the expected behavior in the new version?

Regards,

Eric Brousseau

**Comment by jakubgarfield** [comment]
Only repository administrators are expected to change properties of the repository.
