### ISSUE TITLE
Illegal characters in repository names from previous versions

### ISSUE THREAD

**Issue by Eric-Brousseau-AIA** [jakubgarfield/Bonobo-Git-Server#276]
Hi,

I recently upgraded my Bonobo server from 2.0.1 to 3.6.0.

In the old version, I had a repository named "XMLDocFeaturesExtractor(XDFE)". Now with the new version, I get the following error: "Only characters, numbers, dots, minus and underscore are allowed for "Name"." This means that I can no longer edit the properties of this repository now, including the access rights on it.

Is there a way to bypass the validation rules on an existing repository name since this value can not be edited after the repository has been created? If this is not possible, is there a way to rename a repository so that I can get this repository working again? Right now, I would like a "quick fix" just to be able to get the repository working again.

Regards,

Eric Brousseau

**Comment by jakubgarfield** [comment]
Rename the repository folder in Explorer manually and Bonobo should pick it up automatically under the new name. After that, you can delete the missing old repository with the old name.

**Comment by Eric-Brousseau-AIA** [comment]
I tried this and it almost worked. I copied and renamed the folder and now have a new repository with a valid name that lets me edit it's properties. But when I try to delete the old repository, I can't. When I click on the "Delete" button, nothing happens. I tried deleting another repository that had a legal name from the start and it worked, so I suspect that this also have something to do with the naming of the repository.

**Comment by jakubgarfield** [comment]
At least it leaves you with a working repository now. Could you provide a log file for your delete action on that repository? (I assume it doesn't give you an error in the UI)

**Comment by Eric-Brousseau-AIA** [comment]
No, there is nothing in the UI. And nothing in the Bonobo.Git.Server.Errors.log fine either. The page just reacts as if I hadn't clicked on the button at all. I opened the markup from the Delete page and it looks like there is a validator in there that validate the "Name" attribute with the same rules as in the Edit page. This might explain why I don't see anything in the log as in must prevent the button from actually submitting the form over to the server.

**Comment by jakubgarfield** [comment]
There is no validation around delete action https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/Controllers/RepositoryController.cs#L139

I'm surprised that there are no errors in the log as it looks like something else is failing.

**Comment by salimoneus** [comment]
To get around this simply save the Delete page as local html and edit it so that

  data-val-regex-pattern="(*)$"

and you should be able to delete the repo with invalid characters.  At least it worked for me.

**Comment by RedX2501** [comment]
Closing this as it should be fixed in new versions.
