### ISSUE TITLE
Option to disable push to master

### ISSUE THREAD

**Issue by kostrse** [jakubgarfield/Bonobo-Git-Server#277]
Would be great to have an option to disable **push to master** for a specific repository.

We have a scheduled job on the server which syncs the master of the server bare repo with another VCS, in this case our `master` is a read-only mirror of other source control system.
Everyone can fetch the `origin/master` to branch off it locally, but we'd want to prevent *accidental* push of changes in master back to server.

Somewhat similar to `receive.denyCurrentBranch`, but for (bare) repos hosted on Bonobo Git Server.

```
[] Allow non-administrators to push to current (default? master? combobox?) branch.
```

**Comment by Stoffe** [comment]
I agree to this one, but not only master.
We have different branches depending on their function, and would like to link a user to a specific branch, so only user x can push to branch master and user y to branch release but all can fetch and well all can push to the develop branch etc...

**Comment by RedX2501** [comment]
Use git commit hooks for that.

We provide `AUTH_USER`, `REMOTE_USER` and on the next release `AUTH_USER_GROUPS` and `AUTH_USER_ROLES` via environment variables.

**Comment by MarvinKlein1508** [comment]
@RedX2501 could you provide us an example to disable pushing for a certain user/group ?
