### ISSUE TITLE
File preview doesn't handle BOM (byte order mark) header  for UTF files

### ISSUE THREAD

**Issue by beatcracker** [jakubgarfield/Bonobo-Git-Server#280]
If file has [BOM](http://en.wikipedia.org/wiki/Byte_order_mark), it will be rendered in a preview. Example:

![BOM rendered in a preview](https://cloud.githubusercontent.com/assets/7583050/8056996/2cdd46e0-0eb6-11e5-9421-c34489febe51.png)

**Comment by lkho** [comment]
BOM should render without problems, are you using the latest build?

**Comment by beatcracker** [comment]
@lkho I'm using Bonobo Git Server 3.6.0.0 with [Git-1.9.5-preview20141217` (portable version)](https://github.com/msysgit/msysgit/releases/tag/Git-1.9.5-preview20141217). I see that version 4.0.0 was [released recently](https://github.com/jakubgarfield/Bonobo-Git-Server/releases/tag/4.0.0), I'll try it and post a results here.

**Comment by beatcracker** [comment]
Sorry for close\reopen, I've hit a wrong button :/

**Comment by beatcracker** [comment]
Confirmed, BOM works fine with version 4.0.0.
