### ISSUE TITLE
User can override Git Server user data

### ISSUE THREAD

**Issue by Matt-17** [jakubgarfield/Bonobo-Git-Server#282]
When I create a user with Name and eMail, I expect the commit history will show this Name (firstname lastname), email and Gravatar. 
My issue is, that using Visual Studio git settings, the user can type in a different name and eMail that is used in the saved history. I would suggest, to put at least an option, that bonobo overrides this with it's own user details.

**Comment by RedX2501** [comment]
I'm not sure that is possible as the commit hash includes the user details.
See last post for details for information that the hash contains.

http://stackoverflow.com/a/28917694/551045

Maybe an option is to deny the commit if the information don't match. You
could do that as a hook.

**Comment by Matt-17** [comment]
Ok, I see. Thanks for the details. But I think the option to deny would also be terrible, since you must change (revert and resubmit?) all your local commits, as I understand?

Then I guess, I should just live with this bahavior except anyone else has an idea.

**Comment by whosa** [comment]
Maybe we can set up a mapping between server settings and git settings

**Comment by jakubgarfield** [comment]
The only way I see this implemented is replace the author info when user is committing into protected repository and needs to authenticate.

Bonobo could ignore info coming from git client and replace it with authenticated user details.

**Comment by Matt-17** [comment]
But as far as I understand git (I'm still pretty new to this topic), it must keep the commit ID so the committer does not have duplicate commits, when he pulls the origin back?

**Comment by mdunicorn** [comment]
@Matt-17 You are right. User name and email is stored in the commit object, and is part of the commit hash. It is impossible to change these information without messing up (rewriting) all the history of the user. So this is definitely not an option.

In my humble opinion, it is better to just warn the user when pushing the commits, and leave everything unchanged.

**Comment by Matt-17** [comment]
Sounds as the best solution. Local rewriting is easier than on server side. Maybe I have time this weekend to think about something to this.

**Comment by RedX2501** [comment]
Not possible with git.
