### ISSUE TITLE
FIPs/MD5 Error with Windows Authentication

### ISSUE THREAD

**Issue by giesberge** [jakubgarfield/Bonobo-Git-Server#285]
Starting with a fresh installation of Bonobo.Git using Windows Authentication and Active Directory Integration. I can't access the Commits or File Histories (instead get redirected to An Error Occurred).

w3wp.exe Error: 0 : Error occured and caught in Global.asax - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by giesberge** [comment]
Went ahead and switched the hasher in Extensions/SignatureExtensions.cs to SHA1 and recompiled the source. Seems to fix everything. Is there any reason it is still using MD5?

**Comment by jakubgarfield** [comment]
Probably just backwards compatibility with the existing database.

**Comment by RedX2501** [comment]
This should be fixed in newer versions.
If not please reopen the issue stating which version you used.
