### ISSUE TITLE
When using clone you can't use branches cloned over. 

### ISSUE THREAD

**Issue by AmishP** [jakubgarfield/Bonobo-Git-Server#288]
Hi, 

I have seen a slight issue when cloning repositories.

Repo A has master and develop braches and some tags. 
When cloning Repo A and calling the new one Repo B master and develop branches are prefixed with origin/master and origin/develop. 

The problem now is that you cannot do anything with them and the actual fact is that you can only use the master branch that is recreated. 

This is Repo A 
![repo a](https://cloud.githubusercontent.com/assets/5777285/8572569/36bbf4c8-2585-11e5-8ccd-e79133dc9d5b.PNG)
This is Repo B 
![repo b](https://cloud.githubusercontent.com/assets/5777285/8572573/3bd08a46-2585-11e5-868c-5295b303c5d3.PNG)

Does anyone know a workout either to delete the origin/master and origin/develop branches from view or to make them available to use to be able to check them out? 

Thanks in Advance.

**Comment by jakubgarfield** [comment]
When developing, just use the branches without that origin prefix.

```
git checkout master
git push origin master
```

don't do

```
git checkout origin/master
git push origin origin/master
```

As far as deleting branches on remote server concerns - plenty of resources on SO - http://stackoverflow.com/questions/2003505/delete-a-git-branch-both-locally-and-remotely
