### ISSUE TITLE
Unable to push to git repository: /info/refs not valid

### ISSUE THREAD

**Issue by CPUTerminator** [jakubgarfield/Bonobo-Git-Server#290]
The web interface and actions relating to obtaining data from the git repository works just fine (including cloning, fetching selective branches, pulling, etc). But any action that puts information back to the repository and I get that error. I've verified I have write permission to the repository and the error logs show nothing except for the:

`Native library pre-loader is trying to load native SQLite library "C:\inetpub\wwwroot\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll"...`

line present on server startup.

Given that cloning from the repository works fine I know my URL isn't incorrect.

Bonobo Git Server version: 4.0.0
IIS Version: 8.5 on Windows Server 2012 R2

Potentially related to issue #224

**Comment by RedX2501** [comment]
Please try with the newer Bonobo versions. if it is still happening please reopen the issue.
