### ISSUE TITLE
Repository Symlinks

### ISSUE THREAD

**Issue by ChazSII** [jakubgarfield/Bonobo-Git-Server#291]
In **Bonobo.Git.Server.Data.Update.RepositorySynchronizer.CheckForNewRepositories()**, the server errors out if your *App_Data* or *Repositories* folder is a Symlink.

EDIT: Removed fix, didn't pan out after further testing.

**Comment by willdean** [comment]
I can't repro this with either mklink /D or mklink /J.   @ChazSII would it be possible to provide a repro recipe which creates a directory structure that causes this problem?

**Comment by RedX2501** [comment]
If you still experience this issue please reopen this topic.
