### ISSUE TITLE
Windows Authentication could retrieve User's name for better overview

### ISSUE THREAD

**Issue by RedX2501** [jakubgarfield/Bonobo-Git-Server#295]
When executing any action which lists usernames in Windows Authentication mode with an Active Direct it only lists the username although more information is available. This makes editing them quite difficult as most companies usernames are non descriptive as can be seen in the screenshot.

![2015-07-15_09-50-20](https://cloud.githubusercontent.com/assets/929932/8693448/718c3ed0-2ad7-11e5-9188-69a0a87b221f.png)

Would it be possible to retrieve the Name or eMail Address and display it instead or additionally?

**Comment by jakubgarfield** [comment]
So first of all, you'd have to introduce a concept of a display name - you need to have unique username, and I believe full name or emails don't have to be unique.

After that, you need to retrieve this information in WindowsImporter class https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/WindowsIdentityImporter.cs.

Also, there is no updating of this information, so unless some updating mechanism is added those information will get stale over time.

To get a friendlier name - have a look at https://msdn.microsoft.com/en-us/library/system.security.principal.windowsidentity(v=vs.110).aspx if you can get anything relevant from there.
