### ISSUE TITLE
HTTP Hooks

### ISSUE THREAD

**Issue by OO00O0O** [jakubgarfield/Bonobo-Git-Server#299]
GitHub type HTTP hooks for integrations.

**Comment by CoderCow** [comment]
### Open Questions

- [ ] What exactly is GitHub's "Secret" setting and is something like this useful for Bonobo hooks?
- [ ] Should hooks support http basic auth?
- [ ] Is a different format than JSON actually useful?
- [ ] How customizable should the JSON data in the request body be? AFAIK there's no standardized format for the data. Could allow to choose between "GitHub Format", "Bitbucket Format" etc. or even let users configure their own JSON templates.

# Purposed Solution (WIP)

## Triggers for Hooks

**Application Triggers**
* Repository Added
* Repository Deleted
* User Added
* User Deleted
* Team Added
* Team Removed
* Team Members Modified

Hooks for application triggers will be configured in the Bonobo settings.

**Repository Triggers**
* Branch Created
* Branch Deleted
* Branch Modified
* Tag Created
* Tag Deleted
* Repository User Access Modified (triggers for user, team or admin changes)
* Repository Anonymous Push Policity Changed

Hooks for repository triggers can be configured on a per repository basis and globally as part of the Bonobo settings. Whether the global hooks are triggered for a specific repository can be configured in each repository's settings.

## Webhooks

Multiple webhooks can be configured for each trigger. The user can 
* set a custom name and a url to invoke,
* activate and deactivate them,
* test them in the web interface and get immediate feedback,
* turn SSL certification on or off per hook.
