### ISSUE TITLE
404 error when trying to view web.config file from repository browser

### ISSUE THREAD

**Issue by KY4U** [jakubgarfield/Bonobo-Git-Server#302]
Hello,

I'm running a published version of the code dated through 07/28/15.  When using the Repository Browser link I can view a listing of all files in that folder.  I can click on any file EXCEPT web.config in that listing and view the file.  When I click on the web.config file it takes me to a url similar to:
https://mysite.com/git/Repository/repo_name/master/Blob/web.config

Instead of getting a page view of the web.config file I receive a Server Error 404 - File or directory not found.  If I run the application locally the web.config files is displayed properly.

I receive similar results if I browse to a different repository and attempt to view the web.config file.  Same 404 error message.

If it makes any difference the application is running on Windows 2012.

Please advise.

**Comment by latop2604** [comment]
It's working for me but my repositories directory is not at the default location. (Not in the web site directory). You can try that as workaround.
All *.config files are protected by IIS.

**Comment by jakubgarfield** [comment]
It might be related to the IIS web.config protection as latop2604 is suggesting, so I'd suggest looking in that direction and perhaps white listing somehow the URLs (/Repository/*)

**Comment by KY4U** [comment]
It appears that IIS blocks the display of web.config.  I stumbled across this article relating to the issue: 
http://weblogs.asp.net/owscott/iis7-blocks-viewing-access-to-files-in-bin-and-other-asp-net-folders

I'll leave things the way the are.  Thanks for the insight.
