### ISSUE TITLE
Releases / tag page wanted

### ISSUE THREAD

**Issue by NgYueHong** [jakubgarfield/Bonobo-Git-Server#304]
It would be nice if bonobo-git-server can come with a releases / tag page like github. This allow us to easily view all the releases (tag) on a page with information for each tag.

**Comment by kiddailey** [comment]
+1 - I actually thought it already had this for some reason but checking back I don't see it :(

**Comment by willdean** [comment]
Does this need to be anything more complex than the 'commits' page, but filtered to show only tagged commits?

**Comment by RedX2501** [comment]
@willdean I think not. That should pretty much cover it. Should we add this to 6.0?

**Comment by willdean** [comment]
I guess it's about two lines of additional action method to provide a set of data into the existing view, plus a link to it from somewhere.   Like you say, why not do it now - it's low-risk.
