### ISSUE TITLE
Issues with NTFS mountpoint

### ISSUE THREAD

**Issue by electricduck** [jakubgarfield/Bonobo-Git-Server#305]
I have an NTFS mountpoint at C:\inetext\. Whenever Bonobo is set to use a folder inside there, creation of a repo causes the standard error ("An error occurred when processing your request. Please try again or contact the system administrator."). Using a folder outside the mountpoint works.

Interestingly, symlinking to a folder inside the mountpoint (C:\inetext\repo\) to somewhere outside (C:\repo\) works fine and Bonobo is able to create a repo there.

**Comment by larshg** [comment]
Can it be that the IIS user doesn't have the correct rights to your inetext folder? I have a similar error which I tracked down to be a issue in libgit itself [here](https://github.com/libgit2/libgit2/issues/3308).

**Comment by RedX2501** [comment]
Since we haven't heard back in a while i'm closing this.
Please reopen if the issue still exists.
