### ISSUE TITLE
Add Issue Tracking capabilities

### ISSUE THREAD

**Issue by jkildedal** [jakubgarfield/Bonobo-Git-Server#306]
Hi

Is there a plan to add an Issue Tracking system Like what is available here on github?
If not, can you recommend another git repository webbrowsing tool with this feature (which can be installed on Windows Server 2008+ and IIS).

Thanks!

**Comment by jakubgarfield** [comment]
I'd be happy to merge a PR for this feature. Have a look at Jira for issue tracking.

**Comment by jkildedal** [comment]
I will see if I get time for it :)

Would you mind if the frontend for this feature was created in Angular instead of MVC Razor?
I will use WebAPI as backend.

**Comment by jakubgarfield** [comment]
Sorry for the late response, I've been travelling a lot recently. For first implementation, I'd prefer using classic asp.net mvc without any javascript framework. If you'd like to use WebAPI I'd be more happy with React on the front end part (as I can't really support angular as I never worked in it).

**Comment by rasmuseeg** [comment]
I would suggest using anuglar. It's quite easy to get started.

**Comment by megamorf** [comment]
I'd also prefer an angular-based frontend.

**Comment by jakubgarfield** [comment]
The problem with picking Angular is that someone needs to be able to maintain it and that person needs to be committed to Bonobo Git Server for next couple years. Therefore, it will be a hard sell.

**Comment by rasmuseeg** [comment]
Then its best to pick an MVC approach.

**Comment by myduke** [comment]
+1 for Issue Tracking. Happy to contribute

**Comment by jakubgarfield** [comment]
Support for external issue tracking system has been implemented in #384.
