### ISSUE TITLE
TXT preview in repository browser not working for some txt files

### ISSUE THREAD

**Issue by larssb** [jakubgarfield/Bonobo-Git-Server#307]
I have been in communication with the Bonobo Git community at Google forums, more precisely: https://groups.google.com/forum/#!topic/bonobo-git-server/lXv9Jy8Ix-E

After having communicated forth and backup with Jakub he told me to create an issue so here it is :-)

--- SHORT DESCRIPTION, more in the forum post ---
Text files with ANSI encoding, the std. encoding for text files saved on Windows, cannot be shown via the Bonobo Git Server web interface. More specifically it throws the error: "Preview of this file is not supported."
Jakub have been able to reproduce this on the Bonobo Git demo server, with my guidance. 

He told me that lkho, stanshillis and ColinNiu is the programmers to go to on this issue.

Looking forward to hear your opinion.

Thank you and have a great day.

**Comment by larssb** [comment]
Just a polite status enquirer. Have anybody had the time to look at this? :-) have a great day.

**Comment by padremortius** [comment]
Confirm the problem. The bug was created by patch #273

**Comment by larssb** [comment]
@padremortius hmmm ok :-) - so the fix is hopefully around the corner. Looking forward to it and thank you very much for your reply.

Have a great day to you all.

**Comment by larssb** [comment]
Hi guys and girls :-) - is it doable :-D ? Looking forward to being able to view txt files again.

**Comment by larshg** [comment]
@larssb  I have made a pull request that should make it possible to view text files encoded with ansi/windows-1252 in #312.

Can you try it out?

**Comment by larssb** [comment]
Hi @larshg - sure I would love to. In order to test it, do you want me to just download the changed files in the repository manually or will the Bonobo Git Srv version be bumped so that it can be downloaded from the official channels? Asking because I'm not a seasoned vet when it comes to this :-)

Thank you.

**Comment by larshg** [comment]
@larssb as of now @jakubgarfield has already merged my pull-request to the master, so you can checkout the master and build it yourself and "publish" it to a local folder. This can then be copied as if you had downloaded from the official channels.

I don't know when @jakubgarfield has plan for a new release?

**Comment by jakubgarfield** [comment]
I'm not planning the release soon, waiting for more features to pack in. Might do a spontaneous one if I got a spare hour.

**Comment by larssb** [comment]
Hi @larshg - trying to update the server. I'm lacking knowledge on how to build this. Could you be so kind to give me a hint :-)? Also checking it out isn't that pretty much similar to downloading the zip from the main Bonobo GIT Server GitHub project page?

Thank you very much.

**Comment by larssb** [comment]
Hey there :-) - how do I do that build? Any help would be appreciated.

**Comment by larshg** [comment]
Hi @larssb 

I have been quite busy lately - have you tried cloned the master and build it locally?

Else I'll try to help you, if you need it :)

**Comment by larssb** [comment]
Hi @larshg,
I tried to built. I assume I should use the build.cmd file. But it does not work and throws the error:

' error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v11.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. '

It does not seem that the build.cmd file is a general way to do this or am I misunderstanding something. I have looked at the FAQ and the doc. both there and on Github and can't see a description on how to build this.

Any help is therefore appreciated.

Thank you :-D

**Comment by larshg** [comment]
I get the same error when running the build.cmd file. I'm not sure where it gets the v11.0 since I'm using VS2015 and that is v14.0.

Which VS are you using?

Can you just open the the solution and build it in VS? ie Bonobo.Git.server.sln...

**Comment by larssb** [comment]
Hi @larshg - Thank you for your response. I acknowledge I'm very noobie here. However, after having opened the solution in VS I only get an updated version of the Bonobo.Get.Server.dll - but I still have one big mess of various .cs files and so forth, that in no way resemblances a production release of Bonobo GIT Server. So basically I'm very unsure if this is correct and how to get to a state where what I have is a production build of Bonobo GIT Server. I'm sorry but I'm quite new to this.....just let me know if you need more info.

Also just to try it out I replaced the Bonobo.Git.server.dll on the Bonobo GIT server with the one build by VS. The issue still persists (the issue that this case is about in the first place). So I can't be doing things correct here :-(

Thank you very much.

**Comment by larshg** [comment]
Indeed most the .cs files will, when you compile the project end up in being a dll.

If you rightclick on the project, you can select publish. Then use the Release that is properly preselected and it will create a install directory that should be similiar to the official releases :)

**Comment by larssb** [comment]
Hmm that was waaaaaay better :-) - Thank you. I'm running the Windows Authentication setup. So both a Bonobo.Git.Server & Bonobo.Git.Server.Interface. I first started out updating the Bonobo.Git.Server but the TXT preview error is still there for ANSI files. I then thought I might have to update the Bonobo.Git.Server.Interface as well. After I did that the app pool crashes and the eventlog refers to kernelbase.dll and exception 0xe0434352 - but I don't think it has to do with kernelbase.dll. I think it is just the messenger. 

This is not going as hoped :-) - any good ideas? Maybe to wait for an official release......I would just really love to have this thing fixed.

Thank you for your help and your patience @larshg @jakubgarfield

**Comment by larshg** [comment]
Hmm that seems weird.

Is there any error before, that can be more helpful - because the the provided is a somewhat generic error for .net managed application chrashing I think.

I'll try build a fresh and upload to a test location.

Alternatively you try edit the web.config under:

```
<system.web>
    <globalization enableClientBasedCulture="true" uiCulture="auto" />
    <customErrors mode="On" defaultRedirect="Home/Error" />
    <httpRuntime maxRequestLength="102400" />
    <!--<authentication mode="Windows" />-->
...
```
to

```
<system.web>
    <globalization enableClientBasedCulture="true" uiCulture="auto" />
    <customErrors mode="Off" defaultRedirect="Home/Error" />
    <httpRuntime maxRequestLength="102400" />
    <!--<authentication mode="Windows" />-->
...
```

And see if you get an error message before crashing!

**Comment by larshg** [comment]
@larssb I located the error.

In the source folder of bonobo, you can to Bonobo.Git.Server\bin and copy the either x86 or x64 folder to the bin folder on your webserver. This is where SQLite.Interop.dll is residing and it gives me the same error and crashing the app pool as you describes. It is properly not being copied in the current settings of the publish command. @jakubgarfield how can this be added? I'll try take a look but at first glance at the publishing settings, I couldn't find any list etc. should it be added to folder in the project?

Hope it helps the last way - at least it worked here again :)

**Comment by jakubgarfield** [comment]
I thought the SQLite.Interop.dll is added automatically to the build output when you compile the project. The nuget package should take care of it. Under which events does this not happen? (I don't have problems with normal build and release with Visual Studio)

**Comment by larshg** [comment]
They do get copied to the bin folder when building.

But afterwards when I publish(ie. copy all required files to bonobo_install) the project the files doesn't get copied, atleast using VS2015.

**Comment by larssb** [comment]
@larshg yes it works by copying the x86 & x64 folders to .\bin on the server. @jakubgarfield I have the same experience as larshg, the files are not in the 'bonobo_install' folder generated when right clicking in vs2015 and selecting publish. If this could be fixed it would help in the future :-) - thank you.

Also, most importantly, the ANSI files can now be pre-viewed in the browser gui again. Wonderful!
Thank you all and everyone :-D (I can't have missed anyone now)

**Comment by jakubgarfield** [comment]
If I use publish from Visual Studio (right click on the project in solution explorer) it puts the files under /bonobo_install/x86 and /bonobo_install/x64.

**Comment by larshg** [comment]
Closing this one, as the original issue was solved and the other issue with SQLlite.interop.dll should be solved in master.
