### ISSUE TITLE
All the icons are not showing up in Windows 10 host.

### ISSUE THREAD

**Issue by Lywx** [jakubgarfield/Bonobo-Git-Server#314]
Windows 10 Installation with official installation guide. Only difference is that I selected ASP.NET 4.6 in Windows Features (because there is no ASP.NET 4.5), according to http://andikanugraha.com/2015/09/install-bonobo-git-server-4-0-0-on-windows-10/

![image](https://cloud.githubusercontent.com/assets/6576272/9808385/2bd12800-5891-11e5-93e9-be056368d900.png)

Resulting effect is that all the icons are not showing up properly. Since I have no experience with ASP.NET, I could not provide more detailed info.

![image](https://cloud.githubusercontent.com/assets/6576272/9808324/bb9f852c-5890-11e5-83b5-6fa562088a85.png "Fig 1")

![image](https://cloud.githubusercontent.com/assets/6576272/9808332/cabe26ee-5890-11e5-963a-55a4e6940a6e.png  "Fig 2")

**Comment by Amonomen** [comment]
I'd be inclined to think that this isn't a problem with your installation. I'm leaning more towards a browser issue. 

I'll give it a try on windows 10.

**Comment by Lywx** [comment]
@Amonomen I have testest on Internet Explorer and Chrome. There did not seem to be any difference on display.

**Comment by Lywx** [comment]
I contacted Andika Nugraha, the author of 
http://andikanugraha.com/2015/09/install-bonobo-git-server-4-0-0-on-windows-10/. It works ok for him. It felt like something wrong in my environment but I have no idea what is going wrong.

**Comment by jigneshphipl** [comment]
If you are using Microsoft Edge browser then it is reason for issue, because sometime Edge browser do not load and render images/icons on page when page is rendered.

Otherwise I have hosted Bonobo server on Windows 10 Pro and it is working fine with Chrome browser for me.

**Comment by Lywx** [comment]
After I inspected the log in Chrome developer tools, I could see the following errors.

![image](https://cloud.githubusercontent.com/assets/6576272/9900384/f9f288b4-5c92-11e5-8f81-8412b8a95a1b.png)

**Comment by Lywx** [comment]
The files did exist in my disk.

**Comment by Lywx** [comment]
It seems that fonts in Bonobo.Git.Server/Content/fonts are not downloaded correctly. Does that indicate something wrong?

**Comment by jigneshphipl** [comment]
In other, can we say that MIME setting is not done in IIS hosted website?

**Comment by Lywx** [comment]
I didn't see MIME settings in IIS 10.

![image](https://cloud.githubusercontent.com/assets/6576272/9901136/1203e4ca-5c98-11e5-890f-0a5a8e672daa.png)

![image](https://cloud.githubusercontent.com/assets/6576272/9901119/f2cbd860-5c97-11e5-9261-8d14218c5660.png)

**Comment by jigneshphipl** [comment]
Hi,

Try following



[image: Inline image 2]



[image: Inline image 5]




[image: Inline image 4]


Add extension: *.woff2*
MIME type:  application/font-woff2

On Wed, Sep 16, 2015 at 2:56 PM, Wuxiang Lin <notifications@github.com>
wrote:

> I didn't see MIME settings in IIS 10.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/6576272/9901136/1203e4ca-5c98-11e5-890f-0a5a8e672daa.png>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/6576272/9901119/f2cbd860-5c97-11e5-9261-8d14218c5660.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jakubgarfield/Bonobo-Git-Server/issues/314#issuecomment-140684416>
> .
>



-- 

Jignesh Patel / Software Engineer
Jigneshp@digidms.com / +919427590088

DigiDMS Inc.
2222 Morris Ave2nd Floor
http://digidms.com

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company

**Comment by Lywx** [comment]
@jigneshphipl 

Thanks, but I cannot see your image posted here. Can you post them again?

**Comment by jigneshphipl** [comment]
​

On Wed, Sep 16, 2015 at 3:35 PM, Wuxiang Lin <notifications@github.com>
wrote:

> @jigneshphipl <https://github.com/jigneshphipl>
>
> Thanks, but I cannot see your image posted here. Can you post them again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jakubgarfield/Bonobo-Git-Server/issues/314#issuecomment-140694688>
> .
>



-- 

Jignesh Patel / Software Engineer
Jigneshp@digidms.com / +919427590088

DigiDMS Inc.
2222 Morris Ave2nd Floor
http://digidms.com

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company

**Comment by Lywx** [comment]
I solved this problem by following http://stackoverflow.com/questions/21999760/blank-iis8-localhost-page-on-windows-8-laptop:

In Control Panel > Programs > Turn Windows Features On/Off > IIS > WWW Services > Common HTTP Features:

Enable HTTP Redirection and Static Content

I think MIME Type Settings in Web.config is irrelevant in this issues.

**Comment by Lywx** [comment]
@jigneshphipl 

Thanks.
