### ISSUE TITLE
Adding a team with forward slashes in the names breaks access to edit/delete pages

### ISSUE THREAD

**Issue by jaboc83** [jakubgarfield/Bonobo-Git-Server#321]
I added a team named FB/DRF/LE and then tried to edit the team later and I get 404 errors because it throws the slashes in the URL like so: 

`http://git.abc.com/Bonobo/Team/FB/DRF/LE/Edit`

Same thing happens if I try to delete it, so now it's stuck in my system...

**Comment by Matt-17** [comment]
I tried to fix this problem, but the only way to get rid of this, was to change the RouteConfig.cs to use a catchall (the asterisk at id). But then you need to change the order of action and id. 
`routes.MapRoute("Team", 
                            "Team/{action}/{*id}",
                            new { controller = "Team", action = "Detail" });`

Same problem for Users. 

Is there a reason why action comes after id?

**Comment by jakubgarfield** [comment]
Forward slashes should not be supported in the team names and we should add a validation for that. As a temporary workaround I recommend deleting it manually from SQLite database from console.

**Comment by jakubgarfield** [comment]
The reason for the URL is that it is more in accordance to REST.

**Comment by RedX2501** [comment]
@jakubgarfield  maybe we should rethink the action order of the Url. This way it is also easier to support domains in usernames. We would be able to remove the ugly `\` -> `!` hack that i introduced.

**Comment by RedX2501** [comment]
Probably same as #156

**Comment by jakubgarfield** [comment]
Adding an id as a key to a user might be a good solution.
