### ISSUE TITLE
Database storage for Git Repositories

### ISSUE THREAD

**Issue by aboryczko** [jakubgarfield/Bonobo-Git-Server#322]
Hi,

I'm a happy user of Bonobo Git Server and I appreciate all the work that all of you are doing.
I have a suggestion for a feature. Since there is already a database for user management it would be great to also have the repositories themselves in the database (for me it would be great if that database was MS SQL) it would improve backup and restore for the server and of course all those small files wouldn't take full disk sectors.

Kind regards,
Artur

**Comment by jhudsonWA** [comment]
I'm not sure this would work. That's not really how git works. Git is always a file based.

**Comment by jakubgarfield** [comment]
Unfortunately, this is not possible (or not a good trade off as git is file based database).
