### ISSUE TITLE
Best support for Markdown 

### ISSUE THREAD

**Issue by coderdiaz** [jakubgarfield/Bonobo-Git-Server#323]
My markdown isn't show in my repository. I don't know the reason but my markdown it's ok.

This is the message: 

```
Preview of this file is not supported.
```

**Comment by larshg** [comment]
Have you saved your file in default windows encoding, then it might be the same error as present in #307.

There is a fix merged to master already - have you tried it?

**Comment by vermiculus** [comment]
@coderdiaz Are you still having this problem?

**Comment by coderdiaz** [comment]
Yes @vermiculus I update and change the encoding but it's not working.

**Comment by vermiculus** [comment]
What did you change it *to*?

**Comment by larshg** [comment]
@coderdiaz can you upload an example file somewhere?

**Comment by coderdiaz** [comment]
@larshg Yes, I can.

**Comment by vermiculus** [comment]
@coderdiaz Then remove the confidential information...

**Comment by larshg** [comment]
Create a fil in similar encoding/program with gibberish data..  Else it's quite hard to help ;-)

**Comment by larshg** [comment]
The txt file shows properly here, using latest master - but should also work with previous versions as it detects the utf-8 encoding with 1 (ie 100 % sure).
