### ISSUE TITLE
Repository page shows 401 unauthorized instead of redirecting to login

### ISSUE THREAD

**Issue by mm201** [jakubgarfield/Bonobo-Git-Server#324]
If you're not logged in, most pages redirect you to the login page, but the repository webpages (not git endpoints) do not. This becomes very annoying.

**Comment by Matt-17** [comment]
Sound like a duplicate of https://github.com/jakubgarfield/Bonobo-Git-Server/issues/267. Which version have you installed?

**Comment by mm201** [comment]
Looks like it. I didn't think to check closed issues. Sorry.
