### ISSUE TITLE
The commit user is unknown

### ISSUE THREAD

**Issue by clker** [jakubgarfield/Bonobo-Git-Server#328]
Hi friend,

I have setup the server in two PC.

The first one is my laptop and which is windows 8.1 64bit + IIS8. It works perfectly.

The other one is the PC in the lab which is offline and it is windows 7 bit. I installed .NET framework 4.5, ASP.NET MVC 4 and IIS8 **Express**. It also works but the commit user is shown as unknown. 

Any idea? 

Thanks,

**Comment by jakubgarfield** [comment]
You have to configure your git identity on the machine you run your git client.

```
git config --global user.name "John Doe"
git config --global user.email johndoe@example.com
```

https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

**Comment by clker** [comment]
Thanks, the problem is solved.

But I think it should be better to extract the user from the commit because the server know the commit user.

**Comment by jakubgarfield** [comment]
You are right, github is doing it as well so I'll reopen and leave for a community to pick it up.

**Comment by RedX2501** [comment]
@jakubgarfield  Do you mean correlate the commit user to the website user and display that info? But what if the username and email of the commit don't match any of the entries in the DB. Should we keep a log of commit \<-\> user?

**Comment by jakubgarfield** [comment]
If it doesn't match up I'd assumed that the client is configured "incorrectly" and use the username and email from the server database. I'm not sure if the log is necessary.

**Comment by RedX2501** [comment]
I'll close the issue as it was fixed. If we want to correlate the commit user to the website user we should open a new issue for that.
