### ISSUE TITLE
Not redirect correctly after logon using admin:admin

### ISSUE THREAD

**Issue by zhongsp** [jakubgarfield/Bonobo-Git-Server#329]
Hi, I visit http://localhost/Bonobo.Git.Server in browser. After logon using admin: admin.
The page redirect to Logon page again without saying auth error. What's the problem with me..? Thanks

**Comment by bogusz** [comment]
I resolved this issue. Checkout my pull request.

**Comment by zhongsp** [comment]
@bogusz Great! Thanks man.
