### ISSUE TITLE
Teams page don't work on demo server (http://demo.bonobogitserver.com/Team/Index)

### ISSUE THREAD

**Issue by maintainer** [jakubgarfield/Bonobo-Git-Server#331]
<img width="1112" alt="screen shot 2015-10-22 at 6 17 57 pm" src="https://cloud.githubusercontent.com/assets/82028/10662894/066973e6-78ea-11e5-945d-5419ca07cff5.png">

Steps to reproduce:
- create two users
- create team
- add admin and one user to team

**Comment by larshg** [comment]
Hi @maintainer 

I have reproduced the error and submitted a possible fix in #332

**Comment by maintainer** [comment]
Great! Thanks!

**Comment by mykemaas** [comment]
Just did an upgrade today from the official download page at bonobogiterver.com to my personal server, and am seeing the same thing on the teams page.  FYI: Using SqlLite local database.

**Comment by jakubgarfield** [comment]
Hi guys, I'm away from computer and will be back on the 2.11.

In the meanwhile can @ollienator have a look please?
