### ISSUE TITLE
It would be super nice if Bonobo could act as a server for committed HTML

### ISSUE THREAD

**Issue by vermiculus** [jakubgarfield/Bonobo-Git-Server#334]
I'm looking for alternatives to a clunky SVN workflow that's incumbent at work (and not leaving). The SVN repo-browser currently serves an HTML file that I need to make [available via link](http://demo.bonobogitserver.com/Repository/testbonobo/master/Raw/test.html?display=True).

I don't really want to track this project in the SVN – it doesn't fit – so I found Bonobo while searching for git servers. (I'm going to be sharing this project with a small number of friends at work.) I'd still like the HTML to be easily viewable from the browser – it would be super nice if Bonobo could do this for me :smile:

**Comment by RedX2501** [comment]
This is not a goal for this project.
