### ISSUE TITLE
An Error Occurred, when adding a team

### ISSUE THREAD

**Issue by mvklingeren** [jakubgarfield/Bonobo-Git-Server#336]
After i add a team (with the admin as a member, or a single user as a member). I cant view the page anymore. Receiving the message: 

An error occurred when processing your request. Please try again or contact the system administrator.

I cant find a detailed error in the Windows event log, is it possible to get this from somewhere else?
fyi: im running this on a Windows 10, iis (32bit).

**Comment by larshg** [comment]
This is a dublicate of #331 and I have suggest a correction in #332 - you can try out - unless you will wait for a new release :) @mvklingeren

**Comment by jakubgarfield** [comment]
Closed as duplicate
