### ISSUE TITLE
This webpage has a redirect loop - ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by siavashfdst** [jakubgarfield/Bonobo-Git-Server#337]
I have installed bonobo based on install guide.
I am using IIS  7.5  and .Net framework 4.0 in Windows server  2008 R2.

when i go to http://localhost/Bonobo.Git.Server with Chrome browser , this error occures :

    This webpage has a redirect loop
    ERR_TOO_MANY_REDIRECTS

with firefox:

    The page isn't redirecting properly
    Firefox has detected that the server is redirecting the request for this address in a way that will     never complete.

**Comment by larshg** [comment]
Have you disabled anonymous authentication? Because if you have, this happends (atleast for me).
