### ISSUE TITLE
Bonobo 5.0.0 Unable to login on Windows Server 2012 R2 with IIS 8

### ISSUE THREAD

**Issue by Alexander882** [jakubgarfield/Bonobo-Git-Server#339]
When trying to log in on a vanilla version of Bonobo, Chrome returns to the same login page, while Internet Explorer faults with "Unable to display this page".

I'm pretty sure that the issue lies with the fact that the HomeController returns an EmptyResponse while relying on the IAuthenticationProvider to perform Response.Redirect.

Removing the Response.Redirect call in CookieAuthenticationProvider, and changing the EmptyResponse to a RedirectToAction-call fixes the issue (however only when using CookieAuthenticationProvider).

Response.Redirect and ASP MVC is not a good mix as explained here http://blogs.msdn.com/b/rickandy/archive/2012/03/01/response-redirect-and-asp-net-mvc-do-not-mix.aspx

**Comment by JPomichael** [comment]
+1
![qq 20151102100724](https://cloud.githubusercontent.com/assets/1901960/10873067/8ca12d20-8149-11e5-91d1-7acef412dc20.png)

**Comment by larshg** [comment]
Have you guys even looked at already opened/closed issues :) ? ie. #329 #330 #337 #338 ? Anyways there should be a fix in PR #335 ;)

Even though according to your link this might not be the best way to do it - and also, its only for CoookieAuthentication - if you have another suggestion, why don't you make a PR? :)

**Comment by jakubgarfield** [comment]
Closed as duplicate
