### ISSUE TITLE
Active Directory authentication/user-role management doesn't respect nested groups

### ISSUE THREAD

**Issue by hmmwhatsthisdo** [jakubgarfield/Bonobo-Git-Server#340]
The current version of Bonobo does not respect groups nested within groups on Active Directory for login or role-assignment configuration settings.

As a test case, consider the following heirarchy:
* [GroupA]
    * UserOne
    * [GroupB]
        * UserTwo
        * UserThree
    * [GroupC]
        * UserFour

In this situation, most users would expect that granting permissions to GroupA would cause UserOne-UserFour to inherit permissions (most Active Directory-integrated things work this way). However, only UserOne gets these permissions.

**Comment by hmmwhatsthisdo** [comment]
In the mean-time, is there a way to allow multiple groups access to the server or assign multiple groups a role?

**Comment by larshg** [comment]
You can added multiple groups in the config file like its descriped [here](https://bonobogitserver.com/ad-membership/)

**Comment by hmmwhatsthisdo** [comment]
@larshg That doesn't really answer my question, nor does it seem to work. In their example, there is only one group in the ActiveDirectoryMemberGroupName key, and only one ActiveDirectoryRoleMapping key.

Because some people are likely to find this by Googling, the solution is not to add multiple groups to the same line, but rather to have multiple ActiveDirectoryMemberGroupName or ActiveDirectoryRoleMapping keys as needed.

For instance, to grant access to UserOne-UserFour in the example above, the following three lines would need to be inserted into Web.Config:
<add key="ActiveDirectoryMemberGroupName" value="GroupA" />
<add key="ActiveDirectoryMemberGroupName" value="GroupB" />
<add key="ActiveDirectoryMemberGroupName" value="GroupC" />

**Comment by larshg** [comment]
I think I misunderstood you - I thought you where  talking about multiple teams :)

**Comment by Darxis69** [comment]
I also saw a similar problem. When u set AD groups like:
* [Developers]
  *Developer1
   *[DeveloperAdmins]
And in the web.config file you set:
`<add key="ActiveDirectoryMemberGroupName" value="Developers" />
<add key="ActiveDirectoryTeamMapping" value="Developers=Developers" />
<add key="ActiveDirectoryRoleMapping" value="Administrator=DeveloperAdmins" />`
there is an exception thrown in the view https://localhost/Bonobo.Git.Server/Team/Developers

>System.ArgumentException: Value cannot be null or empty.
>Parameter name: linkText
   >at System.Web.Mvc.Html.LinkExtensions.ActionLink(HtmlHelper htmlHelper, String linkText, String actionName, String controllerName, RouteValueDictionary routeValues, IDictionary`2 htmlAttributes)
   >at ASP._Page_Views_Team_Detail_cshtml.Execute() in c:\inetpub\wwwroot\git\Views\Team\Detail.cshtml:line 28

**Comment by hmmwhatsthisdo** [comment]
I believe commit 587dfeaa405be3f544b257f99da07d4fcfafb52f fixed this issue, but I'm not 100% sure - can someone verify?

**Comment by RedX2501** [comment]
I'll be closing this as this should have been fixed on the latest series of PRs. If anyone still experiences this please reopen this issue.
