### ISSUE TITLE
Unable to clone/pull from repository with or without permission/anonymous clone enabled

### ISSUE THREAD

**Issue by hmmwhatsthisdo** [jakubgarfield/Bonobo-Git-Server#344]
After "updating" my Bonobo v5.0.0.0 instance with the fix from #335 (downloaded source, built Bonobo.Git.Server.dll, brought IIS site offline, replaced DLL - if this was a bad idea then I can re-roll from source) and finally getting web login working, I'm noticing that any attempts to clone into a Git repository throws an Authentication Failed error through my Git client and shows the following line in IIS's log files:

    2015-11-03 01:39:01 134.121.124.44 GET /TestRepo.git/info/refs service=git-upload-pack 80 - www.xxx.yyy.zzz git/2.6.2.windows.1 - 401 0 0 640

Toggling anonymous pull/clone still asks for a username/password and still fails to work. We're using AD's membership service - I'm wondering at this point if the fact that our usernames are listed as our email addresses (username@domain.edu) might be related.

Is there a known issue with actual Git usage on Bonobo?

**Comment by larshg** [comment]
I don't know what the issue is, but at my company we are also using the email addresses as username and it works fine, so thats probably not the issue.

**Comment by hmmwhatsthisdo** [comment]
It would appear this was an artifact of my attempted "fix" to #340, which
didn't actually work FWICT.
