### ISSUE TITLE
Windows Authentication is not working.

### ISSUE THREAD

**Issue by patelmitul** [jakubgarfield/Bonobo-Git-Server#345]
Here are two lines from my web.config. In IIS I have set Authentication mode to Anonymous.

    <add key="AuthenticationProvider" value="Windows" />
    <add key="MembershipService" value="ActiveDirectory" />

I have put Bonobo server in Git folder.

When try to go to "http://testiis/Git" I get redirected to
"http://testiis/Git/Home/WindowsLogin?ReturnUrl=%2FGit%2F" with 302 and then to
 "http://testiis/windowsAuthCallback?id=9eb08ac9-3d0c-4097-a2df-cde0fa1bc841"

If I set authentication mode to Windows in IIS then I get unlimited 302 redirects.

I know I have setup AD Domain and Group correctly because there are JSON files in ADBackEnd/Users, ADBackEnd/Teams, ADBackEnd/Roles, and ADBackEnd/Repos folder. They all have correct information form AD.

This is with v5.0

**Comment by larshg** [comment]
Can you try with latest master?

IIS settings should be: Allow anonymous enabled and windows auth off.
web.config should be: as you stated with windows on and AD on

That should work!

**Comment by patelmitul** [comment]
I compiled the latest master and copied Bonobo.Git.Server.dll to server. Restarted IIS and it is still same issue.

**Comment by chrismdev** [comment]
Same issue, config same as above. The config does work using IIS Express but not using IIS.

**Comment by jakubgarfield** [comment]
Unless @Ollienator can help with fixing this issue I recommend going back to 4.0.0 or investigating on your own (and submitting PR would be awesome).

**Comment by patelmitul** [comment]
Does 4.0 require two installation? If it does then can we have those documentation on how to set it up?

**Comment by jakubgarfield** [comment]
https://github.com/jakubgarfield/Bonobo-Git-Server-Web/blob/29f2f9f301d6afd98c93cc8eb4a1864de7ef4c72/content/windows-authentication.md

**Comment by Geaz** [comment]
Have the same problem here.

**Comment by YopparaiNeko** [comment]
Can you try the latest commit?

**Comment by patelmitul** [comment]
It works.
I've compiled and put the new Bonobo.Git.Server.dll in bin folder and it works.

**Comment by RedX2501** [comment]
I have the same issue with 5.0.1 when trying the site under ssl and without ssl.
I have copied App_Data from an existing 3.4.3 installation. I'm trying to use Windows Auth with Internal Membership.
I have also tried with a fresh copy just modifying the AuthenticationProvider to Windows and I get the same error.

**Comment by larssb** [comment]
Hi @RedX2501,

I have the exact same error. Did you figure it out?

**Comment by patelmitul** [comment]
I just downloaded the latest version and compiled it myself. The changes made resolved the login/authentication issue.
Mitul
 

    On Monday, February 15, 2016 2:42 PM, larssb <notifications@github.com> wrote:
 

 Hi @RedX2501,I have the exact same error. Did you figure it out?—

**Comment by RedX2501** [comment]
@patelmitul @larssb The version in master branch works fine for me.

**Comment by larssb** [comment]
@RedX2501 - thank you. I also got it working. Just need Internet Explorer to accept that the domain I use for BonoboGit is actually a 'intranet zone'.

**Comment by vladimir123** [comment]
Hello!
I have troubles with my Bonobo version... I want to use Windows authentication, but when I changed web.config, and go to localhost/Git I can see only blank page....

web.config
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
    
  </configSections>
  <appSettings>
    <add key="webpages:Enabled" value="false" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />

    <add key="UserConfiguration" value="~\App_Data\config.xml" />
    <add key="DefaultRepositoriesDirectory" value="~\App_Data\Repositories" />
    <add key="GitPath" value="~\App_Data\Git\git.exe" />
    <add key="GitHomePath" value="~\App_Data" />
    <add key="RecoveryDataPath" value="~\App_Data\Recovery" />
    
    <add key="AuthenticationProvider" value="Windows" />
    

    

    <add key="MembershipService" value="ActiveDirectory" />
    <add key="ActiveDirectoryDefaultDomain" value="GITSRV.local" />
    <add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" />
    <add key="ActiveDirectoryMemberGroupName" value="Git" />
    <add key="ActiveDirectoryTeamMapping" value="Developers=GitTeam" />
    <add key="ActiveDirectoryRoleMapping" value="Administrator=GitAdmins" />

    
  </appSettings>
  <connectionStrings>
    <add name="BonoboGitServerContext" connectionString="Data Source=|DataDirectory|Bonobo.Git.Server.db" providerName="System.Data.SQLite" />
    
  </connectionStrings>
  <system.diagnostics>
    <trace autoflush="true" indentsize="4">
      <listeners>
        <add name="errorListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="App_Data/Bonobo.Git.Server.Errors.log" />
        <remove name="Default" />
      </listeners>
    </trace>
  </system.diagnostics>
  <system.web>
    <globalization enableClientBasedCulture="true" uiCulture="auto" />
    <customErrors mode="On" defaultRedirect="Home/Error" />
    <httpRuntime maxRequestLength="102400" />
    <authentication mode="None" />
    <compilation debug="false" targetFramework="4.5" />
  </system.web>
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />
    <handlers>
      <remove name="UrlRoutingHandler" />
    </handlers>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="104857600" />
        <fileExtensions allowUnlisted="true">
          <clear />
        </fileExtensions>
        <hiddenSegments>
          <clear />
        </hiddenSegments>
      </requestFiltering>
    </security>
  </system.webServer>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="WebGrease" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.6.5135.21930" newVersion="1.6.5135.21930" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Antlr3.Runtime" publicKeyToken="eb42632606e9261f" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.0.2" newVersion="3.5.0.2" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IdentityModel.Tokens.Jwt" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.20622.1351" newVersion="4.0.20622.1351" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Protocol.Extensions" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.0.2.33" newVersion="1.0.2.33" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="v11.0" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
      <provider invariantName="System.Data.SQLite" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
      <provider invariantName="System.Data.SQLite.EF6" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
    </providers>
  </entityFramework>
  <system.data>
    <DbProviderFactories>
      <clear />
      <remove invariant="System.Data.SQLite.EF6" />
      <add name="SQLite Data Provider (Entity Framework 6)" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite (Entity Framework 6)" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6" />
      <add name="SQLite Data Provider" invariant="System.Data.SQLite" description=".Net Framework Data Provider for SQLite" type="System.Data.SQLite.SQLiteFactory, System.Data.SQLite" />
    </DbProviderFactories>
  </system.data>
</configuration>`

can anyone help with it? 
Bonobo 5.2 latest version from site
IIS 8.5
OS: Windows Server 2012
