### ISSUE TITLE
Administrator should not be an option if it's mandatory

### ISSUE THREAD

**Issue by ldanster** [jakubgarfield/Bonobo-Git-Server#352]
![image](https://cloud.githubusercontent.com/assets/3726917/10971894/53a9aa5e-83df-11e5-80e4-ce80c57165d5.png)

**Comment by jakubgarfield** [comment]
If there are more users in the system, you can select more than one to be administrator of the repository. But there has to be at least one.

The message is not very descriptive though and such a good English :)
