### ISSUE TITLE
Switch repository icons from ugly jpg to nice png

### ISSUE THREAD

**Issue by carlosefonseca** [jakubgarfield/Bonobo-Git-Server#361]
Uploaded repository icons are being converted to jpeg and they look awful, full of compression artifacts, and transparency is being discarded, with black on its place.

Please consider switching to PNG, where there will be no compression artefacts and transparency is  kept.

I'm using Bonobo Git Server (4.0.0.0)

**Comment by RedX2501** [comment]
@mischalandwehr any chance of turning the the referenced commit into a PR?

**Comment by mischalandwehr** [comment]
It's already done and merged to the master branch.
