### ISSUE TITLE
Windows Authentication URL is too long

### ISSUE THREAD

**Issue by tmintner** [jakubgarfield/Bonobo-Git-Server#371]
For some reason when I try to use Windows Authentication it comes back with a URL that IIS claims is too long.  The syntax of the URL does not look correct:
http://localhost:80/Bonobo.Git.Server/Home/WindowsLogin?ReturnUrl=%2FBonobo.Git.Server%2FHome%2FWindowsLogin%3FReturnUrl%3D%252FBonobo.Git.Server%252FHome%252FWindowsLogin%253FReturnUrl%253D%25252FBonobo.Git.Server%25252FHome%25252FWindowsLogin%25253FReturnUrl%25253D%2525252FBonobo.Git.Server%2525252FHome%2525252FWindowsLogin%2525253FReturnUrl%2525253D%252525252FBonobo.Git.Server%252525252FHome%252525252FWindowsLogin%252525253FReturnUrl%252525253D%25252525252FBonobo.Git.Server%25252525252FHome%25252525252FWindowsLogin%25252525253FReturnUrl%25252525253D%2525252525252FBonobo.Git.Server%2525252525252FHome%2525252525252FWindowsLogin%2525252525253FReturnUrl%2525252525253D%252525252525252FBonobo.Git.Server%252525252525252FHome%252525252525252FWindowsLogin%252525252525253FReturnUrl%252525252525253D%25252525252525252FBonobo.Git.Server%25252525252525252FHome%25252525252525252FWindowsLogin%25252525252525253FReturnUrl%25252525252525253D%2525252525252525252FBonobo.Git.Server%2525252525252525252FHome%2525252525252525252FWindowsLogin%2525252525252525253FReturnUrl%2525252525252525253D%252525252525252525252FBonobo.Git.Server%252525252525252525252FHome%252525252525252525252FWindowsLogin%252525252525252525253FReturnUrl%252525252525252525253D%25252525252525252525252FBonobo.Git.Server%25252525252525252525252FHome%25252525252525252525252FWindowsLogin%25252525252525252525253FReturnUrl%25252525252525252525253D%2525252525252525252525252FBonobo.Git.Server%2525252525252525252525252FHome%2525252525252525252525252FWindowsLogin%2525252525252525252525253FReturnUrl%2525252525252525252525253D%252525252525252525252525252FBonobo.Git.Server%252525252525252525252525252FHome%252525252525252525252525252FWindowsLogin%252525252525252525252525253FReturnUrl%252525252525252525252525253D%25252525252525252525252525252FBonobo.Git.Server%25252525252525252525252525252FHome%25252525252525252525252525252FWindowsLogin%25252525252525252525252525253FReturnUrl%25252525252525252525252525253D%2525252525252525252525252525252FBonobo.Git.Server%2525252525252525252525252525252Flogin.aspx%2525252525252525252525252525253FReturnUrl%2525252525252525252525252525253D%252525252525252525252525252525252fBonobo.Git.Server

**Comment by YopparaiNeko** [comment]
Double check to make sure IIS Authentication settings has Anonymous Authentication Enabled and everything else Disabled.

**Comment by chrismdev** [comment]
This is a bit of a side note and not directly related to your problem, but if you are using the Active Directory provider then make sure you set your application pool identity to an account that can access active directory, such as network service.

**Comment by tmintner** [comment]
I got it working with Cookies authentication and not Windows authentication so that is a good enough workaround for now.  It would be nice if I could just use Windows authentication and not have to do the form based authentication at all.

**Comment by larshg** [comment]
You should be able to use Windows authentication, if you have only enabled Anonymous in IIS and in the webconfig enabled Windows authentication. I also experienced the redirection when I had enabled windows auth in IIS settings.

**Comment by RedX2501** [comment]
I assume this got fixed as we have not heard anything else from you.
If the problem persists please reopen.

**Comment by tmintner** [comment]
Thanks yes. I was able to work around it.  You can close it.  I still have
the issue if trying to use Windows authentication outside of forms (single
sign on) but it works fine with the forms

**Comment by baqshi** [comment]
i'm currently having the same issue with windows server 2016 and visual studio 2015.

is there any update on the solution??
