### ISSUE TITLE
Change User Display When Creating/Modifying Repository

### ISSUE THREAD

**Issue by kars85** [jakubgarfield/Bonobo-Git-Server#374]
Hi,

I'm wondering if someone might know where to look and modify what is displayed on the Create/Modify repositories page for user delegation as contributor or administrator. I've looked in the database tables, but their must be some ASP work being down to retrieve user values. I hope to set the display to be Lastname, FirstName instead of username

Our facility uses two factor authentication, with the Active Directory usernames setup as their smartcard UPN number, not their legacy firstinitiallastname. Administrative account still use a readable username starting with ap., but normal users are set to UPN.

Thanks!

![IMAGE](https://cloud.githubusercontent.com/assets/6616548/11629308/12a6e1ba-9cbd-11e5-8231-0ebc5a1fc957.png)

**Comment by RedX2501** [comment]
Same as #295
