### ISSUE TITLE
Scripted Repository Creation

### ISSUE THREAD

**Issue by jRichardeau** [jakubgarfield/Bonobo-Git-Server#376]
It would be wonderful if we could create repositories from command line in order to automate some processes !!

**Comment by RedX2501** [comment]
You actually can just create a bare repo in your folder and it will be found by Bonobo.
It will have all the default access rights.

**Comment by jRichardeau** [comment]
Is it planned ?

**Comment by RedX2501** [comment]
What features are you missing?

**Comment by jRichardeau** [comment]
Scripted repository creation

**Comment by RedX2501** [comment]
Yes, i get that from the title.

Maybe you can use more then one sentence in an answer and explain, what YOU undersrtand under that term.

Where do you expect to run it? On the server? Should it be a REPL? How do you expect to do authentication?

Maybe write a small use-case with mock invocations of the things you expect it to do?

**Comment by jRichardeau** [comment]
For instance I also use GitBlit, and with that repo I can push on a non-existing repository and it creates it, with same authentication as the other git commands.
Do you need more details ?

**Comment by RedX2501** [comment]
Ok, now I understand what you mean.
Maybe we should make this an option.
