### ISSUE TITLE
AD integration issues

### ISSUE THREAD

**Issue by mattepi** [jakubgarfield/Bonobo-Git-Server#378]
I've encountered a few issues in using the Active Directory integration:

1. Nested group permissions don't work
2. Logging in without specifying a domain does not work throughout the system. The login occurs but the roles are not properly populated.
3. Username is case sensitive when loading the roles, which may be an issue for AD users who do not know the casing of their username in AD.

**Comment by RedX2501** [comment]
@mattepi Since the merge of your PR is this still happening?

**Comment by mattepi** [comment]
After applying my changes I no longer see the issues mentioned.
