### ISSUE TITLE
Lost admin password

### ISSUE THREAD

**Issue by rieksmoleman** [jakubgarfield/Bonobo-Git-Server#380]
How can i reset the admin password, or how to change it in a way that i can login again as admin

**Comment by nickalbrecht** [comment]
By default, It's stored in the Bonobo.Git.Server.db file, which is a SQLLite database I believe. Something like http://sqlitebrowser.org/ should be able to help you out.

**Comment by rieksmoleman** [comment]
I solved the problem. In the release notes there was a encoded password for admin. By using a SqlLite manager i was able to patch the password in de user table. After that i had access again.
