### ISSUE TITLE
Active Directory Authentication - Not working on this cirscumstance

### ISSUE THREAD

**Issue by newcmelgar** [jakubgarfield/Bonobo-Git-Server#381]
Hi, 
First of all, thank you for the great work. Thanks to this project I dropped my bulky and heavy Atlassian Bitbucket Server. 

Here is my issue/scenario: 

- I have my IIS behind a pfsense firewall with 192.168.30.0/24 LAN. 
- I have a public IP doing NAT Forwarding to my LAN IP for my IIS
- I have my DNS pointing to the above public IP. Say we're using git.mypublicdomain.com 
- The IIS server is part of the AD

If I go to git.publicdomain.com from the IIS server, I can't authenticate. I get a response back a blank page from the server with the URL: http://git.publicdomain.com/windowsAuthCallback?id=0205d3db-0f58-4b32-81a2-aef5bbdb695b

If I inspect the page source, this is what I find: 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="/favicon.ico?v=2" type="image/x-icon" />
    <title>404 Page Not Found :: My Git Server</title>
    <link href="/Content/bundled.css?v=UEA_jcKENnoJEuanvgU2XUQHPuchSvwtdp67eanQevs1" rel="stylesheet"/>

</head>
<body class="windowsAuthCallback Index">
    <div class="main">
        <div class="header">
            <div class="navigation pure-menu pure-menu-open pure-menu-horizontal">
                <a class="pure-menu-heading" href="/">My Git Server</a>

                <ul>
                                                                <li><a href="/Home/LogOn"><i class="fa fa-sign-in"></i> Sign In</a></li>
                </ul>
            </div>
        </div>

        <div class="content">
            

<h1>404 Page Not Found</h1>
<div>
    <p class="summary-error">The page you were looking for wasn&#39;t found. Please try again or contact the system administrator.</p>
</div>

        </div>

        <div class="footer">
            <p>
                Bonobo Git Server (5.0.1.0) &copy; 2015 <a href="http://www.chodounsky.net">Jakub Chodounský</a>
                &middot; <a href="http://bonobogitserver.com/">Official Page</a> 
                &middot; <a href="https://github.com/jakubgarfield/Bonobo-Git-Server">Github</a>
            </p>
        </div>
    </div>

    <script src="/bundled.js?v=rdN2JJVuABjROsps5FwYDE6LuZHYi_5ddjDmg6h93FU1"></script>

    
</body>
</html>

If I go to git.publicdomain.com from a PC on the same LAN or from the other side of the pfsense firewall, it works just fine. 

Regards, 

Carlos

**Comment by NubCoda** [comment]
Hey,

I think this problem is a know issue and already fixed. But there is no version for it yet. I cloned the reposititory and compiled and myself. Then replaced the bonobo.git.server.dll and now it is working fine.

**Comment by RedX2501** [comment]
This should be fixed in 5.1.1 please try out that version.
If the problem persists please reopen.
