### ISSUE TITLE
Markdown <pre> interpreted as <code> not working with backtick.

### ISSUE THREAD

**Issue by aaroncalderon** [jakubgarfield/Bonobo-Git-Server#382]
# Issue 

I have a Readme.md file on one of my repositories.  A snippet of the mark down is as follows:

<pre>
```
git clone http://localhost/git/n-ldapjs.git
   cd n-ldapjs 
npm install
```
</pre>
Expecting the block to be interpreted as `<pre>`, like enclosed in three backticks  __```__. But the code shows interpreted as `<code>` and shows as: `git clone http://localhost/git/n-ldapjs.git
   cd n-ldapjs 
npm install`
As if only one backtick was used.

I realize that I can also indent the text with four spaces and acheive the same `<pre></pre>` rendering, but I'm trying to document my repositories and I am used to many of the features from GitHub. Just wondering if there could be a way to address this.

# Work Around
As a work around I can use the HTML tag `<pre>$code.goes.here() </pre>`, or indent by four spaces, but I would expect similar Markdown features from the Bonobo since it replaces GitHub on my server.

# Conclusion

In the end this will boil down to a feature request. Since, there is a way to achieve the same end result, but in my opinion, the desired similarity between Git's and Gonobo's Markdown interpreters is strong.

Thanks.

## Update:

I reviewed the code and seems that Bonobo uses [MarkdownDeep](http://www.toptensoftware.com/markdowndeep/) to support displaying markdown pages in the repositories. So, the use of three backticks to define a code block is not part of the markdown implementation.

**Comment by RedX2501** [comment]
Maybe you should open an issue with the MarkdownDeep developers and close this issue.

**Comment by aaroncalderon** [comment]
Well, MarkdownDeep's enphasys is to support the markdown standard as defined by [Daring Fireball](http://daringfireball.net/projects/markdown/) on his website. But, as I mentioned above, Bonobo-Git-Server aims at being a Git implementation for Windows, kind of GitHub-ish, or at least I think it should. So, I would expect Gonobo-Git-Server users will expect this to be a feature.

I myself looked into this and found a way to use a JavaScript library, [marked](https://github.com/chjj/marked) to gain some additional GitHub Markdown features on Gonobo-Git-Server.

My approach completely replaces the current MarkdownDeep implementation, so I do not know if a Pull Request would be welcomed. 

If anything, I would like to look in to it further and add an option to either use MarkdownDeep or marked. 

Or better yet, use __marked__ as the only markdown implementation and use its options to choose to parse markdown as 'standard' markdown or GitHub Markdown. But, I have not had the time to work on that right now. When I do, I will send a Pull Request for sure.

Regards
