### ISSUE TITLE
Viewing Commits for a large repository takes a long time to render

### ISSUE THREAD

**Issue by esontag** [jakubgarfield/Bonobo-Git-Server#389]
Hi Jakob,
Wanted to thank you first for creating Bonobo.  Ive been looking for a simple windows based git server for a long time and so far this seems to fit the bill very well.  

We have a repo that's quite old and has a large commit history and also is decently large.  I've noticed that it takes sometimes more than 5 minutes for the Commit page to render and was curious if there's something we can do to remedy this?  (Optimize the git repo on the server perhaps).  Any suggestions are welcome.  Also, by contrast we had no issues when we were running on ubuntu.gitweb for this same repo.  Thanks in advance.

**Comment by jakubgarfield** [comment]
At the moment, the algorithm for loading the commits and getting the tree is not optimal - it's (was) due to the lack of methods on libgitsharp api side - it might be worth revisiting if someone wants to pick it up.

**Comment by latop2604** [comment]
This should be fixed in #402
