### ISSUE TITLE
Anonymous Access Stopped Working after Upgrade

### ISSUE THREAD

**Issue by askasok** [jakubgarfield/Bonobo-Git-Server#390]
I just upgraded Bonobo Git 3.4.2 to 5.0.1.

Now we are no longer able to access the repositories anonymously even though the checkbox is marked. I took the default settings when I upgraded. I tried pull and clone and both are requesting username/password. Any suggestions will be greatly appreciated. -Alex
![image](https://cloud.githubusercontent.com/assets/16605981/12192666/9393c982-b595-11e5-8550-a795223b2d1f.png)

Server 2012 R2

PS  Bonobo Git Server is such a great tool. Thank you!

**Comment by RedX2501** [comment]
Same issue as #344

**Comment by askasok** [comment]
I just tried upgrading to the latest 5.1.1. The issue is not resolved.

I am still getting an error trying to pull anonymously: **Fatal: Authentication failed**.

When I roll back to version 3.4.2 it works fine. Please reopen this issue.

Thank you.

Alex

**Comment by askasok** [comment]
@RedX2501 should I repost this as a new issue since it's been closed?

**Comment by RedX2501** [comment]
We have reworked the access in the latest (not officially released) version.

Try the version from appveyor and see if it is working there.

Appveyor.com/jakubgarfield/bonobo-git-server

**Comment by askasok** [comment]
That URL is not working. It says The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by RedX2501** [comment]
Was typing by heart and made a mistake. Here is the proper link:
https://ci.appveyor.com/project/jakubgarfield/bonobo-git-server/build/artifacts

**Comment by askasok** [comment]
Unfortunately I have to stick to released versions only (work policy).

Any chance of releasing this fix soon?

Thanks.

**Comment by RedX2501** [comment]
Can you at least try it out on a dev server? Because it would be a shame to put out a version and not have it fixed.

**Comment by askasok** [comment]
Good point. I will try it this week and report back.
