### ISSUE TITLE
Active Directory White Listing

### ISSUE THREAD

**Issue by davidmn** [jakubgarfield/Bonobo-Git-Server#391]
We are setting up a Bonobo server and are looking to use AD for authentication. Would it be possible to use AD to authenticate but only for a list of users? 

I know this is possible by using AD Groups but it would fit our workflow better if the admin(s) could manage this list through the web interface rather than asking our systems team to add or remove users from groups.

Absolutely loving Bonobo so far. Seems  to do everything else we want.

**Comment by RedX2501** [comment]
Is it enough to have the admin add the user beforehand to the list of known users?

**Comment by RedX2501** [comment]
Same as #56 IMHO.
Please reopen if that method of white-listing users is not an option for you.
