### ISSUE TITLE
Unable to execute package.cmd with VS2013

### ISSUE THREAD

**Issue by RedX2501** [jakubgarfield/Bonobo-Git-Server#395]
This is due to msbuild no longer being deployed with VS.

See http://blog.maskalik.com/msbuild/2014/03/04/changes-in-msbuild-with-visual-studio-2013/

The basic fix is to tell build.cmd to use whatever msbuild it finds first instead of having an absolute path.

```
@echo off
set startPath=%cd%
set startDrive= %startPath:~0,2% 
set fileDrive=%~dp0
%fileDrive:~0,2% 
cd %~dp0
msbuild build.msbuild  /m:4 %*
%startDrive%
cd %startPath%
```

**Comment by jakubgarfield** [comment]
I don't use package.cmd myself. Would you be keen to submit PR?

**Comment by RedX2501** [comment]
I'd be glad to provide a PR but it will be exactly the same as the code provided above so maybe you just want to copy paste it?

BTW what release method do you use? Maybe we should use that too to make sure errors like #393 don't happen anymore.

**Comment by jakubgarfield** [comment]
Awesome, thank you :)
