### ISSUE TITLE
Found invalid hex digit in length

### ISSUE THREAD

**Issue by JohnGalt1717** [jakubgarfield/Bonobo-Git-Server#40]
It appears that Bonobo is not compatible with Microsoft's Visual Studio 2012 Update 2 Git support. It always throws this while doing a push to the bonobo hosted repository.

Also looks like bonobo is using a very old version of gitsharp which looks like it may be the case of this...

**Comment by softlion** [comment]
I'm hitting this issue with 3.5.0 and VS2013
