### ISSUE TITLE
Package.cmd and deploy-apps.cmd is outdated

### ISSUE THREAD

**Issue by RedX2501** [jakubgarfield/Bonobo-Git-Server#401]
@jmagly introduced package.cmd and deploy-apps.cmd in 2014. With the new 5.0 version which no longer requires two interfaces, these need to be updated.

It would be interesting to know what process @jakubgarfield uses so we could automate that to use with the new AppVeyor integration.

**Comment by jakubgarfield** [comment]
I use only the Publish function of VS project, nothing too special. The configuration I'm using is Release.
