### ISSUE TITLE
Connect AppVeyor to this repository

### ISSUE THREAD

**Issue by latop2604** [jakubgarfield/Bonobo-Git-Server#406]
Now that file Appveyor.yml has been added, it will be easy to setup.
It will provide a "Nightly build" like endpoint as artifact. 
Non-developers will have the option to download a zip of the latest version instead of waiting for the official release. Useful to quickly close issue.

**Comment by latop2604** [comment]
This is a 10 click max task if you signup with your GitHub account.
https://ci.appveyor.com/signup
I can provide you a step by step tutorial if you want.

**Comment by jakubgarfield** [comment]
Wow, that was easy - thanks for setting that up @latop2604.

The builds are available at https://ci.appveyor.com/project/jakubgarfield/bonobo-git-server
