### ISSUE TITLE
Update migrating doc to account for username change with PR #400

### ISSUE THREAD

**Issue by RedX2501** [jakubgarfield/Bonobo-Git-Server#408]
With PR #400 i was forced to update the username to \<domain\>!\<username\> in the DB. The old format was \<domain\>\\\<username\>.

We should inform users that they need to updathe their DBs if the wish to use WindowsAuth with Internal DB.

Maybe we should provide an update script?

**Comment by jakubgarfield** [comment]
You can create automatic database migrations - have a look at `Bonobo-Git-Server/Bonobo.Git.Server/Data/Update/` folder and a few implementations there.
