### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jakubgarfield** [jakubgarfield/Bonobo-Git-Server#41]
Search commit, tag, branch, file, content, ...

**Comment by alexchandel** [comment]
GitHub searches repository names, user names (equivalent to repository groups, which Bonobo lacks), file content, and issue content (which Bonobo lacks).

Forget searching past commits for now. Implementing simple file content searching (globally and per-repository) would be a major stepping stone.

**Comment by jakubgarfield** [comment]
Any pull request with even the basic search capabilities would be very appreciated.

**Comment by RedX2501** [comment]
Closed by #421
