### ISSUE TITLE
why not support git-large

### ISSUE THREAD

**Issue by dvgamer** [jakubgarfield/Bonobo-Git-Server#413]
git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags origin master:master
Pushing to ...

WARNING: These git config values clash:

  git config "color.branch" = "auto"
  git config "color.branch" = "false"
WARNING: These git config values clash:
  git config "color.diff" = "auto"
  git config "color.diff" = "false"
WARNING: These git config values clash:
  git config "color.status" = "auto"
  git config "color.status" = "false"

Repository or object not found: http://....../info/lfs/objects
Check that it exists and that you have proper access to it
Repository or object not found: http://......./info/lfs/objects
Check that it exists and that you have proper access to it

Git LFS: (0 of 2 files) 0 B / 892.00 KB                                        

error: failed to push some refs to 'http://...'

Completed with errors, see above.

**Comment by RedX2501** [comment]
Same as #342
