### ISSUE TITLE
Adding new test toMsysgitIntegrationTests

### ISSUE THREAD

**Issue by RedX2501** [jakubgarfield/Bonobo-Git-Server#414]
I'd like to add tests for anonymous push/pull.

But I am unable to get the MsysgitIntegrationTests to run. I am able to run all the other tests.

It seems to need a started version of the server but AFAIK the unit tests don't start a whole server? What am I missing?

This is on Visuals Studio 2013.

**Comment by jakubgarfield** [comment]
First of all, sorry for those tests being a little bit wonky - they are more like a regression.

The idea is that you have a server running (Ctrl + F5 with Visual Studio and use the port to modify RepositoryUrl) and you create a repository called Integration (that is empty) on the server.

After that it will run a series of commands with different versions of git and clean after itself. The tests are working on matching the output from the client to a hard coded string in resources.

**Comment by jakubgarfield** [comment]
Also note, that the Git clients needs to be in a specific directory under GitPath + combination of a version

**Comment by RedX2501** [comment]
#416 added some notes for exactly the things you mentioned that need to be setup.
