### ISSUE TITLE
Wrong "service" when pushing to remote repository

### ISSUE THREAD

**Issue by larshg** [jakubgarfield/Bonobo-Git-Server#428]
Pushing as admin with cookie auth and internal db - freshly compiled standard settings etc.

As seen on the image, the service string is: "git-receive-pack" - even though this should have been routed to SecureReceivePack - any who has an idea why the routing is wrong? or did I misunderstood something, @jakubgarfield ?

![image](https://cloud.githubusercontent.com/assets/1165340/12533538/e1bf7e9a-c232-11e5-89e6-08a0a1223709.png)

**Comment by RedX2501** [comment]
You forgot to mention, dies it still work although the string seems wrong? 

Here is some more info on the protocols https://git-scm.com/book/be/v2/Git-Internals-Transfer-Protocols

**Comment by larshg** [comment]
No it does not work - thats why I posted it - it seem that your [change](https://github.com/jakubgarfield/Bonobo-Git-Server/commit/6a8063e6228b3fc41e8c12fd49a3a00d20408f9d) to fix the anonymous clone change it.

The first boolean condition can give access alone no matter what the service string is - so if the user had access before the above patch, it would succeed and return the info refs.

If I manually jumped to return the info refs with master it did succeed though :)  - Thanks for the link of the protocols - I'll have a look at it soon hopefully :D
