### ISSUE TITLE
Unable to login via TortoiseGIT

### ISSUE THREAD

**Issue by khorvat** [jakubgarfield/Bonobo-Git-Server#43]
Hi,

  after I have pulled the latest build I can't login to GIT Server via the TortoiseGIT. I can login to Bonobo Server stable version installed on my server. I have preform GitController debug and it seems that there are two requests after credentials have been provided by the TortoiseGIT. First request sends empty username and returns unauthorized while second one sends the username but it seems to be too late.

Thoughts ?

**Comment by gikerix** [comment]
Hi. I set up authentication based on Active Directory Membership Service and I can login to the web site, but I can't clone my repository using my domain credentials using TortoiseGIT. I use latest version. Could you help me?
