### ISSUE TITLE
Problems with Update from 4.0 to 5.1.1

### ISSUE THREAD

**Issue by hadzira** [jakubgarfield/Bonobo-Git-Server#432]
I have deleted all files except App_Data for the update but when I want to open the site a runtime error is showed.

Server Error in '/Bonobo.Git.Server' Application.

Runtime Error

Description: An exception occurred while processing your request. Additionally, another exception occurred while executing the custom error page for the first exception. The request has been terminated. 

What means that? please help me

**Comment by RedX2501** [comment]
- What are you configurations?
 - What is your MembershipService?
 - What is our AuthenticationProvider?

in the root folder in `web.config` change:

    <customErrors mode="On" defaultRedirect="Home/Error" />

to

    <customErrors mode="Off" defaultRedirect="Home/Error" />

And please post the message you get.

**Comment by hadzira** [comment]
During the change I got this message:

Server Error in '/Bonobo.Git.Server' Application.

Access to the path 'd:\InetPub\waproot\Bonobo.Git.Server\App_Data\config.xml' is denied.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.UnauthorizedAccessException: Access to the path 'd:\InetPub\waproot\Bonobo.Git.Server\App_Data\config.xml' is denied. 

ASP.NET is not authorized to access the requested resource. Consider granting access rights to the resource to the ASP.NET request identity. ASP.NET has a base process identity (typically {MACHINE}\ASPNET on IIS 5 or Network Service on IIS 6 and IIS 7, and the configured application pool identity on IIS 7.5) that is used if the application is not impersonating. If the application is impersonating via <identity impersonate="true"/>, the identity will be the anonymous user (typically IUSR_MACHINENAME) or the authenticated request user. 

To grant ASP.NET access to a file, right-click the file in File Explorer, choose "Properties" and select the Security tab. Click "Add" to add the appropriate user or group. Highlight the ASP.NET account, and check the boxes for the desired access.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[UnauthorizedAccessException: Access to the path 'd:\InetPub\waproot\Bonobo.Git.Server\App_Data\config.xml' is denied.]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +216
   System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) +1430
   System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy) +205
   System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) +87
   Bonobo.Git.Server.Configuration.ConfigurationEntry`1.Load() +167
   Bonobo.Git.Server.Configuration.UserConfiguration.Initialize() +52
   Bonobo.Git.Server.MvcApplication.Application_Start() +125

[HttpException (0x80004005): Access to the path 'd:\InetPub\waproot\Bonobo.Git.Server\App_Data\config.xml' is denied.]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +12601933
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +175
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +304
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +404
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +475

[HttpException (0x80004005): Access to the path 'd:\InetPub\waproot\Bonobo.Git.Server\App_Data\config.xml' is denied.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +12618980
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +12458597

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34274

**Comment by RedX2501** [comment]
I'd say because you copy posted the App_data folder the write permission
for iis got lost.

Re-add the permission as instructed on the installation instruction and it
should work.
Am 26.01.2016 19:29 schrieb "hadzira" <notifications@github.com>:

**Comment by RedX2501** [comment]
Please reopen if the issue still exists.
