### ISSUE TITLE
Switching to Active Directory Member Service HttpException - Value cannot be null error.

### ISSUE THREAD

**Issue by larssb** [jakubgarfield/Bonobo-Git-Server#433]
Hi fellow Bonobo Git Server users,

I am trying to get up to the latest version of Bonobo Git Server, unfortunately I'm having some issues doing that. 
I have gone through the setup guide/documentation several times and cannot see that I'm doing anything wrong during setup. 

When I browse the website I get a runtime error in the browser and the windows event log on the server running Bonobo Git gives me this:

----
Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 27-01-2016 18:26:36 
Event time (UTC): 27-01-2016 17:26:36 
Event ID: 2cfdc7d0b3d84a458c980cc6bd01fa9f 
Event sequence: 2 
Event occurrence: 1 
Event detail code: 0 
 
Application information: 
    Application domain: /LM/W3SVC/1/ROOT/Bonobo.Git.Server-2-130983891948993281 
    Trust level: Full 
    Application Virtual Path: /Bonobo.Git.Server 
    Application Path: C:\inetpub\wwwroot\Bonobo.Git.Server\ 
    Machine name: REVISIONCONTROL 
 
Process information: 
    Process ID: 4272 
    Process name: w3wp.exe 
    Account name: 'DOMAIN\USERNAME'
 
Exception information: 
    Exception type: HttpException 
    Exception message: Value cannot be null.
Parameter name: virtualPath
   at System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app)
   at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
   at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
   at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
   at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)

Value cannot be null.
Parameter name: virtualPath
   at System.Web.VirtualPath.Create(String virtualPath, VirtualPathOptions options)
   at Bonobo.Git.Server.Data.ADBackend.<>c.<.ctor>b__18_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Bonobo.Git.Server.Data.ADRepositoryRepository.GetRepository(String name)
   at Bonobo.Git.Server.Data.Update.RepositorySynchronizer.CheckForNewRepositories()

 
 
Request information: 
    Request URL: https://localhost:443/bonobo.git.server/Home/Error?aspxerrorpath=/Bonobo.Git.Server 
    Request path: /bonobo.git.server/Home/Error 
    User host address: ::1 
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: 'DOMAIN\USERNAME'
 
Thread information: 
    Thread ID: 5 
    Thread account name: 'DOMAIN\USERNAME'
    Is impersonating: False 
    Stack trace:    at System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app)
   at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
   at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
   at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
   at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)
 
 
Custom event details: 

-----

I removed the username from the above event log data.

TROUBLESHOOTING:
---------------------------

- I did change the app. pool to an AD user that has 'read' rights on the OU that contains the groups used to define access and team membership.
- by viewing the SQLite db with SQLite browser I can't see that the usernames contains '\' (this has been mentioned in other forum/issues posts as a culprit.
- IIS has been restarted
- everything else than App_Data was removed when I installed Bonobo Git server
- tried the 'Network Service' acc. on the App. pool - made no diff.
- IIS_Users still have 'Modify' rights on the App_data folder
- tried adding the app. pool user (the AD user I want to use for this) to the ACL of the App_data folder - no diff.
- Initially, before changing to 'AD Member service' I get a login page.
- Looking in the web.config folder I saw that the ADBackend folder in the line "     <add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" /> " does not exist. Therefore I tried creating that. Made no diff. So this is properly handled by the code. Anyways, worth the try.
- Made sure that the memberOf token included the AD groups used to give access to the Bonobo Git server website.....they where there.

I hope someone can point me in the direction of a solution. Looking forward to hear from you.

Thank you very much.
Regards larssb

**Comment by larshg** [comment]
In your config on line 26 (perhaps :) ) - I have this entry - what is yours? 
```<add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" />```

**Comment by larssb** [comment]
Hi @larshg,

I got exactly the same thing.     

' <add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" /> '

- But is it correctly understood that no actual folder named 'ADBackend' is necessary under App_Data?

Thank you

**Comment by larshg** [comment]
It should create an actual folder yes - and inside the ADBackend folder there is User, Repositories, Teams and Roles - and inside these, there should be some json files.

**Comment by larssb** [comment]
Aha okay - the folder is not created and therefore there is no data beneath
it either. What to do - is there any logs or the like that could help us
troubleshoot this?

/Larsen

- Health is wealth, movement is medicine -

On 27. jan. 2016, at 22.57, Lars <notifications@github.com> wrote:

It should create an actual folder yes - and inside the ADBackend folder
there is User, Repositories, Teams and Roles - and inside these, there
should be some json files.

—
Reply to this email directly or view it on GitHub
<https://github.com/jakubgarfield/Bonobo-Git-Server/issues/433#issuecomment-175879542>
.

**Comment by RedX2501** [comment]
Please try https://github.com/jakubgarfield/Bonobo-Git-Server/issues/432#issuecomment-175023026

**Comment by larssb** [comment]
Hi @RedX2501 The rights are correct. Just controlled it again. Made sure to follow the installation instructions. Also, I was already using v4 before so the rights was already there. Made sure to follow the migration steps.

Looking at the error I already have posted, to me it seems like, when Bonobo Git Server is set to use the 'AD member service' it cannot create the ADBackend folder and the items required inside it. 
Here:
--
Value cannot be null.
Parameter name: virtualPath
   at System.Web.VirtualPath.Create(String virtualPath, VirtualPathOptions options)
   at Bonobo.Git.Server.Data.ADBackend.<>c.<.ctor>b__18_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Bonobo.Git.Server.Data.ADRepositoryRepository.GetRepository(String name)
   at Bonobo.Git.Server.Data.Update.RepositorySynchronizer.CheckForNewRepositories()
--

Thank you.

**Comment by larssb** [comment]
I have now also tried building it by downloading master and doing a publish from Visual Studio. The error is exactly the same.

**Comment by larshg** [comment]
Are you sure that you have write permissions to the folder - maybe it can't create the folders and therefore crash as the virtual path is null.

You can try create the folders manually?

If not - you properly have to try remote debugging on the IIS directly. Publish a debug version on the server and in VS attach a debug to a process where you enter the servername - you have to have admin rights on the server though, I think.

**Comment by larshg** [comment]
Hm.. Maybe it doesn't get that far to even try creating the folders... So creating them manually is properly not helping :(

**Comment by larshg** [comment]
Can you perhaps disable custom error page and provide are more full debug stack trace... I tried manually to set the backendpath to null and I got a similar error as you, but more detailed in the browser...

**Comment by larssb** [comment]
Hi @larshg,

I just checked again, the IIS_IUSRS group have [MODIFY] permissions. Manually creating the ADBackend dir. does not help. Hmm I'll do the remote debug if it is essential, as I have never tried that before :-).

This is the error after having disabled the custom error page.
---

Server Error in '/Bonobo.Git.Server' Application.

Value cannot be null.
Parameter name: virtualPath 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.ArgumentNullException: Value cannot be null.
Parameter name: virtualPath

Source Error: 


 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 



[ArgumentNullException: Value cannot be null.
Parameter name: virtualPath]
   System.Web.VirtualPath.Create(String virtualPath, VirtualPathOptions options) +12538514
   Bonobo.Git.Server.Data.ADBackend.<.ctor>b__1() +113
   System.Lazy`1.CreateValue() +14337348
   System.Lazy`1.LazyInitValue() +524
   Bonobo.Git.Server.Data.ADRepositoryRepository.GetRepository(String name) +32
   Bonobo.Git.Server.Data.Update.RepositorySynchronizer.CheckForNewRepositories() +157

[HttpException (0x80004005): Value cannot be null.
Parameter name: virtualPath]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +12601933
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +175
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +304
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +404
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +475

[HttpException (0x80004005): Value cannot be null.
Parameter name: virtualPath]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +12618980
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +12458597

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34274  
---

To me it seems like it is pretty much the same error as the one I've found in the eventlog on the Windows server.

Thank you.

**Comment by latop2604** [comment]
Can you check the ActiveDirectoryBackendPath value in your web.config (in AppSettings block) ?

**Comment by larssb** [comment]
Hmmm yes I did that. Larshg already asked me that and I have also mentioned
it before in this issue.....however, it is ~\App_Data\ADBackend

/Larsen

- Health is wealth, movement is medicine -

On 28. jan. 2016, at 23.41, Rémy de Sérésin <notifications@github.com>
wrote:

Can you check the ActiveDirectoryBackendPath value in your web.config (in
AppSettings block) ?

—
Reply to this email directly or view it on GitHub
<https://github.com/jakubgarfield/Bonobo-Git-Server/issues/433#issuecomment-176460234>
.

**Comment by latop2604** [comment]
Arf sorry. My bad

**Comment by larssb** [comment]
It's okay :-)

/Larsen

- Health is wealth, movement is medicine -

On 30. jan. 2016, at 00.52, Rémy de Sérésin <notifications@github.com>
wrote:

Arf sorry. My bad

—
Reply to this email directly or view it on GitHub
<https://github.com/jakubgarfield/Bonobo-Git-Server/issues/433#issuecomment-177022779>
.

**Comment by larssb** [comment]
Anyone with an idea on what could be the culprit in this case? Kind of anxious to get going with the new features and especially the AD integration. Yeah in general get back to a working Bonobo Git install (without rolling back is preferred ;-).

**Comment by RedX2501** [comment]
@larssb I did have a similar problem once, where the fields in in Repository were missing while discovering existing repos. The problem was here https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/Data/Update/RepositorySynchronizer.cs#L37 maye adding users, teams and admins might help.

**Comment by larssb** [comment]
Hi @RedX2501 - Thank you for responding :-) - and I would have to do that through sqlite? Or is there some other way?

**Comment by larssb** [comment]
@RedX2501 

Went through the SQLite db with SQLiteBrowser and found a couple of teams and such that did not have values in some fields. The entries where either deleted or updated with valid data. Still the exact same error.

Any ideas?

**Comment by RedX2501** [comment]
You have to add them in the code.

The location that i posted.

```
teams = new string[0];
```
and so for users and admins.

**Comment by larssb** [comment]
Hi @RedX2501 - still get the same error. 

For good measure the error is
========================

Server Error in '/Bonobo.Git.Server' Application.

Value cannot be null.
Parameter name: virtualPath 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.ArgumentNullException: Value cannot be null.
Parameter name: virtualPath

Source Error: 


 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 



[ArgumentNullException: Value cannot be null.
Parameter name: virtualPath]
   System.Web.VirtualPath.Create(String virtualPath, VirtualPathOptions options) +12538514
   Bonobo.Git.Server.Data.ADBackend.<.ctor>b__1() +113
   System.Lazy`1.CreateValue() +14337348
   System.Lazy`1.LazyInitValue() +524
   Bonobo.Git.Server.Data.ADRepositoryRepository.GetRepository(String name) +32
   Bonobo.Git.Server.Data.Update.RepositorySynchronizer.CheckForNewRepositories() +157

[HttpException (0x80004005): Value cannot be null.
Parameter name: virtualPath]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +12601933
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +175
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +304
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +404
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +475

[HttpException (0x80004005): Value cannot be null.
Parameter name: virtualPath]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +12618980
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +12458597

  


Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34274  

====================

Dang! :-(

**Comment by larssb** [comment]
@RedX2501 - it seems to have something to do with the repos. I moved them out of App_Data\Repositories. After that Bonobo seems to be starting and prompts for a user to login with. However, I cannot login. I have added the user to the Bonobo git admin AD group and the app. pool user has read rights to the OU where the group is located....

This is my web.config file, the AD service part.

  

-----

Thank you.

**Comment by latop2604** [comment]
You need to uncomment these tags. (remove ).
This is why the value is null at runtime

**Comment by larssb** [comment]
Hi @latop2604 

Sorry for the confusion. There is two lines in the web.config file regarding the MembershipService. Default it is set to Internal as far as I remember. Just changed that line instead of removing the comment from the other line. In short.....the line is without 

But thank you for replying.

**Comment by larssb** [comment]
Hmmm anyone else with an idea?

**Comment by willdean** [comment]
@larssb The only way I can repro this is to comment out the `<add key="ActiveDirectoryBackendPath"...>` line in web.config. 

It would be good if you could post the actual appSettings part of webconfig that you're using at the time of the crash, because the earlier comments on this leave room for doubt, and the symptoms are exactly that of having the line `<add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" />` commented-out.

Anyway, I've added some diagnostics to a branch on my fork - feel free to checkout https://github.com/willdean/Bonobo-Git-Server/tree/Bug433 and see if you get a line which looks a bit like this written into the error log:

> iisexpress.exe Error: 0 : CONFIGURATION ERROR: The 'ActiveDirectoryBackendPath' element in web.config appSettings does not appear to be set

**Comment by larssb** [comment]
Ooooooh noooooo. I have a confession. Yesterday when I troubleshooted this I saw that I needed to remove the commenting from the appSettings part correctly. I had not done that. I can't say sorry enough for wasting your precious time. 

Other comments:
- I would recommend that the documentation mentions that the AppPool should also have 'Read' rights to the 'Users' and 'Computers' system AD containers. This also gave me some grey hair during troubleshooting. 

Thank you so much for your time....! Highly appreciated and I pretty embarrassed right now :-D

**Comment by willdean** [comment]
@larssb Don't worry, I think it just points to the value of building in some configuration validation.  Lots of bits are harder to troubleshoot than they could be.

**Comment by larssb** [comment]
Hey Will,

Thank you. Yes agree some bits are a bit hard to troubleshoot.

/Larsen

- Health is wealth, movement is medicine -

On 16. feb. 2016, at 10.58, Will Dean <notifications@github.com> wrote:

@larssb <https://github.com/larssb> Don't worry, I think it just points to
the value of building in some configuration validation. Lots of bits are
harder to troubleshoot than they could be.

—
Reply to this email directly or view it on GitHub
<https://github.com/jakubgarfield/Bonobo-Git-Server/issues/433#issuecomment-184604512>
.

**Comment by buvatu** [comment]
Hi @larssb 
It seems you already resolve this issue.
Currently I'm facing this issue too.
I tried to configure the IIS and Bonobo many times carefully.
But the Bonobo did not start after all.

Here is my system:
Windows 7 - IIS 7.5 (Default)
Bonobo version 6.1.0
.NET framework 4.5.2 (I think it's OK)

Prerequisites
Install IIS - OK
Install ASP.NET MVC 4 - OK
Register MVC framework with IIS - OK

Installation
Set permission for IIS_IUSRS - OK
Convert Bonobo.Git.Server to Application in IIS - OK
Configure Authentication - OK

Here is the result when I start Bonobo
http://localhost/bonobo.git.server/Home/Error?aspxerrorpath=/bonobo.git.server/Home/Error

Could you please show me how to fix this issue
Many thanks

**Comment by willdean** [comment]
@buvatu This issue was about a problem with 'Active Directory' - before you try to do that you should make sure Bonobo works with its default configuration.

**Comment by larshg** [comment]
You need to upgrade to .net 4.6 at least !

**Comment by buvatu** [comment]
Thank you so much @larshg 
I follow the instruction of main page and it did not work at all.
After upgrade my .NET 4.6, everything works like a charm.
Thanks again.
