### ISSUE TITLE
Activity Stream

### ISSUE THREAD

**Issue by rabin111** [jakubgarfield/Bonobo-Git-Server#436]
Hello,

This thread is about feature request.

Activity Stream when someone pull/push a code into repository would be great.

Thanks!

**Comment by RedX2501** [comment]
What exactly are activity streams?

**Comment by rabin111** [comment]
They are a activity that occurred in all repos such as someone push some codes into the repo like in GitLab.

https://about.gitlab.com/images/feature_page/activity_stream_full.png

**Comment by willdean** [comment]
@rabin111 In Bonobo, which doesn't have issue tracking or pull-requests, would you see anything in this list other than commits?

**Comment by RedX2501** [comment]
Same as #304
