### ISSUE TITLE
General URL to Repository not working

### ISSUE THREAD

**Issue by DanDrag** [jakubgarfield/Bonobo-Git-Server#437]
Hello,

I have a fresh installation of Bonobo GIT Server and the problem that I get is that after I create a new repository and then I go to details, I am presented with the general URL for it (screen shit attached), this link doesn't seem to be working. When I try to access it, I get the generic error: 

404 Page Not Found
The page you were looking for wasn't found. Please try again or contact the system administrator.

What am I missing here ?

Thanks in advance,
Dan
![git](https://cloud.githubusercontent.com/assets/17047518/12785304/86d5a968-ca94-11e5-979a-02fc278cb715.JPG)

**Comment by RedX2501** [comment]
That link is not for clicking but to be used with your git command line tool.

**Comment by ecocquerez** [comment]
Have the same problem. 
I'm using AD autentication. I've created new repository (I belong to administrator group) and then I try to push my local repository to bonobo 
![errorbonobo](https://cloud.githubusercontent.com/assets/3832431/12886107/668d07a2-ce6b-11e5-9ddc-ec746345d12f.PNG)

All previous repository can be accessed via TortoiseGit or Git Extension

**Comment by willdean** [comment]
@ecocquerez Yours is not the same problem @DanDrag who opened this bug is having. 

You have typed/pasted your URL into GitExtensions with a space character after it, which is causing a 400 error.

**Comment by mlarizzate** [comment]
Hi Guys!
I'm having a problem like these.

I have a created a project in my bonobo server but eclipse cant access to it

![image](https://user-images.githubusercontent.com/1816228/41553724-f6898f76-7308-11e8-8a08-372d4d15bc2f.png)

I took the url from the web admin.

Any Idea?
