### ISSUE TITLE
Repo name case sensitivity is inconsistent

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#443]
We had a problem today which was caused by someone being given a repo name to clone which was the right name but with a casing error in it.

This triggered issued #441 which has now been fixed, but this led me to look into the subject of casing, because even with the fix for #441, you get an **authorisation** error if you mis-case a repo name, not a 'Not found' error, which IMO would point more quickly to the cause.

It seems that Bonobo is 'a bit case-sensitive' on repo names, but not very.

For example `EFRepositoryPermissionService.HasPermission` needs a repo to have the right case, because otherwise it can't find it.   However, `GitController` does something like this:

            var directory = GetDirectoryInfo(project);
            if (Repository.IsValid(directory.FullName))

and this is not case-sensitive - so where this test is performed, it doesn't return a Not Found error, but the auth layer will probably fail you anyway.

My personal feeling is that repo names in URLs should be case-sensitive, if for no other reason than that they are are GitHub, but either way, the whole app should be consistent.  (Update: I'm not actually sure they are case-sensitive at GitHub now - I've read both things now, and perhaps they shouldn't be case-sensitive because Windows isn't, and after all we're only looking at file/directory names really)

I'm happy to produce a PR to fix this in either direction, depending on what people ( @jakubgarfield, @RedX2501  ?)  think is best.

**Comment by RedX2501** [comment]
Imho we should be consistently case sensitive on repo names and case insensitive on username and team names.

**Comment by willdean** [comment]
I'm a bit vague about the management of this project - is there any more opinion/voting needed to decide to do this?

**Comment by larshg** [comment]
What's the advantage of being case sensitive on Repo names? I Would expect RepoName and reponame to refer to the same repository - As the name is the same? Or said differently would anyone add two repositories where the only difference was one to several cased letters? I don't think so?

**Comment by latop2604** [comment]
The underlying repo storage system (windows) is case insensitive. 
Unless you want to support .net core and linux, bonobo should be case insensitive.

**Comment by willdean** [comment]
@larshg Indeed - one could not add two repositories which differed only in case, at least to the filesystem.  (You might be able to add them to Bonobo's database, I haven't checked.

Is there a consensus for case-insensitive emerging?

**Comment by jakubgarfield** [comment]
@willdean there is not really any voting, if some piece of work will help the project it is gonna get merged :)

usually I try to be consistent with github, but @latop2604 provided good reasons for the repo names being case insensitive and the reason to usernames and being insensitive is smoother AD integration @RedX2501?

**Comment by willdean** [comment]
OK, I'll do a PR for case-insensitive repo names, and then we can go from there.
