### ISSUE TITLE
Exceptions in GitController give confusing results at client

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#444]
At present, unhandled exceptions occurring within GitController are handled in the same way as exceptions occurring on any other page.  i.e. They're redirected to an error page.

This can give a confusing response at the client, because the client sees a 200 response with a human-friendly error page, and concludes that it's seeing a bad /info/refs - this leads to the error message:  

>  fatal: http://localhost:3002/repo.git/info/refs not valid: is this a git repository?

This is rarely helpful - ime the problem is not usually anything to do with the repo, it's usually a problem in Bonobo.  This is mentioned in the FAQ.

I have prepared a PR which adds a OnException handler to GitController, and returns a 500 response, with the exception stack trace in the body.   The client then stops with "The requested URL returned error: 500", which isn't much more friendly, but at least it's not actively misleading.

The normal Git client can't display the body information (as far as I know), but at least it's there to see with Wireshark / Fiddler if that's useful.

**Comment by RedX2501** [comment]
Fantastic! I was planning to have a look into this myself.

Thanks.
