### ISSUE TITLE
"General URL" should not be rendered as a link on repo details page

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#449]
The 'Repository Details' view renders the Git URL as an href, which encourages people to click on it.  (See #437) 

It seems to me that this information is provided for cutting and pasting into clients, and doesn't serve any purpose as an href.

Although I think it probably shouldn't 404 when you go to this URL with a browser, the best place for it to go would probably be to the repository details, so it would still be useless as an href on that page, because it would just link back to itself.

Should this just be displayed as text?

**Comment by RedX2501** [comment]
The nice thing about having it as an href is that you can right click and copy target link. But i agree that it can be confusing. Maybe we can check the browser string and redirect to the repo if the git URL is called from the browser.

**Comment by willdean** [comment]
Perhaps we could have it as plain text but with a 'copy to clipboard' button next to it?

**Comment by RedX2501** [comment]
That would be nice.

**Comment by willdean** [comment]
How does the project feel about using additional external libraries, e.g. https://www.npmjs.com/package/clipboard-js ?

**Comment by RedX2501** [comment]
I think it's fine but i don't know anything about licenses and similar
important things.
Am 12.02.2016 11:27 schrieb "Will Dean" <notifications@github.com>:

**Comment by jakubgarfield** [comment]
Copy to clipboard and removal of the link would be nice.Clipboard.js is MIT so no problem with using it if it's a good one.You might also want to have a look at https://github.com/zeroclipboard/zeroclipboard (used by github).

**Comment by padremortius** [comment]
@jakubgarfield @RedX2501  May be rename text before link to "General URL for Git client"?

**Comment by RedX2501** [comment]
@padremortius i think that's to too long. Maybe "Git URL"? Because that URL is clearly not a General URL but just not a personalized one.

**Comment by willdean** [comment]
I was going suggest "Git URL" too

**Comment by willdean** [comment]
I've put in a PR for this because I'd appreciate a review.  I moved the 'copy' buttons from one end of the URL to the other about 6 times, not really able to decide which looked best.  I used a different JS library, but it's still MIT.  Zeroclipboard seems to be flash-based, which rather put me off.
