### ISSUE TITLE
Missing repo directory prevents Bonobo starting

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#451]
At startup, Bonobo searches for repos in the configured "Repository Directory".  If this folder is missing, then there's an exception during startup which prevents the server starting at all.   This makes it difficult to recover from that situation.

**Comment by RedX2501** [comment]
What happens if the user wants to create a repo? Will it fail? Do we need to display a warning about the missing directory?

**Comment by willdean** [comment]
@RedX2501 Yes, everything is borked if this is wrong, you probably get errors all over the place. All that my patch does is at least let you get to the settings page and correct it.  The settings page does validate the directory field - so to see this problem you do have to have been messing around with the file-system.

If we had some general way of notifying system problems to the user (e.g. banner at top / bottom of page), there are various configuration issues we could possibly detect and notify.
