### ISSUE TITLE
Trouble installing Bonobo on Plesk or Wild West / GoDaddy Virtual Server

### ISSUE THREAD

**Issue by WisconsinWildcat** [jakubgarfield/Bonobo-Git-Server#456]
I've been fighting this for days now, and I've tried many different configurations.  I've followed the prerequisites (afaik) and I just can't get it to roll. It spins and spins in the web browser without resolving.

I did get it close, once. The problem is that http://<ip address>/Bonobo... doesn't work due to some weird way they have the IIS configured, and I'll dig into that more now. 

I was able to get close by putting it in the default server location and then binding the default to a subdomain, but then I ran into some error about line length and could not push the repo.  I've since found a fix for the line length and I'm trying to get back to that stage.

I do have Bonobo set up on a different server for a different company, and that went easily, so I've done this before. That one -- I have problems running a post-update script which I solved with a recurring windows tasks for now - is running fine.

Any suggestions on Plesk, Wild West/Go-Daddy, etc are much welcomed!

Windows 2008 R2 Standard 64 bit 4GB RAM

**Comment by WisconsinWildcat** [comment]
Presently cannot get around this error, although I have just about everything enabled:

HTTP Error 403.14 - Forbidden
The Web server is configured to not list the contents of this directory.

**Comment by willdean** [comment]
Do you know what folder it was trying to list?  Does this happen before any part of the site is available?  Where are you intending to set the Git repo directory to be?

**Comment by WisconsinWildcat** [comment]
willdean, I'm still trying to just get this install working, so it's localhost/Bonobo.Git.Server.  I've applied the permissions, tried various application pools, compared it to the other successful installation I did on another server - nothing.

**Comment by WisconsinWildcat** [comment]
What???  Just worked. I recently switched from an App Pool pointing to .net framework v4.0.30319 to the same framework version but named ASP.NET v4.0.   Is Bonobo somehow sensitive to that??

**Comment by willdean** [comment]
Did you change to a different app-pool, or did you change the framework on the same app-pool?

**Comment by WisconsinWildcat** [comment]
Changed to a different app pool but running the same framework.

**Comment by willdean** [comment]
Sorry, I'm not following - it was a different app pool with a different name for the framework, but the same framework?  Is that right?   Does it break again if you go back to the previous pool.

Doesn't really sound like a Bonobo thing TBH, more IIS/.NET app pool madness.

**Comment by WisconsinWildcat** [comment]
Your last statement was the most correct. App Pool madness!
![apppool_didnotwork](https://cloud.githubusercontent.com/assets/7716691/13056417/ce8ed096-d3da-11e5-94c7-d58db9cd0a18.png)
![apppool_didnotworkeither](https://cloud.githubusercontent.com/assets/7716691/13056418/ce949bf2-d3da-11e5-860b-b980b12fd5c7.png)
![apppool_worked](https://cloud.githubusercontent.com/assets/7716691/13056419/ce952b8a-d3da-11e5-8b3a-b7efbfaaaa80.png)

**Comment by WisconsinWildcat** [comment]
Advanced Settings - there were a couple differences...
![app_pool_asp_net_adv_settings](https://cloud.githubusercontent.com/assets/7716691/13056561/b70fe7ec-d3db-11e5-8c00-5b76cb4f434f.png)
![app_pool_default_net_4_advanced_settings](https://cloud.githubusercontent.com/assets/7716691/13056560/b70fe29c-d3db-11e5-8782-154709363ded.png)
![app_pool_net_4_classic_adv_settings](https://cloud.githubusercontent.com/assets/7716691/13056562/b71338f2-d3db-11e5-98e7-114512ee3c05.png)

**Comment by willdean** [comment]
You'll never want 'classic' pipeline for anything modern.  Glad it's sorted anyway - hopefully this will be helpful to people who come later.

**Comment by WisconsinWildcat** [comment]
Agreed about the "hope it helps others". Thank you for your assistance.

**Comment by SeriousITGuy** [comment]
I just recently hit the same problem and what solved the issue for me was running:
%windir%\Microsoft.NET\Framework\v4.0.30319\aspnet_regiis.exe -ir

which generate two new app pools: asp.net v4.0 and asp.net v4.0 classic. After switching the bonobo application to the new asp.net v4.0 app pool everything worked.
