### ISSUE TITLE
MVC version

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#457]
What version of MVC is Bonobo supposed to be using?

I think it was upgraded from MVC 4 -> MVC 5 at d6eea1b , but there are parts of views\web.config (i.e. NOT the root web.config, the view one) which weren't updated.   This causes a bazillion intellisense errors in VS when working on views, which go away when the changes to views\web.config are made.

I'm happy to fix this, but if there's some confusion about what MVC version we're using, I don't want to add to it...

**Comment by RedX2501** [comment]
I thought we were using version 5 but at the very bottom of the config file it seems that some references to mvc 4 still exist. So I'm a bit confused now.

Imho we should fix the inconsistencies and go for 5.

@jakubgarfield how do you feel about this?

**Comment by jakubgarfield** [comment]
Agree, let's update the whole project to 5.

**Comment by willdean** [comment]
@RedX2501 - are you talking about the web.config in views?  If so, I'm sorting it.  If not, could you point me to where you're seeing MVC4 stuff?

**Comment by RedX2501** [comment]
Sorry if I'm misreading but i found it here:
https://github.com/jakubgarfield/Bonobo-Git-Server/commit/d6eea1b2d2888b23a3077f9ffce9b84a2a86b63d#diff-6e0343f21ec6bdbcecc94b95d5aa0ae8R222

**Comment by willdean** [comment]
If you're looking at a line that says "Unity.MVC4", then that changed at 082d357

**Comment by RedX2501** [comment]
Hmm there i found this line:
https://github.com/jakubgarfield/Bonobo-Git-Server/commit/082d357b801495c5e726e0c0ec7275844d16ada5#diff-6e0343f21ec6bdbcecc94b95d5aa0ae8R135

**Comment by willdean** [comment]
That's saying the package "Unity.Mvc" is at version 4 - i.e. it's the version of "Unity.Mvc", not the version of Mvc.

My (very limited) understanding is that "Unity.Mvc" is generic to all versions of MVC, whereas "Unity.Mvc4" was specific to Mvc4.

Unity is a dependency injector, it's working with MVC, it's not a part of it.

**Comment by RedX2501** [comment]
A quick googling revealed that there is a version 5 of the unity framework. Unity 4 has a dependency on mvc 4 and above whereas unity 5 has mvc 5 and above. So not sure if should update unity too.

**Comment by willdean** [comment]
Did you find any explanation for the difference between Unity.Mvc, Unity.Mvc4 and Unity.Mvc5?

**Comment by RedX2501** [comment]
After some digging:
Unity mvc 4 uses unity 3.5
Unity mvc 5 uses unity 4.0

There seems to be no summary of the changes between 3.5 and 4.0 according to this issue on unitys githubhttps://github.com/unitycontainer/unity/issues/20

**Comment by willdean** [comment]
Lol.  And I thought the MVC6 + ASP.NET5 stuff was enough to make me cry.  Well, we're using Unity 4 so I guess we're OK.
