### ISSUE TITLE
.vs directory

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#458]
Can I remove the .vs directory from the Bonobo source, please?

I know it spent about an hour in .gitignore last year, but it's definitely Microsoft's intention that it's not in version control.  The application.config file is particularly unhelpful, as it ends up full of of local paths for running IISExpress - I don't need paths on other people's machines, and they don't need mine.

**Comment by RedX2501** [comment]
Yep, pretty sure it can go.

**Comment by jakubgarfield** [comment]
:+1:
