### ISSUE TITLE
AD authentication not working for Administrator access

### ISSUE THREAD

**Issue by SGatOCCU** [jakubgarfield/Bonobo-Git-Server#459]
Hello All,

I'm having an issue getting an administrative login via Active Directory.  I am able to successfully login using AD, just not as an administrative user.

Unexpected behavior:
- When attempting to login as an administrative user I can login, but receive the error "Unauthorized
You don't have permission for the selected action or page."

Troubleshooting:
- The machine is connected to AD.  I can successfully login with an AD user as a regular user.
- Nested groups are not being used.
- Case sensitivity is not the issue - I've tried case correct and lower case.
- Local admin will not work when AD authentication is used.  This is to be expected I suppose, but limits workarounds.

Here is the user authentication block from the web.config file:
```
  <add key="UserConfiguration" value="~\App_Data\config.xml" />
    <add key="DefaultRepositoriesDirectory" value="~\App_Data\Repositories" />
    <add key="GitPath" value="~\App_Data\Git\git.exe" />
    <add key="GitHomePath" value="~\App_Data" />
    <add key="RecoveryDataPath" value="~\App_Data\Recovery" />
    <add key="AuthenticationProvider" value="Cookies" />
    <!--<add key="AuthenticationProvider" value="Windows" />-->
    <!--<add key="AuthenticationProvider" value="Federation" />-->

    <!--<add key="MembershipService" value="Internal" />-->

    <add key="MembershipService" value="ActiveDirectory" />
    <add key="ActiveDirectoryDefaultDomain" value="ulaneocu.org" />
    <add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" />
    <add key="ActiveDirectoryMemberGroupName" value="Git1101Gitall" />
    <add key="ActiveDirectoryRoleMapping" value="Administrator=Git1101Admin" />
    <!--<add key="ActiveDirectoryTeamMapping" value="Developers=GitTeam" />-->

```
Thanks in advance for your assistance and time,
Sean

**Comment by willdean** [comment]
I may well reveal my almost complete ignorance about AD here, but does your user show any roles if you go to the users page?  Seems to me you'd be unlikely to fail any auth tests if you correctly have the role 'Administrator'

**Comment by SGatOCCU** [comment]
Hi Will.  Thanks for the reply.

I don't have access to the user pages after my ?login? with administrative user.  I'm only able to see the Bonobo Git Server button in the top left corner and the Sign In link in the top right along with the  error "Unauthorized You don't have permission for the selected action or page."

I know what you're talking about though, when my regular user logs in I can see "Repositories, "$AD_Long_Name", and Sign Out in the top right.

**Comment by willdean** [comment]
If you change the ActiveDirectoryRoleMapping value so that it doesn't match you, does your account then work as a normal non-admin account?

**Comment by SGatOCCU** [comment]
I've removed my AD admin user ("AUser) from the "Git1101Admin" AD group (admin group).  I then add "AUser" to the "Git1101Admin" AD group (regular user group).  The "AUser" account can now log in, as a regular user.

If I leave the above setup in place and add "AUser" to the "Git1101Admin" AD group (user is now in regular user and admin groups) I can login, but receive the menus of a regular user; no admin menu in the top right.

It seems the problem is narrowed down to the administrative group in Bonobo not granting administrative rights to the service.  Everything else seems to be working; it's really odd.

**Comment by willdean** [comment]
Unfortunately there are a number of places in the AD code which might be silently swallowing exceptions without a trace.  If I sent you a set of binaries which recorded better logging, would you be able to try them?    (Or do you have VS and could build your own - I can create a branch for you to try)

**Comment by SGatOCCU** [comment]
I'm happy to run a binary that produces verbose logging.  I can clone the existing virtual machine and run it there.

I'm not sure what a VS is, sorry.

Thanks for the help with this.

**Comment by willdean** [comment]
The attached file should be put into the bonobo.git.server\bin directory. TAKE A BACKUP FIRST!

If it works, then you might get useful into written into app_data\bonobo.git.server.errors.log.  Probably worth you clearing that file out before you start.

(VS is 'Visual Studio' which is the Microsoft product which you'd use to build your own copy of Bonobo)

[Bonobo.Git.Server.dll.zip](https://github.com/jakubgarfield/Bonobo-Git-Server/files/131626/Bonobo.Git.Server.dll.zip)

**Comment by SGatOCCU** [comment]
New binary writes out the error below to the Bonobo.Git.Server.Errors file when attempting Admin login via AD group.  No error is written when in log (successfully - with expected behavior) in using non-administrative group.

`Native library pre-loader is trying to load native SQLite library "C:\inetpub\wwwroot\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll"...`

**Comment by willdean** [comment]
@SGatOCCU - That's not relevant I'm afraid, it's just noise while the app is starting up, it's not an error per se, and it's not connected with the AD stuff.

Clearly whatever's going wrong is not recorded by those additional checks I added.

I have in mind some kind of 'configuration verifier' which could check for various problems with the Bonobo setup and might help narrow-down your problem, but it isn't written yet, and I don't have a AD server here to test against at the moment anyway.

In another thread about an AD problem (which just turned out to be a config error), someone said the following:

> I would recommend that the documentation mentions that the AppPool should also have 'Read' rights to the 'Users' and 'Computers' system AD containers. This also gave me some grey hair during troubleshooting.

I don't even really know what it means, but it just might point you to something helpful.

**Comment by willdean** [comment]
@SGatOCCU  Here's another version of the DLL to try.  This has a new diagnostics page, which you get to by going to http://<my server>/Home/Diagnostics

I am flying blind with AD, but I have tried to dump some useful info into that page - see what you get.

[Bonobo.Git.Server.dll.zip](https://github.com/jakubgarfield/Bonobo-Git-Server/files/133279/Bonobo.Git.Server.dll.zip)

**Comment by willdean** [comment]
Just noticed another place in the AD code which might be silently swallowing an exception - please try the attached and see if it logs anything.

[Bonobo.Git.Server.dll.zip](https://github.com/jakubgarfield/Bonobo-Git-Server/files/134178/Bonobo.Git.Server.dll.zip)

**Comment by RedX2501** [comment]
@willdean Do you think it could help the project if we removed all the try catch blocks that catch all excepitons for AD?

**Comment by willdean** [comment]
Yes!  I am reluctant to make myself unpopular by dissing other people's hard work within a week of looking at the project, but I do think they're a problem.

I think there are generally too many catch() blocks (and possibly too many if(foo != null) { xxx } blocks.)   I'm not singling out the AD code for this.

I know it's a tricky balance, because an exception which stops the server even starting is a bad experience too, but less tolerance of exception-catching and less tolerance of nulls being pushed around everywhere might make it a lot easier to find/fix all the weird config/environment problems people come along with.

I am tempted to open an issue for general discussion of code-quality (perhaps think about having the Appveyor+Resharper stuff do some enforcement, or look at StyleCop perhaps), but there would have to be some serious buy-in from more senior people if there was to be a big push on this.

**Comment by RedX2501** [comment]
@willdean I'm in favour of this. I'd just open a PR with an [RFC] tag. Let's giive it a go.

**Comment by SGatOCCU** [comment]
@willdean This is a response to the "AppPool having read rights to users and computers" I found a document on how IIS is managed differently in 2008R2/Win7 onward:
http://www.iis.net/learn/manage/configuring-security/application-pool-identities

I then changed the following value in IIS.  Unfortunately, this had no effect.  I did not make changes in Active Directory yet though.  I want to make one more change before I go there.
IIS Manager > Application Pools > IIS DefaultAppPool > Advanced Settings > generate process model event > Load User Profile > *TRUE* (from false).

I have another idea I'll investigate as well. Maybe it's local file permissions that need the AppPool rights?  We'll see.

**Comment by willdean** [comment]
@SGatOCCU Can you look back a couple of comments and find the new version of the DLL which I attached, with some instructions about a new diagnostic page (the url should be `http://<your server>/Home/Diagnostics` - it got munged in the last comment.

I would be interested in the output of that page.

**Comment by SGatOCCU** [comment]
@willdean 

0) Installed the new binary.

1) 
[BonoboDiagPageSanitized.txt](https://github.com/jakubgarfield/Bonobo-Git-Server/files/135409/BonoboDiagPageSanitized.txt)

2) I now receive the below from Bonobo.Git.Server.Errors file.  I'm not sure if that's helpful.

```
Native library pre-loader is trying to load native SQLite library "C:\inetpub\wwwroot\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll"...
About to run  on Closed
Post run count 1
About to run  on Closed
Post run count 1
```

Thanks for your help with this!

**Comment by willdean** [comment]
I don't feel I'm being any help!  What did the 'sanitization' consist of - removing the AD user-name list?

**Comment by larshg** [comment]
Just to verify you try to use cookie auth, with AD membership/role provider?

**Comment by larshg** [comment]
Are there any json files in the app_data/ADBackend subfolders?

I just tried with cookie auth and a AD backend with the experimental branch that @RedX2501  and I are working on - and it seems to work fine.

I'll try the master branch also - just to verify that it is also working.

**Comment by larshg** [comment]
I can verify that it also works on master here. Are there any json file in the app_data/ADBackend/Roles ?

**Comment by SGatOCCU** [comment]
@willdean Yep, I just removed all the groups users.  They were presented in a case sensitive CSV format.  All accounts were reflected correctly, so it's able to read from AD.

@larshg Cookies are enabled in the web.config.
` <add key="AuthenticationProvider" value="Cookies" />`

I'll attach the whole config file here with only the AD domain name sanitized.
[Santitzed_web.config.xml.zip](https://github.com/jakubgarfield/Bonobo-Git-Server/files/137147/Santitzed_web.config.xml.zip)

Thanks,
Sean
