### ISSUE TITLE
Upload a changed file to an available repository

### ISSUE THREAD

**Issue by hadzira** [jakubgarfield/Bonobo-Git-Server#461]
How can I upload a new file to an available repository in Bonobo Git?

**Comment by RedX2501** [comment]
You need to have a cloned version of the repository that contains the file you changed.

Then you just do the usual add commit push cycle of git.

**Comment by hadzira** [comment]
how do I clone the version and add, comm and push them?

**Comment by willdean** [comment]
It's going to be beyond the capabilities of the Bonobo team to help with real begineer Git stuff, I'm afraid.

A great place to start with Git is this free book:  https://git-scm.com/book/en/v2
