### ISSUE TITLE
Change password salting

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#462]
This is with reference to PR #426 

Currently, password hashes using the username as a salt.  This was probably never a very good idea, in that every site has a user called 'admin', so an attacker could precompute hashes which would be useful on all bonobo sites.  But it didn't give any functional problems.

After #426, people will be able to change usernames, which is a great feature, but would invalidate their password, because the hash will need to change.

I propose the following, as part of the #426 work:

* We add another string column to the user table, called "PasswordSalt"
* During the #426 upgrade, we copy the existing username of users into the PasswordSalt field
* When validating a user's password, we use the PasswordSalt field for the salt, not their current username (which might have changed some time after the migration occurred)
* Every time we save/update a password, we generate a random string for PasswordSalt (a guid string is fine) and save that along with the hash

To my mind, this solution has the following benefits

* We don't have to touch the hashing code at all - that still takes a string salt
* We're doing a big code-based migration anyway, so copying the data into a new column is trivial at this point
* We won't have to mess with the UI to insist that people reset their password if they change their username
* In time, we will migrate away from having predictable salting in the database

Any thoughts, anyone?

**Comment by RedX2501** [comment]
1. I'm in favour of not touching the current password code.
2. I'm also in favour of adding this extra column as I guess it is the only way of not invalidating the password on username change due to 1..
3. Predictable salts are not a concern (repeating salts on the other hand is), after all they are readable in the database and to get the password hash you need read access to the DB.

Can you provide a PR to my repo with the changes? Best to the user_id branch.

**Comment by willdean** [comment]
Will do.  I'll can also merge in my new test stuff with it, but that would mean that I'll have to back-out the changes in 74d0556 which we've been talking about.

I think it's worth adding the test, because the coverage on EFMembershipService, (which I thought was a bit soft and didn't really add much value) found a couple of regressions in this branch straight away.

**Comment by willdean** [comment]
OK, I've done this, and it's in willdean:user_id, along with all the new test stuff.  For some reason, @RedX2501 's  clone is not showing up in my "base fork" pull down, so I can't currently create a PR.  I'm going to ask GH about this.

**Comment by jakubgarfield** [comment]
I think this is a change in a good direction, especially that we are doing bigger architectural changes around usernames in different PR.

I stumbled upon an article this morning that touches this at https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016. And also a bit info on stackoverflow http://security.stackexchange.com/questions/17421/how-to-store-salt - mostly in accordance with what you are proposing.

**Comment by willdean** [comment]
I think what we've done is an improvement, and like you say it's a good time to do it.

If we wanted to improve one the current plain SHA512, there's now a hasher in provided in ASP.NET Identity which gives you a proper combined salt+hash output: 

http://stackoverflow.com/questions/19957176/asp-net-identity-password-hashing?rq=1

All the details of hashing/salting go away, and you just get a string in/out.

I would suggest that we move to this eventually, then we can drop the password salt column again, and use the same approach that was used for the MD5 -> SHA512 transition to translate the hashes from the old to the new format.

But I don't think there's much appetite for changing the password hashing now as part of the GUID-ID work, so I'd suggest we defer this for now unless you think it's really worthwhile to combine it.
