### ISSUE TITLE
Help with testing AD code

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#463]
I've recently been writing a load of test code, initially for the EFMembershipService.  This uses an in-memory sqlite database, and now has pretty much 100% coverage on that service.  

I have now split my tests into general IMembershipService stuff, and EF-specific stuff.  

This has allowed me to create a test class for ADMembershipService, which would allow us to run the same tests against both providers, which could be great for finding subtle differences.

However, I've now come to the point where I'd need an AD server to work against.  What are the people who work on the AD code doing in this regard?   I installed AD LDS on a server here, but I'm not sure it's doing anything, nor how to configure it, nor if it's even what I need.

Clearly an AD test is never going to run in appveyor, but it could still be a useful thing to run interactively.

Any suggestions about a simple testing approach would be appreciated.

**Comment by RedX2501** [comment]
Does this help you? http://brockallen.com/2013/10/22/announcing-thinktecture-embeddedsts-a-simple-local-sts-for-asp-net-applications/

**Comment by willdean** [comment]
It might, if only I knew what it was!  Interesting anyway.

**Comment by RedX2501** [comment]
And i had posted this before: http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/

**Comment by willdean** [comment]
I've seen that one - I'll explore it properly.
