### ISSUE TITLE
Resharper?

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#465]
How would people feel about me committing project-based Resharper settings to the repo which match the project's coding-style as much as possible?

I'm not sure how many people working on the project have Resharper (not many, I suspect from some of the warnings I see!), but for those that do have it it would be a good way to semi-automatically help with code style consistency.

Separately it could also automatically enforce some good practices at build-time.  I think JetBrains will give away licences to active open-source devs too, though I've never been down that route myself.

If I did commit the settings, it would only be two or three extra small text files in the repo, so it's not going to be a big deal to those who don't use it.

**Comment by RedX2501** [comment]
Unless all devs use Resharper I'm against code style changes even if those would be considered better practice. That would only lead to an inconsistent look.

But if someone has Resharper and is willing to fix the warnings that are not code style relevant I'm ok with it.

**Comment by willdean** [comment]
Sorry, I've been unclear about this - I'm _not_ proposing changing the code style to match Resharper's, I'm proposing adding a Resharper configuration file to make it match the project's _existing_ style for everybody who does work on it.

For example, Bonobo uses explicit 'private' modifiers on private members - I have no problem with this, but it's not my default style, nor is it Resharper's default style.    Resharper by default in VS2105 also encourages the use of some of the new C#6 stuff, so to avoid that creeping in you need to tell it to limit itself to C#5.

To make my life easier and keep cleanly to Bonobo's style, I have a project-specific configurations for Resharper - that's one small config file for the solution and one for each project.  If there were other Resharper users on the project, they might benefit from these, if people didn't mind seeing them in repo.

**Comment by jakubgarfield** [comment]
I don't have a problem with it as we already have a code formatting file for Visual Studio. Not everyone uses Resharper (I think it can be free for open source projects though). Maybe a linter of some sort should be part of the build process.

But I'm not very active in development at the moment - so it's more @RedX2501 @larshg and @latop2604 call.

**Comment by willdean** [comment]
OK, I added the DotSettings files.  I don't think that they'll cause anyone any problem if they don't need them.
