### ISSUE TITLE
.NET Framework version

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#466]
The project is currently built to run on .NET 4.5, which went out of support on January 12th.

Anybody object to me upgrading everything to .NET 4.5.2?

**Comment by RedX2501** [comment]
My Visual Studio only offers me the option to change to version 4.5.1. I'd have  to ask IT to update my pc to 4.5.2.

**Comment by willdean** [comment]
OK.  4.5.1 is out of support too, but it doesn't really make much difference what version of 4.5.x Bonobo is built for, it will always end up running on the latest.

I noticed you had some issue with SpecsFor with 4.5 which is why I thought of it, it's no big deal.

**Comment by RedX2501** [comment]
Hmm I guess I'll have to talk to IT anyway then if support has run out. They should have updated it then...

**Comment by willdean** [comment]
@RedX2501 I think it's possible that you have a newer version of the framework on the machine, but not the dev stuff which upgrades the options in VS.

**Comment by RedX2501** [comment]
Hmm, how do I update that?

**Comment by willdean** [comment]
http://stackoverflow.com/questions/23617900/how-to-select-net-4-5-2-as-a-target-framework-in-visual-studio

**Comment by RedX2501** [comment]
I don't have 4.5.2 but go for it (from my side). I'll get it installed.
