### ISSUE TITLE
mstest vs vstest.console

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#467]
I happened to run 'run-tests.cmd' for the first time just now, and discovered that all my hundreds of beautiful new tests failed, even though they run fine in nCrunch and fine on Appveyor.

It turns out that Appveyor is using 'vstest.console.exe' rather than 'mstest.exe' 

Judging from https://msdn.microsoft.com/en-us/library/ms182486.aspx I think vstest.console is the correct choice, besides which is makes no sense to be different to Appveyor anyway.

Is there any objection to me updating run-tests.cmd?

**Comment by RedX2501** [comment]
mstest is out of date.

In the new integration-test PR that script will go away.

**Comment by willdean** [comment]
OK, excellent, I'll ignore it for now
