### ISSUE TITLE
The AD membershipservice tests

### ISSUE THREAD

**Issue by larshg** [jakubgarfield/Bonobo-Git-Server#469]
@willdean 
They are not really helpful since you cannot create new AD users through Bonobo. 

The only way is to test direct against a global accessible AD server - where its possible to add a known user etc. that can be tested with.

So... I guess they should be removed?

Until now - I can try test out any new changes to the AD - until a more sustainable solution exist :)

**Comment by willdean** [comment]
I think that's fair comment - I'll take them out and leave them on a branch of mine in case we ever need them again.
