### ISSUE TITLE
The Names of Names

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#470]
We have a funny situation at the moment, where 'User', the EF data object has the following name fields:

Name
Surname
Username

The UserModel class, used elsewhere in the code has

Name (equivalent to Username above)
GivenName (equivalent to Name above)
Surname (that's the same as above)

I think we should fix this, and both classes should use the following:

Username
GivenName
Surname

This is a change to both classes.  I'm not proposing changing database column names, so the EF Mapping code would need to map those names across.

I can do this in about 10s, but it's going to touch a lot of files, so it would be a good idea not to do it while there are big outstanding branches.

Thoughts?

**Comment by RedX2501** [comment]
Im fine with it. I don't have any big open branches at the moment. 

There was a reason to this madness that i can't remember right now. But with all the new tests that we have now the impact of this change is less likely to have hidden gotchas.

**Comment by willdean** [comment]
Well, fortune favours the brave - I just pushed this.
