### ISSUE TITLE
Upgrade to guid causes problems for people with the Upn claim in their cookies

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#471]
We need to somehow flush people's cookies when they upgrade to the GUID version, because otherwise they may have a Upn claim which is not a GUID, it's a username.  That then causes a problem in UserExtensions when it tries to parse into a GUID.

See #407

**Comment by willdean** [comment]
Or perhaps we just need to change UserExtensions.Id to use TryParse

**Comment by RedX2501** [comment]
I guess we can check it the beginning of authentication if the Upn contains a valid GUID. If not reset the cookie and forward to login.

Here is how to remove the cookie:
http://stackoverflow.com/questions/5122404/how-do-you-clear-cookies-using-asp-net-mvc-3-and-c/5122611#5122611

**Comment by willdean** [comment]
We probably don't need to remove the cookie ourselves - if we just refuse to Authenticate at that point, then I suspect the framework will deal with it - it will do a redirect-to-login, which will then give us a decent cookie.

**Comment by willdean** [comment]
I'm closing this, because I think #488 fixes/avoids it
