### ISSUE TITLE
Can't run the new integration tests with VS2015

### ISSUE THREAD

**Issue by larshg** [jakubgarfield/Bonobo-Git-Server#473]
hey @RedX2501 

I can't get them to run, because when the SpecsForMvcConfig is instantiated i throws an error:

Test Name:	RunGitTests
Test FullName:	Bonobo.Git.Server.Test.Integration.ClAndWeb.MsysgitIntegrationTests.RunGitTests
Test Source:	D:\Code\CSharp\Bonobo-Git-Server\Bonobo.Git.Server.Test\IntegrationTests\MsysgitIntegrationTests.cs : line 58
Test Outcome:	Failed
Test Duration:	0:00:00

Result StackTrace:	
ved SpecsFor.Mvc.SpecsForMvcConfig.AssertEnvironemntValid()
   ved SpecsFor.Mvc.SpecsForMvcConfig..ctor()
   ved Bonobo.Git.Server.IntegrationTests.AssemblyStartup.AssemblyInit(TestContext tc) i D:\Code\CSharp\Bonobo-Git-Server\Bonobo.Git.Server.Test\IntegrationTests\AssemblyStartup.cs:linje 33
Result Message:	Assembly Initialization method Bonobo.Git.Server.IntegrationTests.AssemblyStartup.AssemblyInit threw exception. System.InvalidOperationException: System.InvalidOperationException: Unable to find required Microsoft Build Tools 2013 installation folder.  Be sure you install Microsoft Build Tools 2013 from http://www.microsoft.com/en-us/download/details.aspx?id=40760. Aborting test execution.

and it seems hardcoded [here](https://github.com/MattHoneycutt/SpecsFor/blob/master/SpecsFor.Mvc/SpecsForMvcConfig.cs)

There was a proposal to change the path. but that seems to only for the IISExpress setting [here](http://stackoverflow.com/questions/24824203/specsfor-mvc-msbuild-exe-not-building-publishing-project-correctly-in-visual)

Maybe we need to open a issue at SpecsFor?

I have only VS 2015 installed and hence it cannot find the MS build tools 2013.

Also is it possible to switch out 7z with a powershell script like what are proposed [here](http://stackoverflow.com/questions/17546016/how-can-you-zip-or-unzip-from-the-command-prompt-using-only-windows-built-in-ca) - I'm not really that familiar with setting up all these commands, so I didn't succeed with my limited time :)

**Comment by willdean** [comment]
Have a look at this issue, which has a misleading title, but is actually about changing the msbuild path - the poster links to a gist which might be helpful.  https://github.com/MattHoneycutt/SpecsFor/issues/70

**Comment by RedX2501** [comment]
We are using IISExpress so it should not be a problem setting that variable through some code.

**Comment by RedX2501** [comment]
@larshg Is your last sentence about the 7z dependency on the git extraction or about your problem?

**Comment by RedX2501** [comment]
@larshg BTW i think you are the only one that can provide a patch to this as i'll guess willdean does hae the tools installed as he did not have a problem.

I tooks like the gist provided by willdean will fix the problem for you.

**Comment by larshg** [comment]
The thing is the code breaks on the SpecsForMvcConfig constructor and hence not about the iisexpress, where you can set the paths to msbuild - so no it doesn't really help me :( - Maybe I should try ask at SpecsForMvc git page.

The dependency of 7z was just for convenience - not forcing people to install 7z and add it to the system path for the git extraction yes.

**Comment by RedX2501** [comment]
I actually think that probably providing a string argument to the constructor is the quickest fix here. Maybe we can create a PR for SpecsFor?

**Comment by willdean** [comment]
> Also is it possible to switch out 7z with a powershell script like what are proposed here - I'm not really that familiar with setting up all these commands, so I didn't succeed with my limited time :)

The git download is actually a self-extractor, so doesn't need anything else to extract it, just some very hard beating on the command line, which I've just given it - hopefully it will appveyor OK.

I'm not 100% happy with us running post-install.bat either - it fails here anyway, but I don't want a VS build to be messing around trying to change global stuff on my machine, which post-install does.

**Comment by RedX2501** [comment]
@willdean The post-build stull could probably mitigated by applying some kind of transform or using the appveyor redistribution stuff. We need to look into it.

**Comment by willdean** [comment]
@RedX2501 I too found in incredibly difficult to find the switches, but I got it from the answer here http://stackoverflow.com/a/32105548/987 - not the most up-voted answer, but the one below it.

**Comment by RedX2501** [comment]
@larshg since the problem has been identfified can we close this?

**Comment by larshg** [comment]
Well. There is not solution yet?

**Comment by RedX2501** [comment]
According the chrsmdev my patch fixed the problem. At least i thought so...

**Comment by larshg** [comment]
Are you mixing two issues now ? :) The PRs( #482 and #485) about @chrismdev problem (#475) is not about the integrations test and MSbuild which this issue is about ?

**Comment by larshg** [comment]
I have created an issue [here](https://github.com/MattHoneycutt/SpecsFor/issues/89) - to see if there is any solutions or there has to made a PR to his project.

**Comment by RedX2501** [comment]
@larshg Oh I'm so sorry! Yeah you are right! I only thought we can close this because we definitely need a patch or you to install the build tools.

**Comment by larshg** [comment]
Just a note - specsforMVC is released in a new version 4.7.2 where it doesn't throw on MSBuild not being found if you provide the path.
