### ISSUE TITLE
RepositoryPermissionService User.Id is null

### ISSUE THREAD

**Issue by chrismdev** [jakubgarfield/Bonobo-Git-Server#475]
Hi,
When trying to clone a repo I am getting either authentication failed or 500 errors because the User.Id is null in the GitController, specifically this line:

bool hasPermission = RepositoryPermissionService.HasPermission(User.Id(), repositoryName);

I'm using windows authentication with the active directory membership service. The user I am testing with is an administrator (ie: is a member of this group: ="ActiveDirectoryRoleMapping" value="Administrator=GitAdmins" ).

I can clone the repo if I set the anonymous flag.

**Comment by chrismdev** [comment]
This is my workaround for the problem. Is this safe?

   public ActionResult SecureGetInfoRefs(String repositoryName, String service)
        {
            if (!RepositoryIsValid(repositoryName))
            {
                return new HttpNotFoundResult();
            }

            bool hasPermission = false;
            string username = string.Empty;
            string password = string.Empty;
            if (User.Id() == Guid.Empty)
            {
                var basicAuth = Request.Headers["Authorization"];
                if (!string.IsNullOrEmpty(basicAuth))
                {
                    var base64 = basicAuth.Split(' ');
                    var plainTextBytes = System.Convert.FromBase64String(base64[1]);
                    var usernameAndPassword = System.Text.Encoding.UTF8.GetString(plainTextBytes);

                    if (!string.IsNullOrEmpty(usernameAndPassword))
                    {
                        var usernameAndPasswordArray = usernameAndPassword.Split(':');
                        username = usernameAndPasswordArray[0];
                        password = usernameAndPasswordArray[1];
                        System.Diagnostics.Debug.WriteLine("username : " + username);
                    }
                }
                hasPermission = RepositoryPermissionService.HasPermission(username, password, repositoryName);
                System.Diagnostics.Debug.WriteLine("hasPermission: " + hasPermission);
            }
            else
            {
                hasPermission = RepositoryPermissionService.HasPermission(User.Id(), repositoryName);
            }

            bool allowAnonClone = RepositoryPermissionService.AllowsAnonymous(repositoryName);
            bool isClone = String.Equals("git-upload-pack", service, StringComparison.OrdinalIgnoreCase);
            bool isPush = String.Equals("git-receive-pack", service, StringComparison.OrdinalIgnoreCase);
            bool allowAnonPush = UserConfiguration.Current.AllowAnonymousPush;

            if (hasPermission || (allowAnonClone && isClone) || (allowAnonPush && isPush))
            {
                return GetInfoRefs(repositoryName, service);
            }
            else
            {
                return UnauthorizedResult();
            }
        }

**Comment by RedX2501** [comment]
I guess this was a direct result of https://github.com/jakubgarfield/Bonobo-Git-Server/commit/2af315756ebec6bfcf05f43b09d3fd073c186186. There user adding was removed because it should be done by the background service but i guess if you have enough users it could happen that the user you are using has not been added by the time you try to use him.

@larshg Is this scenario possible?

**Comment by RedX2501** [comment]
@chrismdev Please make that a PR so we can test it outright.

**Comment by RedX2501** [comment]
After looking at you code I don't think that's the best option because it spreads authentication.

I have a similar problem with WindowsAuth. Every user has to log in to the website at least one before being able to checkin/commit if anonymous auth is off. I think that is a fair thing to excpect from the user.

Did you log in into the website with the user at least once before trying to checkout?

**Comment by chrismdev** [comment]
Yes I had. Are you using windows auth or cookies?
How does git know what user credentials to use?

**Comment by RedX2501** [comment]
I was using windows auth.
Your git knows the credentials from the command line. The internal git does not care about credentials.

**Comment by chrismdev** [comment]
How does git know your credentials? Apart from this: http://username%40domain.local@server/Git/repo.git

**Comment by larshg** [comment]
As far as I could debug the the AD is queried for users when the application is started and afterwards every 2 minutes. I don't think that this is the problem - as the json files is more about role providing and not authentication?

I'll try to see if I can reproduce the problem asap.

**Comment by willdean** [comment]
I'm with @RedX2501 - if `User.Id()` is null for a named user by the time we get to the controller action, then that probably needs fixing at the GitAuthorizeAttribute level.   I'm :-1: on this patch as it stands.

As I understand it, we should never get out of GitAuthorizeAttribute.OnAuthorisation without a properly filled-in httpcontext.User.   I wonder if this is related to #471 in that things are being allowed through GitAuthorizeAttribute which are incompatible with the later code.

**Comment by larshg** [comment]
What username do you supply? with domain or?

**Comment by larshg** [comment]
Can you try debug line 84 in ```GitAuthorizeAttribute``` and verify that the username here (it still changes \\ to ! - which I think should be removed? a second issue) - and that the ```GetClaimsForUser``` can find your supplied username in your database in ```GetClaimsForUser``` in class ```AuthenticationProvider``` - and that the user is properly filled?

I cannot reproduce the error - when I login with a admin or just a  member which doesn't have access. I get properly access with the admin user and rejected with the member with no access.

**Comment by larshg** [comment]
If we use AD with internal membership - the users has to login before being added to the database - I actually don't know if this would happen if they did a clone first - but then they should have the git address from someone else? - but this is properly a issue for it self.

**Comment by RedX2501** [comment]
You can try the following:

Disable the background updater.
Remove the user from the AD repos (delete the json file)
Now try to clone.

Auth should still succeed but then the guid will probably be empty.

**Comment by willdean** [comment]
I've just put up PR #477 which might help with this, though I'm not able to test it, really.  It's perhaps more likely to fix #471 than this one.

**Comment by chrismdev** [comment]
@larshg Thanks for the tip, I set the debugger at  line 84 in GitAuthorizeAttribute and found the problem to be that git was sending credentials in the format DOMAIN\username rather than username@domain.local (even though I was trying to clone using this: http://username%40domain.local@localhost:61921/test.git). I have added a super hacky patch that fixed it for me but I'm sure you guys can write nice clean code to handle both username formats.
