### ISSUE TITLE
Let's not overload Guid IDs with error information

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#478]
@RedX2501 and I have had various discussions on various issues about the misuse of GUIDs as error values.  (We both catch each other out at it!)

I think the introduction of the GUID IDs is a fantastic opportunity for the code, and we should not squander that now by wasting many of their advantages by wrapping them in the disadvantages of other techniques.

I propose the following:

1. We never use Guid? at all.  If a method can optionally take a Guid, then make two methods, one which takes it a Guid and one which doesn't
2. We never return Guid.Empty from something which returns a Guid.  If you can't return a real Guid, throw an exception.
3. If you're unsure if something is going to be able to return a Guid, then have a method which tests first for validity and returns true/false, don't muddle up the two concepts.
4. Unintialised Guids (e.g. in new xxxModel objects) will be Guid.Empty, because that's the way the framework works, so we may need to test for Guid.Empty sometimes in creation code, but we'll never assign it.
5. If you're given a Guid, you can assume that it's valid.  (Obviously some front end auth code might need to actually verify this, but backend code should just trust the guids)

I recognise that some parts of the project have been previously written to be extremely defensive, and will do their utmost not to throw an exception, but I think this is holding us back in improving the reliability.

**Comment by RedX2501** [comment]
(Sorry for editing your post but I had to convert your bulleted list to a numbered list to be able to reference the points)

I don't agree with 1. this takes you back to the old C style of programming. But i agree that we should never take a `Guid?`, we should always make the parameter `Guid`.

2. I think this is a valid point as trying to get something that doesn't exist should rarely happen.

3. I don't understand this one...

4. Nice

5. We should aim to achieve this.

**Comment by willdean** [comment]
Numbers are much better than bullets...  But are yours out-by-one in your list?

**Comment by willdean** [comment]
Guid? is hardly used at all at the moment, but I think, for example, CreateUser might be better written as two overloads of CreateUser, one which takes a Guid, and must always be given a valid Guid, and one which doesn't take a Guid, and creates a Guid before calling the first one.   I'm not sure that's too C' like.

The other use of Guid? is in GetPermittedRepositories, and I think that one's just wrong.  If we don't know the user, we should not be asking what repositories they are allowed to access.   Besides which, it's only called in two places at the moment - once with constant null, where clearly it's not being asked about what a user has access to anyway, and once with a Guid which is never null anyway.

**Comment by RedX2501** [comment]
Hehe not on my edit form.. It seems that markdown insists on starting on 1. doesn't matter what i give to it as starting number....

I think that we are over-engineering this.

I think if we agree on never using `Guid?` and that `Guid.Empty` is not a valid user we already won 90% of the battle.

I'd just really dislike to see code like `if(guid != null && guid.value != Guid.Empty)`.

**Comment by willdean** [comment]
I think we're in complete agreement!

**Comment by larshg** [comment]
I think it sounds great to make some guidelines of how to use the guid :)
