### ISSUE TITLE
ADRepoRepo and EFRepoRepo have different 'PermittedRepository' rules

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#480]
The EF version of GetPermittedRepositories (which is used by the web app to show the list of repos on the Repo Index page) has more permissive rules than the AD version.

I'm thinking of refactoring these two classes so that they can share all this code, so that this sort of discrepancy can't happen in future, but if anyone has an opinion about which one's correct, this would be the place to express it.

EF version:
```
   return GetAllRepositories().Where(repo => 
                repo.Users.Any(user => user.Id == userId) ||
                repo.Administrators.Any(admin => admin.Id == userId) ||
                repo.Teams.Any(team => teamsId.Contains(team.Id)) ||
                repo.AnonymousAccess).ToList();

```

AD version:
```
 return GetAllRepositories().Where(x =>
                x.Users.Any(user => user.Id == userId) ||
                x.Teams.Any(team => userTeamsId.Contains(team.Id))
                ).ToList();

```
So the difference is repos with Anon access and repos where you're an admin but not a user (which probably never happens in real life)

**Comment by RedX2501** [comment]
Maybe we should look throug the git log and see why it was changed.

**Comment by willdean** [comment]
Good suggestion to compare the history - basically the AD RepoRepo never had these checks - at the point it was first checked in they already were in EF RepoRepo but not in the AD code.

**Comment by RedX2501** [comment]
That would explain some of the AD clone anon issues we had...

**Comment by willdean** [comment]
I'm going to have a MkII attempt at getting as much as possible of the AD Code under test, then we can get it to a point of consistency with EF, either by fixing it or combining it.

**Comment by RedX2501** [comment]
Btw i think that the EF version is the correct one.

I'll close this as it is clear that this is a bug that needs a PR.
