### ISSUE TITLE
Repo Detail Edit Listbox formatting and error messages

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#481]
We discussed this on #426, but just so it isn't forgotten:

 - [x] The listboxes on repository detail page are not formatted as well as they used to be.
 - [x] The error message which is derived from the name of one of the listbox group properties is not very nice - see attached image.

![err](https://cloud.githubusercontent.com/assets/1306085/13260092/fdbe21be-da51-11e5-90c0-954d8ca88ff3.png)

**Comment by RedX2501** [comment]
Commits https://github.com/jakubgarfield/Bonobo-Git-Server/commit/174d17cb911ff6cf18ba5edc479f3a856f4beaca and https://github.com/jakubgarfield/Bonobo-Git-Server/commit/a64b615db48cac12da1c4a187379f7a83d600da1
