### ISSUE TITLE
Impossible Log in.

### ISSUE THREAD

**Issue by cerberoades** [jakubgarfield/Bonobo-Git-Server#486]
Hi,

I've downloaded and installed Bonobo.Git.Server version 5.1.1 successfully, but, when I try to log in seems that the Sqlite.Interop.dll loading process have an error. The log file is attached and begin with this line:

Native library pre-loader is trying to load native SQLite library "C:\inetpub\wwwroot\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll"...

 My system is Windows 7 x64 with IIS 7.5.

[Bonobo.Git.Server.Errors.txt](https://github.com/jakubgarfield/Bonobo-Git-Server/files/149141/Bonobo.Git.Server.Errors.txt)

**Comment by RedX2501** [comment]
What have you configured as authentication provider and membership provider? What exactly happens when you try to log in and with which credentials? 

If it's a new installation can you try this version and tell us if the error is still there? https://ci.appveyor.com/api/buildjobs/5p9al2qyngirskto/artifacts/bonobo-git-server-2710074-78c669d5fdd398f502673fb32bb16d111ebdd743.zip

**Comment by cerberoades** [comment]
Hi RedX2501,
My authentication provider is this:

<add key="AuthenticationProvider" value="Cookies" />

and membership provider:
<add key="MembershipService" value="Internal" />
When the web browser access to "http://localhost:8080/Bonobo.Git.Server/Home/LogOn" and write username admin and password admin the browser doesn't respond. Without any 500 Error or 404 Error, nothing, just a white page.
I tried to figure out what is going on and I find the error in the log file attached to my first commentary. I think that when Bonobo Git Server try to access to the database, the SqlClient throw an exception because it can't reach the database.
Meanwhile I'll test the @RedX2501 's link.

**Comment by RedX2501** [comment]
Ok i think the version I posted won't help.

I guess it is having trouble finding your sqldb. What settings did you put for connecting to your sql server?

**Comment by willdean** [comment]
@cerberoades Could you show us the ConnectionStrings section of your web.config (remove any passwords if you've put them in there).

**Comment by cerberoades** [comment]
@RedX2501 here is the ConnectionStrings section in my web.config file.

<connectionStrings>
    <add name="BonoboGitServerContext" connectionString="Data Source=|DataDirectory|Bonobo.Git.Server.db" providerName="System.Data.SQLite" />
    
  </connectionStrings>

As you can see, the provider SQLClient is disable. This configuration come from the original web.config file in the Bonobo Git Server 5.1.1. I don't made any change.

**Comment by willdean** [comment]
@cerberoades You need to edit your comment here and mark the section you've posted at code (use the `<>` button.

**Comment by RedX2501** [comment]
The posted configuration does not agree with the trace you posted above. The trace is complaining about not being able to connect to the SQLServer while that configration says to use SQLite....

Are you sure you have posted the correct things?

**Comment by cerberoades** [comment]
Yes, I'm totally sure. I just download the Bonobo Git Server, I made the configuration, when I use the initial credentials username:admin password:admin the log file contains this line:

`Native library pre-loader is trying to load native SQLite library "C:\inetpub\wwwroot\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll"...`

and a few seconds after the log file show me this
[Bonobo.Git.Server.Errors.txt](https://github.com/jakubgarfield/Bonobo-Git-Server/files/151608/Bonobo.Git.Server.Errors.txt)
 file.

 nothing happens.Now, I'll download the source code to fix the problem.

**Comment by willdean** [comment]
Don't worry about the  "Native library pre-loader is trying to load native SQLite library ..." bit - it's not an error, it's just something that the Sqlite interface writes to the trace stream and which gets swept up into the log.

If you do download the source, then you may well find that either it works OK, or that at least it has more information in the log file which could help us help you.

It does appear that something is going wrong in the way the app is configured or starts up, because a call to check role membership is not routing into Bonobo's own code, it's going off into framework code that mistakenly tries to call into SqlServer.  This is because 'User' in WebAuthorizeAttribute.OnAuthorization is not the type of object we'd expect.

A couple of questions about the machine running Bonobo:

* What version of Windows/IIS and .NET framework is on the machine?
* Does this machine run any other IIS applications?
* Could you possibly already have a cookie set for the domain which Bonobo is running on?  (Can you try clearing cookies in your browser?)

**Comment by cerberoades** [comment]
Hi @willdean , here the answer to you questions:

Q: What version of Windows/IIS and .NET framework is on the machine?
A: Microsoft Windows 7 Professional SP 1 x64; IIS 7.5; .NET Framework 4.

Q: Does this machine run any other IIS applications?
A: No, it doesn't. I've install IIS only for Bonobo Git Server.

Q:Could you possibly already have a cookie set for the domain which Bonobo is running on? (Can you try clearing cookies in your browser?)
A: This isn't a cookie problem. I've tried access to the git web server from 3 different computers over the network and it doesn't work:

**Comment by RedX2501** [comment]
If you do have the new version, please dump the contents of
/home/diagnostics here please.

**Comment by cerberoades** [comment]
@RedX2501  I have the version 5.1.1 and I don't see any /home/diagnostics folder.

**Comment by willdean** [comment]
@cerberoades Can you try the version @cerberoades linked to in the second comment on this issue?

**Comment by cerberoades** [comment]
The problem continue. The same error in the log file.

**Comment by willdean** [comment]
@cerberoades With the new version, can you go to the page `http:<your server>/home/diagnostics` and send us the contents of that page.

**Comment by cerberoades** [comment]
[GITHUB.txt](https://github.com/jakubgarfield/Bonobo-Git-Server/files/159264/GITHUB.txt)

**Comment by willdean** [comment]
@cerberoades Thanks for that.

Can you please look in the web.config for the bit which mentions `runAllManagedModulesForAllRequests` and change it to look like this:

```
   <modules runAllManagedModulesForAllRequests="true">
      <remove name="RoleManager"/>
    </modules>
```

Please let us know if this makes a difference.

I am following this Stackoverflow post, which seems to describe your situation:

http://stackoverflow.com/questions/10663555/remove-asp-net-membership-and-roles-provider

**Comment by cerberoades** [comment]
@willdean , the modification in the web.config work perfectly. Thank you so much. This was my only modification inside the web.config file:

`<modules runAllManagedModulesForAllRequests="true">
      <remove name="RoleManager"/>
    </modules>`

Maybe this will be a help to someone. 
Environment: IIS 7.5 Windows 7 x64
My web.config:
[web.config.txt](https://github.com/jakubgarfield/Bonobo-Git-Server/files/161652/web.config.txt)

**Comment by willdean** [comment]
@cerberoades Excellent - thanks to Stackoverflow - and thanks for letting us know - I'll commit that as a mod to the standard code, because it's harmless to everyone else.
