### ISSUE TITLE
Why does AD have a separate database?

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#489]
I have been playing here (not with any specific intention of merging it) with getting rid of much of the AD-specific code, and just importing the AD users/teams into the EF database.

When I looked back at the history of the AD code, it appears from looking at  082d357b that this is actually what happened before the recent AD code arrived - there was a routine called WindowsIdentityImporter.cs which loaded the EF database with AD data.

Does anyone ( @jakubgarfield, @Ollienator, @RedX2501 ?) remember what the motivation for the separate database was, and why the import into the EF database was dropped?

**Comment by RedX2501** [comment]
Im afraid test happened before I joined the project.

**Comment by willdean** [comment]
Ah right, I'll see if I can work out how subgroups work / what they are.  The AD store is just a list of xxxModel objects so it hopefully isn't too far from what the EF store can do.

**Comment by RedX2501** [comment]
We could make AD derived from some base and only override the group functions. Or teach Bonobo about subgroups.
