### ISSUE TITLE
Logging?

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#490]
Bonobo currently has fairly simple logging, just writing exceptions to a file.

I think some of the problems people report issues on could be more easily debugged if there was better logging in the application - for example lots of the interaction with AD could be logged at various levels, which could be very helpful when trying to diagnose problems, and there are lots of other situations where we have some indication that something's going wrong, and logging a warning could be helpful.

What do people think about adding a logging framework and starting to make use of it?
Personally I'd probably use NLog or Serilog, but I'm not fussed if anyone else has strong feelings about something else.

**Comment by RedX2501** [comment]
What would their advantage be against trace.write? I think the real problem is how to activate the logging at runtime.

Another problem i faced was that many non 500 non
Errors never made it into the trace.

**Comment by willdean** [comment]
Tools like nlog have logging levels which can be set in web.config.  So you add as much logging to the app as you like, at various levels (from errors to warnings to info to very noisy debug level) and then the user can turn the level up to suit in web.config.  The proper log frameworks also do stuff like log file rotation, so that you can keep just the last month's logs, etc, without having to write that yourself. 

Trace does some of that, and maybe I should investigate it more.  The mere fact it holds a lock on the logfile makes me hate it. :-)

**Comment by CrispinF** [comment]
The existing logging does not write the date/time of the error. That would be extremely helpful (actually essential for most troubleshooting in a multi-user environment). 
I would also support switching to a more full-feature logger like NLog.

**Comment by holiiveira** [comment]
Taking advantage of the topic, there could be a possibility to enable a record for the operations log a repository (example: when deleted, record who and when information was deleted)?
