### ISSUE TITLE
Github pull requests

### ISSUE THREAD

**Issue by chrismdev** [jakubgarfield/Bonobo-Git-Server#493]
I was trying to find a thread where I could vote on adding a Github style pull request feature to Bonobo.

So here is my +1 for that feature.

Can anyone elaborate on what would be required so I can try and have a go at it?

**Comment by RedX2501** [comment]
I don't think we should go down that road. if anyone wants any fancier features he should in my opinion move to GitLab/Gerrit or similar.

IMHO Bonobo should stay what it is. A simple way to provide access to repos on windows using WindowsAuth/Federation. That is the primary reason i chose it over the other products.

I also feel like closing all the other feature requests for not allowing commit to branches and similar on the grounds that that is not the main purpose of Bonobo. Don't know how the others feel about it.

You would need to provide diffs between branches and a way to visualize and vote on that. For that you need to use libgit2 internals.

**Comment by willdean** [comment]
I reckon this kind of strategic product direction decision is above my pay grade, but I think on a practical level the project doesn't really have the resources or direction at the moment to attempt to build a replica of GitHub even if we wanted to.

As @RedX2501 says, the way Bonobo could differentiate itself would be by having a great Windows story - easy install + configure, reliable + secure, good integration with Windows environment (AD, WinAuth etc).  

Personally I'd like to think that Bonobo could be got to a point of clean 'library quality' perfection, that it would be a basis for someone to build other things on top if they wanted to, but I'm :+1: for limiting the scope of the core project to something in which a reasonable quality level can be maintained.

I think the request about limiting pushes to branches perhaps falls into a grey area about Bonobo's legitimate role as a 'permissions server', but pull-requests and web-based content editors (that's another open issue somewhere) are probably too much.  

I don't feel it's my decision really, and I'm not really sure how much strategy @jakubgarfield has delegated (none to me, I know!).

**Comment by chrismdev** [comment]
Fair enough. Will close this then.

**Comment by jakubgarfield** [comment]
Sorry guys I was away without any internet access - I agree here with @RedX2501 that Bonobo should stay really simple and with @willdean that it should provide really great Windows story with the integrations that other products don't have.

Thinking really longterm - features like PRs and Issues would be awesome in a form of extensions installable to the git server - but the system wasn't written with that in mind at the beginning.

Stable, reliable access to git repositories for users on Windows platform that provides nice user management and access control.

But that's only my point of view and it's more important what you guys as active contributors think the project direction should be.
