### ISSUE TITLE
Is there any way to get actual git username in server side hook and client side hook?

### ISSUE THREAD

**Issue by sgosulazc** [jakubgarfield/Bonobo-Git-Server#494]
We have $(git var GIT_AUTHOR_IDENT) adn $(git var GIT_COMMITTER_IDENT) commands but by updating the repository settings users can give fake these values. 

Do we have any option to get actual authenticated username?

**Comment by RedX2501** [comment]
We provide the variables `AUTH_USER` and `REMOTE_USER` as environment variables on the server side.

Are they enough for you?

**Comment by sgosulazc** [comment]
That's great! Thank you.

**Comment by manoj0007** [comment]
the variables AUTH_USER and REMOTE_USER are not available on server side!!

**Comment by RedX2501** [comment]
@manoj0007 Can you be a little bit more explicit? what dou you mean? How did you try it out? What Bonobo version are you using?

**Comment by sgosulazc** [comment]
**@manoj0007:** If you want to get user information inside the web application then you can get it from HttpContext.Current.User. You will get details like Id, Name and Roles etc and It internally uses claims get fetch values.
