### ISSUE TITLE
Do we have any option to read user group name or user roles in git hooks?

### ISSUE THREAD

**Issue by sgosulazc** [jakubgarfield/Bonobo-Git-Server#495]
We would like to restrict users to delete remote branch based on user role/ users belong  to a group.

Can we read that information from git server side hooks?

**Comment by RedX2501** [comment]
Unfortunately not (yet)

If the user belongs to multiple groups, would a`,` separated list in a environmental variable be fine?

**Comment by sgosulazc** [comment]
Yes, that might help us. how to get the list of groups for a user?

And do we have any function similar to getpwuid in perl?

**Comment by RedX2501** [comment]
There is no way yet. We need someon to implement this feature.

You can write the script for your hook in any language.

I'm no familiar with getpwuid in perl. What does it return?

**Comment by sgosulazc** [comment]
It will return user information like name, password, group ect.

I heared bonobo will maintain a database, can we read data from that database in hooks?

**Comment by willdean** [comment]
@RedX2501 may know better than me, but my guess would be that in the hook, you're quite a way from the Bonobo process, and it would be difficult to provide services to that (I guess we could have an HTTP API).   It's easy to populate environment variables though, so the hook could be provided with everything that the database contains _about the current user_.  Would that be enough?

**Comment by RedX2501** [comment]
There is not much to get from the database, you cannot read any passwords (because they are hashed and salted). The only other piece of interesting information might be the email address of the user.

What exactly are you looking for?

**Comment by sgosulazc** [comment]
We would like to restrict the users based on their roles. I guess we will have this information in database, if we have access to DB from hooks, we can read that details and restrict users based on it.

**Comment by RedX2501** [comment]
I propose that we add an export to the roles and groups of the user making the commit through an environment variable. 

Is this a viable solution for you?

**Comment by sgosulazc** [comment]
Yes, that perfectly make sense.
