### ISSUE TITLE
EF 6.1 and the SqlServer AddColumn

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#496]
I happened to notice that the tests project was using EF6.0, while the main project was using 6.1.3.
For neatness, I updated the test project to use the same version as the main app.

Unfortunately, this caused all the SqlServer unit tests to break in `AddGuidColumn.CopyUsers()` with the exception "There is already an open DataReader associated with this Command which must be closed first."    It seems EF6.1 refuses to execute SQL commands on a database while the SqlQuery is still open.

My guess is that this problem would have showed-up for SqlServer users with Bonobo, and it was just hidden in the unit tests - I've never tried the SqlServer code in real life, just in the tests.

The solutions seem to be either enabling MultipleActiveResultSet, which requires a connection string change - that seems a bit nuclear for a one-time upgrade, or just loading the whole table into memory before writing it all out again.   (Or copying it with T-SQL and not in C# code)

My guess is that the application would break in other places if you couldn't load a whole table into memory - in generally it's very casual about doing this, so that's probably not a problem.  But I wanted to gauge opinion before I did that.

**Comment by RedX2501** [comment]
Why do we have an open reader there? I always thought we'd use the same reader for all operations.

I think copying the tables into memory is fine. I don't think we'd ever have gigabytes of information in the db

**Comment by willdean** [comment]
I think the reader is created by the _db.SqlQuery call, and we're in the middle of a foreach, attempting to do a ExecuteSqlCommand for each iteration.
