### ISSUE TITLE
Admins aren't explicitly granted login privileges

### ISSUE THREAD

**Issue by hmmwhatsthisdo** [jakubgarfield/Bonobo-Git-Server#499]
As it stands, when using the AD membership service, users (or group members) who are designated as administrators but not delegated user permissions are unable to log in.

For example, if two AD groups - GitUsers and GitAdmins - had users UserA and UserB / UserA and UserC, respectively (with role mapping as hinted by the group names), UserA would be able to log in but UserC would not.

**Comment by willdean** [comment]
I'm assuming you're reporting this against 5.1.1?  This may have been fixed in master, because there's been an enormous amount of work on permissions and fixing problems in the AD code.   

I don't think we intend that there is any right available to an 'user' which is not also available to an 'admin'.

**Comment by hmmwhatsthisdo** [comment]
This was after upgrading to a build from master commit d012d5279f48f12b7b45f33e9ad6ac3eee7d50ee. I didn't keep track of what master commit build I upgraded from (whoops!), but I believe it was from around 2/19.

What I did notice was that after I upgraded, I iterated through all of the ADBackend\Users\*.json files - none of the users in the admins groups actually had JSONs for their accounts.

**Comment by willdean** [comment]
OK, I've had a look at it, and the AD importer is pretty clearly designed to work like this:

* _Everyone_ who is visible to Bonobo should be in the 'Members' group (including all the admins)
* People in the admins group are given the role of Administrator

Given that's how it's intended to work, how much of a problem is it for you to live with that?

**Comment by hmmwhatsthisdo** [comment]
I'll need to talk with our the people who actually manage our OU (sadly, I'm not important enough for that) but I would imagine it won't be an issue.

**Comment by willdean** [comment]
OK, I'll close this for now, let us know if it turns out to be a show-stopper.
