### ISSUE TITLE
Git Admins shouldn't need to mark their own accounts as repo administrators when editing permissions

### ISSUE THREAD

**Issue by hmmwhatsthisdo** [jakubgarfield/Bonobo-Git-Server#501]
Right now, when a server-wide admin opens the Edit dialog for a repository, they have to tag their account as an administrator within the administrator list for that repo in order to be able to save changes. Not doing so throws the error "You can't remove yourself as an administrator".

This seems a bit counter-intuitive, as it shouldn't matter whether or not a server admin is an admin over a specific repository - they're going to have access regardless.

**Comment by willdean** [comment]
Yes, this is overzealous checking on the part of the form - the permission layer lets a system-admin do everything anyway, as you say there's no need for it to be burnt into the repo record too.

**Comment by willdean** [comment]
@RedX2501 I think there are two checks here which are not strictly necessary:

1. There's a requirement in RepositoryDetailModel that a repo has to have an admin, which seems to me unnecessary, given that you can just be a sys-admin and administer everything anyway, and the one bad situation, (which is a repo-only-admin removing themselves from the repo) is caught by the 'don't remove yourself' below.

2. As @hmmwhatsthisdo notes, the 'don't remove yourself' rule (in the action method) does not need to apply to a sys admin.

Any objections to me removing rule 1 and modifying rule 2?

**Comment by RedX2501** [comment]
Nope go for it.

I always found that rule strange anyway.
