### ISSUE TITLE
BinaryGUID=False needs to be detected/enforced.

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#506]
It's well established that for the guid update you need to have BinaryGUID=False; in the sqlite connection string, otherwise bad things happen.

I am thinking that we need to detect/enforce this before/during the AddGuidColumn update when people start upgrading to 6.0.0, because otherwise we could end up in a world of misery if people hang on to their existing web.configs.

Either that or fix the code to work with binary guids in the sqlite code - I'm not sure what's involved in that.

**Comment by RedX2501** [comment]
:+1: 

We can ask the connectionstring of the EF framework if it contains the appropriate string.
