### ISSUE TITLE
Integration Test Improvements

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#513]
This is not critical stuff for 6.0.0, but just up for discussion:

The new integration test framework is great, and was an enormous amount of work for @RedX2501, but it's currently taking me 5x as long to get the tests working as it does to write the code that I'm writing the tests for.  We've (i.e. @RedX2501 has) made loads of improvements in this regard already, but here's my suggestions:

1. Interaction between tests.   We have problems where database changes made in one test are visible in other tests.  We're trying to solve this at the moment with better clean-up within tests (disposing repos, etc), but I think that's possibly the wrong approach, for two reasons:
 1. It further slows the tests down, and they're slow enough as it is
 2. Cleanup problems in one test can still impact an unrelated test

I think it is fundamental principle of a robust test framework that one test should be able to screw everything up in any way possible, and the next test should never, ever be affected by that.   I think it's down to the test setup to arrange things predictably for each test.

Now, every bit of boilerplate in the test set-up code is painful in terms of execution rate.  We couldn't bear to have code at the beginning of every test which walked through the UI erasing users, teams, repos etc.

I propose that we implement a database reset within Bonobo, which forces the database (and possibly a git repo) into a known, fixed state, solely for the benefit of testing.  We could do this either by holding a pre-prepared .DB file somewhere (though they can be hard to overwrite) or just by using a bunch of calls to the various account services.   This could be a 'local only' action on the home controller, say.

I think we could have two different reset states that a test could request:

1. Empty (i.e. nothing except admin user) - every test would start in this state
2. Reference setup - A fixed, sample set of data, which tests could rely on without needing to set it up in each tests - so admin plus another couple of users, a team, a repo (ideally containing some files, though that's a different challenge)

**Comment by RedX2501** [comment]
Sounds reasonable. We should define what the default content should be. I'm also in favour of having to give it an username+password (ether on the URL or basic auth) just in case.

**Comment by willdean** [comment]
OK - I'll have a think about this - I think there might be some MachineKey technique we could use to make 100% sure that the request came from the test framework on the machine

**Comment by willdean** [comment]
I'm closing this, because we've done the main part of it, which was the reset.
