### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#518]
The Selenium-based integration tests are fantastic, and are an heroic effort by @RedX2501 - I think they're a great resource for raising the quality of the project.

However, they're incredibly slow, and even with the small number we've added so far, the Appveyor build is now taking about 15 minutes to run.   This is already starting to be an issue (it took hours this AM to clear the appveyor queue), and it's going to get much worse if we keep adding them at the rate we have been.

I don't want to get into a debate about names of types of tests, and anyone who cares about that can choose the names.   But, sitting between the very light-weight 'unit tests' which we have, and the super-heavyweight 'integration' (Selenium) tests, we could be writing unit tests for the controller classes directly - it's a bit of a pain because of mocking the HttpRequest objects, but there are some resources around to help with that, and with the right helpers they would be fast and easy tests to write and run, which could improve the test coverage without all the weight of the full integration tests.

I know in an ideal world, we could test everything via the Selenium framework, but I am wondering if it might be more practical to restrict the growth in the number of Selenium tests and pile more effort into testing at the controller level, where we could have tests running in milliseconds rather than seconds.

**Comment by RedX2501** [comment]
There are things that are only testable with the Selenium tests. Other things, which don't involve javascript or authentication or pushing to repositories should definitely not be done via selenimu testing.

**Comment by willdean** [comment]
Yes, I agree.  I guess the grey area is the division between:
1. Things which absolutely can only be tested in the full system
2. Things which can currently only be tested in the full system but could be tested separately if the code was better factored.

I think some of my stuff, like RepositoryCanBeSavedBySysAdminWithoutHavingAnyRepoAdmins and RepoAdminCannotRemoveThemselves is mostly in category '2'.

Although it's a separate issue, we may also be able to make a helpful improvement to the performance of some of the Selenium tests by having SpecsForMvc authorise us rather than using the login form every time, and by having a pre-loaded database which would save a lot of time on preconditions.

**Comment by RedX2501** [comment]
Specsformvc did/can do nothing more then use the login form. Especially with Csrf protection in place. 


The only thing that comes to mind is having a special login form that comes pre populated from a GET request. That should save considerable time as selenium types very slowly. 

I particularly don't care too much if the integration tests take long to execute. But it might be better to have controller only tests whenever possible.

**Comment by willdean** [comment]
Ah right - I thought AuthenticateBeforeEachTestUsing might do something magic, but I never looked into it.   We could perhaps pass username/password using parameters on the get URL for the login form? 

Anyway, you're probably right that the test time doesn't matter too much - particularly if we can get back to a place where they're a bit more reliable, which is hopefully close now.

**Comment by RedX2501** [comment]
Yeah i thought of passing Username, password, resetcode to the URL. If the request is local and the setting in web.config exists return the pre populated form.

**Comment by willdean** [comment]
Yes, good idea.

I don't really know where all the time is spent in the tests - it would be nice to have a per-test time from appveyor/mstest, to see if some are particularly slow.
