### ISSUE TITLE
Whether it can support MSSQL ?

### ISSUE THREAD

**Issue by zhouyongtao** [jakubgarfield/Bonobo-Git-Server#522]
HI，whether Bonobo-Git-Server can support MSSQL ?

**Comment by RedX2501** [comment]
What is the difference between MSSQL and SqlServer? We do support SqlServer.

**Comment by willdean** [comment]
@zhouyongtao - Yes, Bonobo supports MS SQL Server - you just need to make sure you have the right connection string in web.config.
