### ISSUE TITLE
AddRepoPushColumn sets column to invalid value

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#525]
I've just posted #524 to deal with a crash reported in #521 which was caused by an invalid enum value in AllowAnonymousPush.  I had thought this had come from some intermediate data in the database left over from partial updates, but I've now realised that it's coming from AddRepoPushColumn which sets the new column to '3', which is not a valid member of the associated enum.

I think this should be a valid member, not an invalid one, and I suspect 'No' (0) is the correct default. 

Any thoughts, @RedX2501 ?

**Comment by RedX2501** [comment]
The correct value should be Global. Sorry for that silly mistake. 

I guess we never really test the update path in our automated testing.

**Comment by willdean** [comment]
The upgrade path is called by all the membership unit tests, but there are no repos in the database when it's run, so this isn't tested.
