### ISSUE TITLE
Update to GUID throws SQLite error

### ISSUE THREAD

**Issue by jakubgarfield** [jakubgarfield/Bonobo-Git-Server#529]
When trying to run the project and update the latest schema I get an SQLite error.

```
Exception thrown: 'System.Data.SQLite.SQLiteException' in EntityFramework.dll

Additional information: SQL logic error or missing database

near ")": syntax error
```

it's in the AddGuidColumn.cs on SQL that starts at line 96.

**Comment by jakubgarfield** [comment]
@RedX2501 do you want to have a look at it?

**Comment by RedX2501** [comment]
I have confirmed it and have created a patch. I'm trying to also create tests for the database update mechanism.
