### ISSUE TITLE
Why is the exception handler in Global.asax.cs guarded by a #if

### ISSUE THREAD

**Issue by RedX2501** [jakubgarfield/Bonobo-Git-Server#532]
The title pretty much says it all.

Why don't we have it when debugging? 

The problem with not having it when debugging is that all errors will automatically go to the error page instead of properly throwing in the views.

**Comment by willdean** [comment]
+1000 from me.  I always change that condition to be `true` - you still don't get the YSOD, because that needs a web.config change as well, but at least you get the exception written to the log.
