### ISSUE TITLE
Implement semantic versioning from version 6.0.0 onwards

### ISSUE THREAD

**Issue by RedX2501** [jakubgarfield/Bonobo-Git-Server#533]
The new release 5.2.0 should have been 5.1.2 according to semantic versioning.

I think we should use semantic versioning to make it clear from the version number alone what the implications of a new version might be.

The disadvantage of course is that we probably won't have version 312 in a few months like Firefox and Chrome like to do it.

http://semver.org/

**Comment by willdean** [comment]
I thought the patch was going to be 5.1.2 too, though I don't suppose it matters (perhaps I run the only Bonobo 5.1.2 server in the world :-)

I've always understood semver was mainly talking about API compatibility - we don't have an API so would we just bump the major number when the database schema changes - i.e you can't expect to ever down-grade a major version, but you could downgrade a minor version?

**Comment by jakubgarfield** [comment]
I'm trying to stick to semantic versioning, but also when there is an important release, I bump the bigger number to emphasize it's significance.

Either way is fine, the only reason I went for 5.2 was probably that I thought of it as really important release.
