### ISSUE TITLE
Using + in teamname causes blank pages using IIS

### ISSUE THREAD

**Issue by FreezyExp** [jakubgarfield/Bonobo-Git-Server#535]
I have a teamname with a + in the middle, which refuses view, edit, delete after initial creation.
Link shows %2b, replacing this with a + has no different result.

& and spaces (%20) work fine

Easiest solution would to to filter special characters on the creation pages (probably affects other parts that rely on user input name)

I have not found any related possible error logs

**Comment by RedX2501** [comment]
Thank you for the report. 

We have changed how we handle all names in the upcoming release.

Please check back in some weeks for the 6.0 release.
