### ISSUE TITLE
No anonymous access possible

### ISSUE THREAD

**Issue by ChrissW-R1** [jakubgarfield/Bonobo-Git-Server#536]
I've installed the newest version (5.2.0) of this great software successfully. Everything works fine, but there's one error which is still present: I'm not able to connect to a repository without credentials in anycase (i.e. clone the repository). Every time I am asked to enter a username and password.
Seems like the "Anonymous" checkbox on the repository settings page have no effect.

I've seen the issue #344 and that it should be fixed, but in my case the issue is still present!

**Comment by RedX2501** [comment]
This will be fixed in the upcoming 6.0 release.
