### ISSUE TITLE
remember me doesn't

### ISSUE THREAD

**Issue by chilversc** [jakubgarfield/Bonobo-Git-Server#537]
When signing in I select "Remember Me". If I then close or leave the browser idle then when I return to Bonobo Git Server I'm no longer signed in. Looking at the cookies for the site their expiriy is set to session.

I'm using the cookies authentication provider and the internal membership provider.

**Comment by RedX2501** [comment]
Thanks for pointing this out. Can you provide a PR for this? Preferably with a test.
