### ISSUE TITLE
Question: How to deploy a git Repository to Web Server?

### ISSUE THREAD

**Issue by kbdavis07** [jakubgarfield/Bonobo-Git-Server#540]
Hi,

This is a question.

Would like to know if this is possible.

Have Bonobo Git Server host a git repository on a Server.

When a push is made to the git repository it also publishes to a saved location to serve up as a website?

Like:  

A git repo push located at :http://servername/YourDomain.git

On Push goes to the physical location:

E:\Spaces\Kbdavis07\YourDomain.com\wwwroot

On the same server.

Thanks,

Brian Davis

**Comment by willdean** [comment]
This is how Bonobo works - the repositories are just ordinary Git 'Naked' repositories, which can reside on any volume that the Bonobo web application can access.

The only restriction is that all the repositories served by Bonobo have to be in subdirectories of the same directory - that directory location is then part of Bonobo's configuration.

**Comment by RedX2501** [comment]
You can write a git hook for this.

**Comment by alexkuznetsov** [comment]
@kbdavis07, you wrote about CI server. For this purpose, you can use TeamCity.
