### ISSUE TITLE
503 error except localhost

### ISSUE THREAD

**Issue by Skittluier** [jakubgarfield/Bonobo-Git-Server#543]
Hello,

I just tried to fetch my Git project from a remote device, but it seems that the service is unavailable.
I tried a lot of things, but it just doesn't seem to work.

I use a Windows Server 2012 with IIS 8.

Does anyone have a possible solution for me?

Thanks in advance.

- Skittluier

**Comment by latop2604** [comment]
Maybe this can be helpful : http://stackoverflow.com/questions/13322937/iis-http-error-503-the-service-is-unavailable.
Otherwise take a look into error log file in App_Data

**Comment by Skittluier** [comment]
Thanks for your answer, latop, but it seems that when I only get one error after trying to fetch it and that is:

> Native library pre-loader is trying to load native SQLite library "C:\inetpub\wwwroot\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll"

**Comment by Skittluier** [comment]
I found a solution. The reason was CloudFlare.

I love proxy servers! <3
