### ISSUE TITLE
New install, New Server = redirected you too many times.

### ISSUE THREAD

**Issue by WisconsinWildcat** [jakubgarfield/Bonobo-Git-Server#544]
Brand new virtual server. I think I followed setup to a "T", and this isn't my first rodeo. I have Bonobo working on two other servers, but this one hit me right off the bat. 

There are no other web sites (yet) on this system. 

Thoughts?

**Comment by willdean** [comment]
Does IIS serve-up its default site OK?

There are about 9 million ways to fail to serve an ASP.NET site, so it's really hard to say exactly which one you've found.  Have you installed the latest version of .NET and done the .NET/IIS registration stuff?  

Have you enabled serving static content and dynamic content, etc, in the Windows/IIS features?

**Comment by WisconsinWildcat** [comment]
I think I have the latest version of .NET, but ... net/iis registration?  enabled serving static content? I may have, but I don't recognize it by those names.

**Comment by WisconsinWildcat** [comment]
Static Content Compression and Dynamic Content Compression are installed.  IIS management console, iis 6 mgmgt compat, iis6 metabase compat all installed but the rest of iis stuff and iis6 stuff is not, nor is iis hostable web core.
![servermanagerroles1](https://cloud.githubusercontent.com/assets/7716691/14303374/af68daba-fb6f-11e5-8572-d7490795f630.png)
![servermanagerroles2](https://cloud.githubusercontent.com/assets/7716691/14303373/af6790f6-fb6f-11e5-9713-b202d619cf16.png)
![servermanagerroles3](https://cloud.githubusercontent.com/assets/7716691/14303372/af65ff5c-fb6f-11e5-91ce-84359479b5ef.png)

**Comment by hypervtechnics** [comment]
I have this issue too. I installed it on a complete new Windows 7 computer... Strictly  after the requirements and installation tutorial.. But it's working on my main computer.

**Comment by hypervtechnics** [comment]
Now it works. Installed TFS and it suddenly worked
