### ISSUE TITLE
global settings... Link Regex not working

### ISSUE THREAD

**Issue by bnc-rainman** [jakubgarfield/Bonobo-Git-Server#546]
Hello,

which regexp engine is used for regexp link and url on global settings.

My regexp is working. The ticket number is underlined. But what´s the anchor replacement pattern in the url.  %1%, \1 and $1 are not working.

example:
regexp: #([0-9]{7})    -->  first anchor: [0-9]{7}
url: http://myurl/index.html?ticketid=$1   --> not working

Best regards

**Comment by bnc-rainman** [comment]
In my oppionion it would be nice to use the .NET Regular Expression Synthax instead propriatier String.format Synthax, because you can use the full power of regular expressions. Also in my case report the server an exception on usage of 'http://myurl/index.html?ticketid={1}'  as url parameter.

**Suggestion: File: [Controllers/RepositoryController.cs](https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/Controllers/RepositoryController.cs#L466) -> **
Replace Line 466 - 491 
With
--- snip --
```
        IEnumerable<Match> matches = Regex.Matches(commit.Message, linksreg).Cast<Match>();
        var links = matches.Select(m => Regex.Replace(m.Value, linksreg, linksurl)).ToList();
```
--- snap ---

**Comment by RedX2501** [comment]
This has been improved for version 6. I'll check if i added a proper description.

We already use the default .net regex lib. Only the behavior was not very intuitive. 

Thanks for the feedback.
