### ISSUE TITLE
Lost Groups and Description of repositories after Upgrade from 4.0.0.0 to 5.2.0.0

### ISSUE THREAD

**Issue by danielthaller** [jakubgarfield/Bonobo-Git-Server#548]
After Update Bonobo GIT Version 4.0.0.0 to 5.2.0.0 and Operatingsystem Upgrade to Server 2012 R2 we have lost Groups and Description of repositories. Bonobo Server Show only "Discovered in file System.

Thanks in advanced.

Daniel

**Comment by RedX2501** [comment]
I'm guessing that you did not properly backup your App_Data folder but only
your Repositories folder. Is that right?

Can you tell us your exact update steps?

**Comment by danielthaller** [comment]
I have backup \App_Data\Repositories and \App_Data\Bonobo.Git.Server.db because i switched to a other server.

Upgradeprocess:
- Save \App_Data\Repositories and \App_Data\Bonobo.Git.Server.db
- download new Version and unzip this,
- copy into wwwroot (this is not located on default folder (F:\wwwroot\Git)),
- modify webconfig for AD Login,
- copy saved  \App_Data\Repositories and \App_Data\Bonobo.Git.Server.db to new AppData Folder
- set permission for AppData Folder

**Comment by RedX2501** [comment]
Is this reproducible? If it is can you post your DB file?

**Comment by danielthaller** [comment]
I have found the Problem, we use the new active directory integration. The groups and description would be stored in .json file and not in db file. 
I have modifyed all my repositories by hand and now description and Groups would be shown.
