### ISSUE TITLE
[bug] Visual Studio 2015 connectivity

### ISSUE THREAD

**Issue by sysshad** [jakubgarfield/Bonobo-Git-Server#553]
Seems one needs to use the git bash to make Visual studio 2015 work together with current version of git server.

This i how i do it:
1) Create repository through the web interface
2) Create a visual studio project locally
3) Choose add to source control
4) add the  http://adress/myfirstrepository.git as a remote host.
5) ERROR -> then when i try to sync to the remote i get info about some missing master or origin 8cant see it atmo so cant be clearer, sorry)
6) CURRENT FIX -> open git bash here and type the following
git remote add origin http://username@adress/myfirstrepository.git
git push origin master

7) then i can successfully use visual studio's sync, but it first asks for publish so i do that, then sync.

**Comment by willdean** [comment]
I'm not clear that this is a Bonobo problem
