### ISSUE TITLE
30 second page loads on Azure

### ISSUE THREAD

**Issue by KY4U** [jakubgarfield/Bonobo-Git-Server#556]
Hello,

I'm running version 6.0.0 in an Azure webapp with ~ 4 gigs of data in 100 repositories.  Unfortunately Azure page load times are consistent at 25-30 seconds.  I've tested the same code with the same data on our local web server and page load times at 4 seconds.

I'm not finding anything useful in the error log.  Here are the latest entries.
SnapshotHelper::RestoreSnapshotInternal SUCCESS - File.Copy
SnapshotHelper::RestoreSnapshotInternal SUCCESS - process
Native library pre-loader is trying to load native SQLite library "D:\home\site\wwwroot\Bonobo\bin\x86\SQLite.Interop.dll"...
SnapshotHelper::TakeSnapshotTimerCallback
SnapshotHelper::TakeSnapshotInternal - no new files in CodeGen

Bonobo code is the only application in this webapp.  

This has been going on for a couple months now.  Even pushes and pulls are taking a brutally long time.

**Comment by willdean** [comment]
Is SnapshotHelper an Azure thing?  I don't think that's part of Bonobo

**Comment by KY4U** [comment]
Hi Will,

It appears that the SnapshotHelper is an Azure thing.
[http://stackoverflow.com/questions/32253963/what-is-snapshothelper-on-windows-azure](http://stackoverflow.com/questions/32253963/what-is-snapshothelper-on-windows-azure)

I'm not seeing those entries on my local installation.
Kirk

**Comment by KY4U** [comment]
Will,

I'm trying to tack down whether or not the SnapshotHelper is causing this issue.  In the mean time I have attached my error log file.  Perhaps you can find something in there that can point us in the right direction.

Thanks,
Kirk

[Bonobo.Git.Server.Errors.pdf](https://github.com/jakubgarfield/Bonobo-Git-Server/files/236536/Bonobo.Git.Server.Errors.pdf)

**Comment by willdean** [comment]
@KY4U  I don't think there's anything useful in that log, and it's hard to tell if it's the result of an hour's running or a year's anyway.

I think it might be useful to look at which resources are slow to load - perhaps use something like the network view in Chrome developer tools and see if every item is coming in slowly or just a specific one.

* Can you view the /home/diagnostics in Bonobo page (I think we made this local-only, so you probably can't)?
* If you're not logged in, does the log-in page appear promptly?
* Can you load a static file quickly?  (As suggested further up this thread)
* What type of authentication/authorisation setup do you have?

**Comment by KY4U** [comment]
I apologize, I did not see the request to load the static file.  That png image loaded in 537ms.
When not logged in the login page [https://admin.coastalscience.noaa.gov/git](https://admin.coastalscience.noaa.gov/git) loads in ~ 15 seconds.  Most of the time it takes ~ 30 seconds.  Once logged in (forms based authentication) the Repository listing page loads in 26 seconds.  See attached image.
![capture](https://cloud.githubusercontent.com/assets/13239124/14818997/0d027644-0b8e-11e6-9046-0bc105c20bb8.PNG)

If necessary I can provide you with a username and pw for access to the site.

**Comment by RedX2501** [comment]
I will try to create a testcase with many big repos and see where we are taking long.

Can you tell us how many user you have and what kind of authentication you are using?

**Comment by KY4U** [comment]
We have 40 users.  Authentication is forms based using the Internal MembershipService.

Thanks again for looking into this.

**Comment by willdean** [comment]
On every occasion I just loaded the login page, it took just over 10 seconds, which makes me wonder if there's something timing out there each time.  

If you change the repo directory to point to somewhere with no repos, and rename/remove the user database, so that there are no users, does the delay change?

**Comment by KY4U** [comment]
OK.  I've got a sandbox location where I have removed all the repositories.  Now the repository listing page show all those repos as "Missing".  Page load times are still the same.  What is the quickest way to remove the users.  I can copy down the db and remove users from the table if that's what you suggest.

**Comment by willdean** [comment]
Just delete (or move or rename) the bonobo.git.server.db file in App_Data - when the app restarts it will create a new, empty copy.

**Comment by KY4U** [comment]
Starting with no repositories, and removing the db, I reloaded the [sandbox home page ](http://nccos-sandbox-web-kly.azurewebsites.net/git) in 5 seconds.

**Comment by willdean** [comment]
@KY4U  Yes, that's much faster here (much less than 5 seconds)

Obviously that's a different webapp instance to the one we were testing earlier.  Are you able to clearly see that "with DB = 10 seconds, without DB = almost instant"?

How big was the .DB file?
What size Azure webapp are you running?

**Comment by KY4U** [comment]
This is a different web app. I had copied the code, db, and repos from the original webapp.  The sandbox response was the same as the original.  Once I removed the db the load was nearly instant.  Removing the repos did not make a difference in page load times.

DB size is 200kb.  Azure webapp is Standard Small in the Sandbox, Premium 1: Medium in the original webapp.

**Comment by KY4U** [comment]
I came across some table differences between the newly created database and my current database.  See attached images.
![repository_table_differences](https://cloud.githubusercontent.com/assets/13239124/14827354/e58fef5c-0baf-11e6-8a75-91c2acc7c698.PNG)
![user_table_differences](https://cloud.githubusercontent.com/assets/13239124/14827353/e58ed7ac-0baf-11e6-952e-4da1b9eac18c.PNG)

**Comment by KY4U** [comment]
@willdean and @RedX2501 I wanted to let you know what I have discovered.

In my sandbox webapp, I pointed my repository setting path to an empty folder.  I removed the database and reloaded the login page.  Load time was very quick < 1 second.  Now we have just one user and no repositories.  I then changed the repository setting path to my existing repositories (~100).  Settings saved in < 1 second.  Clicked Repositories, which showed no repositories at this time.  Page load < 1 second.  Clicked Rescan directory which took 27 seconds.  Now all my repositories are listed with "Discovered in file system" as the description.  At this point if I do a search, or click on Settings, Users, Teams, or any other link, page load times are 25-30 seconds.

Please advise.

**Comment by willdean** [comment]
@KY4U It just sounds like there's something about Sqlite (or the way we're using it) and Azure which doesn't get on well.  Bonobo is not very highly-tuned with regard to database efficiency, and perhaps it's doing something which interacts badly with Azure's rather unusual I/O arrangements.  

If I get time, I can try to experiment with something here with my Azure account, but don't hold your breath while you're waiting for me.

**Comment by KY4U** [comment]
@willdean Is there some type of file system validation going on?  Meaning, once the repo data is in the database, does Bonobo check to see if the file(s) for the repo are there?

**Comment by RedX2501** [comment]
No, it only checks if the repo is still there (the folder).

**Comment by KY4U** [comment]
It appears that the function GetRepository(Guid id) is called on every page load.  Is that really necessary?

**Comment by willdean** [comment]
@KY4U Thanks for narrowing this down - a number of the bits of database access are grotesquely inefficient, which doesn't tend to matter with small databases on fast filesystems, but clearly is hit by the Azure I/O system.

There is no reason that getting a single repository by Guid (which is the primary key) to be inefficient at all, but some of the 'get all repository' stuff might be subject to improvement, and it's possible we've ended up with some kind of N^2 problem in the 'get all reposistories I'm allowed to see' logic.

How many repositories do you have, out of interest?

**Comment by RedX2501** [comment]
Some time ago i profiled on my local pc and the part that took longest was populating the navigate to repos dropdown.The merging of all i can see with all the I'm admin in took the longest. I had around 1000 repos but no users. It did take about 3 seconds to populate but on first startup what too longest was adding the repos to the db. 

Maybe we can rework that part a bit.

**Comment by willdean** [comment]
@RedX2501 Would you like me to look at this?

**Comment by KY4U** [comment]
@willdean I have ~110 repos.  By removing the droplist, all pages (except repository listing page) load in ~3 seconds, and my repository listing page loads in 9 seconds.  With the droplist, all pages load in ~ 30 seconds.  Until we can figure out what is causing the bottleneck, my suggestion at this point would be to have the droplist displayed only on the repository page.

**Comment by willdean** [comment]
@KY4U Would you be able to change RepositoryPermissionService.GetAllPermittedRepositories to look like this:

```
            var sw = Stopwatch.StartNew();
            try
            {
                return Repository.GetAllRepositories().Where(repo => HasPermission(userId, repo.Id, requiredLevel));
            }
            finally
            {
                Trace.WriteLine("GetAllPerm: " + sw.ElapsedMilliseconds);
            }
```

Then run this on your Azure instance and report the GetAllPerm line from the log file back here.

With 1000 repos I'm only seeing about 12ms here (fast machine, SSD, etc), so before I dive into trying to optimise this, I'd like to be sure that it's this that's slow for you.

**Comment by KY4U** [comment]
@willdean 

The log file shows the following results:
GetAllPerm: 151
GetAllPerm: 126
GetAllPerm: 167
GetAllPerm: 126
GetAllPerm: 195
GetAllPerm: 170
GetAllPerm: 117
GetAllPerm: 112
GetAllPerm: 126

**Comment by willdean** [comment]
@KY4U And that was with a 30s page load time?  So the problem's not there, anyway, it's somewhere else.

**Comment by KY4U** [comment]
@willdean Page load times still 20-30 seconds so I added the timer to the PopulateRepoGoToList function.

PopulateRepoGoToList: 18391
PopulateRepoGoToList: 16075

**Comment by willdean** [comment]
@KY4U Yup, I see it here - well done.  I'll let you know when it's fixed.

**Comment by RedX2501** [comment]
My Profiling showed that it is literally the line with the linq statement that is merging the two lists. I broke it apart and neither sorting nor grouping is the problem.

**Comment by willdean** [comment]
@RedX2501 It's basically the HasPermission calls - it's confusing to profile because of the IEnumerable deferred execution.   The time is all in GetAllPermittedRepositories, it just didn't show up in my suggested stopwatch code, because the loop hasn't been executed at that point.

Hopefully I'll have it sorted shortly, I'm doing it now.

**Comment by willdean** [comment]
@KY4U Could you try the changes to RepositoryPermissionService that are in #561, please?

This is a combination of a 'cheat', to hugely enhance the performance for the system administrator, but also a number of other improvements which should be significant even for other users.

I'm going to continue to look at this, because there's more to come here.

**Comment by KY4U** [comment]
@willdean Very nice!  Page load times 1-3 seconds.  Now that is good work.

**Comment by willdean** [comment]
@KY4U Thanks!  It was me that messed it up in the first place, so it seems right that I should fix it.
