### ISSUE TITLE
Setting up Git 5.2 with AD users in Local Groups

### ISSUE THREAD

**Issue by chasemyaccord** [jakubgarfield/Bonobo-Git-Server#560]
We would like to set up our Bonobo Git Server to use Windows authentication and Active Directory membership (kind of). Here's our predicament:

The Bonobo documentation seems to imply that the member groups specified in the web.config need to be domain groups. All of the developers have user accounts on an enterprise domain, but it is extremely difficult to have enterprise domain groups created for us. It's much easier to go on our on-prem server where Bonobo is installed, create some local groups, and add our users that way. We were hoping to use these local groups in the web.config but Bonobo doesn't seem to like it. We tried the following:

`<appSettings>`
`    ...`
   `    <add key="MembershipService" value="ActiveDirectory" />`
   `    <add key="ActiveDirectoryDefaultDomain" value="ServerFQDN" />`
   `    <add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" />`
   `    <add key="ActiveDirectoryMemberGroupName" value="MyDevTeam" />`
   `    <add key="ActiveDirectoryTeamMapping" value="Project1=Project1Team, Project2=Project2Team" />`
   `    <add key="ActiveDirectoryRoleMapping" value="Administrator=MyAdminTeam" />`
`    ...`
`</appSettings>`

So in the example above, I want to add subsets of our enterprise domain users to local groups MyDevTeam, Project1Team, Project2Team, and MyAdminTeam. ServerFQDN is the domain name of our on-prem server. Is it possible to configure Bonobo to work this way? Again, we really want to avoid getting into the process of creating a bunch of enterprise domain groups since it takes a lot of paperwork and time (for reasons I'll never understand).

Any inputs appreciated! :) Thanks.

**Comment by RedX2501** [comment]
The best solution for you is to use Windows Auth with internal membership. That way  you use Bonobo to manage the groups but the users get to use their regular windows passwords for logging in.
