### ISSUE TITLE
Accessing Git Server

### ISSUE THREAD

**Issue by surgiie** [jakubgarfield/Bonobo-Git-Server#568]
Okay so im fairly new to server stuff so i apologize ahead for any redundancy. So im trying to get the bonobo git server on a development server at the place i work at. This server runs Windows Server 2012 and I get Bonobo Server on it no problem and can access it on there no problem but is there a way this server can be accessed on other computers to clone/push from. When i try to clone a test repository i created on this server i get this

$ git clone http://ipaddress/Git.Server/test.git
Cloning into 'test'...
fatal: unable to access 'http://ipaddress/Git.Server/test.git/': Failed to connect to IPadress port 80: Timed out

so perhaps im confused but how can i clone repos from this development server to my workstation and commit/push back to it?

**Comment by willdean** [comment]
What happens it you go to http://ipaddress/Git.Server in a browser on your remote machine?

Bonobo is just a web application running in IIS, so you should be able to access it from any other machine, provided IIS is working correctly and there are no firewall issues.

Try turning the firewall off on the server temporarily to see if that's the issue - if it is then you'll need to add an exception for port 80.

**Comment by surgiie** [comment]
Hi @willdean  Thanks for replying, im hoping you can help me out with this,

So i turned off the windows firewall on the windows server 2012 computer

**Comment by willdean** [comment]
Can you ping the IP address of the server from the client machine?

**Comment by surgiie** [comment]
No i am not able to:

 PING IP Address

Pinging IP Address with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for IP Address
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

But if i Ping the my workstation ip from the server it seems to do it successfully,

**Comment by RedX2501** [comment]
Configure your Webserver without Bonobo until you can see the welcome screen from the pcs you wish to access the server from. Until this is done we can't help you much. 

Then you install Bonobo and see if it is reachable. Should it not work then please reopen this issue.
