### ISSUE TITLE
Update to the lateste version of git and Bash

### ISSUE THREAD

**Issue by jansor** [jakubgarfield/Bonobo-Git-Server#569]
Hi,

Maybe not really an issue, it would be nice to have the latest version of GIT and Bash inside the next update. currently i experience some issues as we try to use features from GIT v2.8.2 and Bash 4.3
Bonoboo only has Git 1.8 and Bash 3.1

One solution is to update to the latest version, or make bonobo more flexible, by an option to choose the default setting, internal GIT, or by pointing to the system git Location. this would mean that any user can install any version.

**Comment by RedX2501** [comment]
@jakubgarfield What do I need to do to update to the latest version?

**Comment by jakubgarfield** [comment]
I think it is actually configurable as per https://github.com/jakubgarfield/Bonobo-Git-Server/blob/4aad0cd47a27d276ef08d9a0d0f5d45cb8b08263/Bonobo.Git.Server/Global.asax.cs#L163 and it is driven by the value in web.config https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/web.config#L14

For updating the version, you need to download the msysgit executables, replace the existing ones in the AppData folder and test that all git commands works as expected with a few git clients. The reason for not updating this very often are compatibility issues (e.g. Eclipse and IdeaJ git plugins etc.) as I didn't have a lot of time to test it properly.

**Comment by AJH16** [comment]
I looked in to this with a current version, but after making the updates, I end up with protocol errors when trying to fetch.  It seems that something goes wrong with the git-upload-pack and it doesn't actually send the data, just the first line.  Probably something with line endings changed or something similar, but I don't have the time to try to dig in to what is happening at the moment.
