### ISSUE TITLE
Problem with markdown rendering

### ISSUE THREAD

**Issue by lkho** [jakubgarfield/Bonobo-Git-Server#570]
It seems the current markdown library MarkdownDeep is not rendering some of the text correctly, especially code blocks. Would it be better if changed to the CommonMark.NET implementation? Since I think it conforms to the standard and compatible with popular sites such as GitHub.

**Comment by npbenjohnson** [comment]
It would be nice to get this, or atleast an option of markdown providers since the markdown generators I use generally make something more functional and nicer looking with github markdown enabled.

**Comment by RedX2501** [comment]
Can you maybe post some screenshots to evaluate if it is worth the trouble?

**Comment by lkho** [comment]
sample md: https://github.com/mikecao/flight/blob/master/README.md
v5.1.1:
![5 1 1](https://cloud.githubusercontent.com/assets/7780243/16226552/86f02308-37de-11e6-9c1e-8e35e8ed6f88.png)

v6.0.0 up to lkho@607429cb7a56f5f09186fc714233a2c0a73483a2:
![6 0 0](https://cloud.githubusercontent.com/assets/7780243/16226557/8a24d1cc-37de-11e6-90ca-2df878c80d74.png)

**Comment by RedX2501** [comment]
It seems you already have implemented it in your branch, can you create a pull request with the changes? Please also update the changelog file.
