### ISSUE TITLE
Branch permission

### ISSUE THREAD

**Issue by OmidID** [jakubgarfield/Bonobo-Git-Server#572]
Is it possible to grant access to somebody to push only on specific branch or deny to some branch.
For example i would like to give access to all programmer to push dev-* branches and grant access to CTO for master and everywhere.
Also if it's possible to do like this:
Username: omid
Branch to access: dev-omid
Same as pattern "dev-[Username]"

So in this way I can grant access to all programmer to clone master and make their branch. Then our repository are safe and no body can damage final source code.

If it's possible can you suggest me how can I do it?

**Comment by RedX2501** [comment]
You should be able to do this using commit hooks on your repository. It is not the goal of Bonobo to provide fine grained user access controls.
