### ISSUE TITLE
The 5.2 zip from https://bonobogitserver.com/ is incomplete

### ISSUE THREAD

**Issue by m-salazar** [jakubgarfield/Bonobo-Git-Server#575]
It appears some resources are missing from the zip from https://bonobogitserver.com/. For example:
GET 
`https://localhost/Bonobo.Git.Server/Content/components/font-awesome/fonts/fontawesome-webfont.woff2`
is not present, but is present on the 5.2 tag of this repo. 
`https://github.com/jakubgarfield/Bonobo-Git-Server/tree/5.2/Bonobo.Git.Server/Content/components/font-awesome/fonts`
You may wish to adjust this.

**Comment by RedX2501** [comment]
@jakubgarfield Can you check this out?

**Comment by jakubgarfield** [comment]
I published only what was build by the AppVeyor, I'll have a closer look next week when I'm back at my Windows machine.

**Comment by jakubgarfield** [comment]
It looks like the fontawesome-webfont.woff2 is not included in the csproj file.

Would you mind to include it and submit a PR? Also, is there problem with any other file that's not part of the build but should be? The fix will be the same, just include to csproj and it should be part of the release.
