### ISSUE TITLE
5.2 - Domain and back slash causing 404 errors

### ISSUE THREAD

**Issue by kire62** [jakubgarfield/Bonobo-Git-Server#576]
I am using 5.2 with windows authentication. The windows authentication is working, but only if {domain}\{username} is used. So in the database the usernames must be formatted like this. However when this username is placed in the url it is encoded and comes out as {domain}%5c{username}, i.e:

`Account/na%5Ckiresuah/Edit`

This causes a 404 error - I guess because the user na%5Ckiresuah does not exist in the database.

Is there a work around to exclude the domain name and slash? I tried changing it in the sql lite database but our windows authentication will not work without it.

**Comment by RedX2501** [comment]
We are working on providing a 6.0 release which will fix this issue. If you are comfortable with nightly builds you can try  this relesease:

https://ci.appveyor.com/api/buildjobs/dubdgi04r7yc4k39/artifacts/bonobo-git-server-3911399-abb594f8051878c216bf76ea6d1bb491ed09e4d2.zip

**Beware this will update your database to the latest format.**
