### ISSUE TITLE
Bonobo Git Server Detailed Commits Log Listing Available?

### ISSUE THREAD

**Issue by WisconsinWildcat** [jakubgarfield/Bonobo-Git-Server#577]
I would like to get a list of all commits to one repository showing file, author, date, time, and perhaps the comment so I can weed through what needs to go to staging and what needs to be put into the upcoming features list.

Is this already possible?   Spreadsheet or CSV format, XML, anything structured like that would be nice.

Thanks!
RLS

**Comment by willdean** [comment]
You should be able to do this just using normal Git client stuff - see, for example, https://git-scm.com/docs/git-log
