### ISSUE TITLE
jquery 1.4.4 vulnerabilities

### ISSUE THREAD

**Issue by KY4U** [jakubgarfield/Bonobo-Git-Server#586]
My latest scan of Bonobo shows the following issues:

Vulnerable Javascript library
Vulnerability description:  You are using a vulnerable Javascript library. One or more vulnerabilities were reported for this version of the Javascript library.   Detected Javascript library jquery version 1.4.4.
The version was detected from filename, file content.

This vulnerability affects /git/scripts/jquery-1.4.4.js. 

How to fix this vulnerability:  Upgrade to the latest version.

Can jquery be upgraded to the current version 3.1.0 without causing any issues?
Please advise.

**Comment by willdean** [comment]
If you want to try an update yourself, it's probably quicker and easier to update to the latest in the 1.x line, as they're much less likely to cause a problem than going all the way to 3.x

It could be helpful if you said what tool you were running for the scan and what the vulnerability was.

**Comment by KY4U** [comment]
Acunetix Web Vulnerability Scanner v10.5

Vulnerability listed in my original post.

References:
[http://research.insecurelabs.org/jquery/test/](http://research.insecurelabs.org/jquery/test/)
[https://bugs.jquery.com/ticket/9521](https://bugs.jquery.com/ticket/9521l)
[https://bugs.jquery.com/ticket/11290](https://bugs.jquery.com/ticket/11290)
[https://bugs.jquery.com/ticket/2432](https://bugs.jquery.com/ticket/2432)

I'm not sure if these bugs affect this application, but I thought it was worth noting.
