### ISSUE TITLE
What is the links for? 

### ISSUE THREAD

**Issue by iamkarlson** [jakubgarfield/Bonobo-Git-Server#590]
What is a linkify? What is a purpose of that? I haven't found answer in code and in documentation..

**Comment by RedX2501** [comment]
What links are you talking about? Can you post a picture?

**Comment by iamkarlson** [comment]
![screenshot_0804](https://cloud.githubusercontent.com/assets/4534374/17083628/c84fccde-51b7-11e6-89b7-9880ca1daa28.png)

This option in the settings

**Comment by RedX2501** [comment]
Ever notice that when you post an issue/pull request like #80 on Github it will automatically convert to a link? That option is there exactly for this purpose. This allows you to define a regex that the commit text will be matched against and every match will be converted to a link using the url.

**Comment by jotabe-net** [comment]
Working example. If you introduce this information:
Link Regex: `H-\d{1,4}`
Link Url: `http://myissuetracker.com/issue/{0}`

Whenever the text incluse if finds `H-` followed by between 1 and 4 digits, it will generate a link for it. For example.

`Fixes H-123`
would generate the link:
`http://myissuetracker.com/issue/H-123`
