### ISSUE TITLE
Bonobo Git error: “requested url returned error 500”

### ISSUE THREAD

**Issue by lpdourado** [jakubgarfield/Bonobo-Git-Server#593]
Hello,

I need some help with the problem that I cannot solve.

I have a Windows Server 2012 where I have an IIS 8 installed. Also I installed the Bonobo Git Server with my SSL certificate (that I bought, not created).

When I access via browser, using HTTPS everything it's working, I can get the website, logon (on Bonobo), see my certificate correctly, everything, both internal and external access.

The problem it's when I try to make clone of any repository that I have on Bonobo and I always get this error:

"git.exe clone --progress -v "https://<sub.domain>/<repository>.git" "C:\Users\<user>\Desktop\New folder\<repository>"

Cloning into 'C:\Users\<user>\Desktop\New folder\<repository>'...
fatal: unable to access 'https://<sub.domain>/<repository>.git/': The requested URL returned error: 500

git did not exit cleanly (exit code 128) (468 ms @ 7/28/2016 5:44:13 PM)"

I think the problem is some misconfiguration on IIS, because I've tried the same configuration on a Virtual Machine and it's works.

I've already checked the configurations on both Server and Virtual Machine and it's all equal.

Anyone could help me?

Thanks

**Comment by willdean** [comment]
https:///.git/ can't be a real reposistory URL, because there's no domain name and no repository name.

Where are you getting that URL from?

**Comment by lpdourado** [comment]
Hello,
I was my mistake when I create this post. It's missing the subdomain and the domain.
But, I've already solve the problem.

I create a new Bonobo installation on IIS server and now it's working fine.
Probably there was some file in Bonobo's folder with some error or missing.

Thank you for your help.
