### ISSUE TITLE
Blank Page after fresh Bonobo.Git.Server installation on IIS8

### ISSUE THREAD

**Issue by david-bla** [jakubgarfield/Bonobo-Git-Server#596]
Hi, my system is a Windows Server2012 running IIS8.
I downloaded Bonobo.Git.Server from GitHub and followed the instructions...
Checked the Prerequisites, Copy and Decompress files to /inetpub/.
Changed Permissions, convert to application enable auth.. and ive a blank page if i connect to localhost/Bonobo.Git.Server (just firefox) in real i got Status 403.
The IE shows this error.
If i dieable the Authentication on IIS menu i get about 17 requests with 302 error and after that one 404.
And a really huge url due to much redirects the url is:
`http://localhost/Bonobo.Git.Server/Home/LogOn?ReturnUrl=%2FBonobo.Git.Server%2FHome%2FLogOn%3FReturnUrl%3D%252FBonobo.Git.Server%252FHome%252FLogOn%253FReturnUrl%253D%25252FBonobo.Git.Server%25252FHome%25252FLogOn%25253FReturnUrl%25253D%2525252FBonobo.Git.Server%2525252FHome%2525252FLogOn%2525253FReturnUrl%2525253D%252525252FBonobo.Git.Server%252525252FHome%252525252FLogOn%252525253FReturnUrl%252525253D%25252525252FBonobo.Git.Server%25252525252FHome%25252525252FLogOn%25252525253FReturnUrl%25252525253D%2525252525252FBonobo.Git.Server%2525252525252FHome%2525252525252FLogOn%2525252525253FReturnUrl%2525252525253D%252525252525252FBonobo.Git.Server%252525252525252FHome%252525252525252FLogOn%252525252525253FReturnUrl%252525252525253D%25252525252525252FBonobo.Git.Server%25252525252525252FHome%25252525252525252FLogOn%25252525252525253FReturnUrl%25252525252525253D%2525252525252525252FBonobo.Git.Server%2525252525252525252FHome%2525252525252525252FLogOn%2525252525252525253FReturnUrl%2525252525252525253D%252525252525252525252FBonobo.Git.Server%252525252525252525252FHome%252525252525252525252FLogOn%252525252525252525253FReturnUrl%252525252525252525253D%25252525252525252525252FBonobo.Git.Server%25252525252525252525252FHome%25252525252525252525252FLogOn%25252525252525252525253FReturnUrl%25252525252525252525253D%2525252525252525252525252FBonobo.Git.Server%2525252525252525252525252FHome%2525252525252525252525252FLogOn%2525252525252525252525253FReturnUrl%2525252525252525252525253D%252525252525252525252525252FBonobo.Git.Server%252525252525252525252525252FHome%252525252525252525252525252FLogOn%252525252525252525252525253FReturnUrl%252525252525252525252525253D%25252525252525252525252525252FBonobo.Git.Server%25252525252525252525252525252FHome%25252525252525252525252525252FLogOn%25252525252525252525252525253FReturnUrl%25252525252525252525252525253D%2525252525252525252525252525252FBonobo.Git.Server%2525252525252525252525252525252FHome%2525252525252525252525252525252FLogOn%2525252525252525252525252525253FReturnUrl%2525252525252525252525252525253D%252525252525252525252525252525252FBonobo.Git.Server%252525252525252525252525252525252F`

the decoded url is:
`http://localhost/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/Home/LogOn?ReturnUrl=/Bonobo.Git.Server/`

...really crazy

i tried to find some logfiles but the iis file just shows the connections..
the Bonobo.Git.Server.Errors.log shows just these line: (every restart it appends this line)
`Native library pre-loader is trying to load native SQLite library "C:\inetpub\wwwroot\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll`"...

i hope some of you re able to help me solving this wired issue...

**Comment by softlion** [comment]
I have the exact same config and it works out of the box. Check the windows events logs for details of this failure, and fix it.

**Comment by david-bla** [comment]
there are no logs @ windows eventlog :/
this IIS runs also PHP ...maybe this could be an issue..
the iis logfile shows just the connection.. maybe run a dedicated (new) server for bonobgit or go to unix and using gitlab would be better... but id like to solve this isue anyway.....

**Comment by willdean** [comment]
http://localhost/Bonobo.Git.Server this doesn't look like a sensible base URL - you're possibly tripping over some of the rules about dots in IIS paths.

I'm afraid I'm going to close this because it's beyond the limited resources of the Bonobo devs to help with every possible IIS setup issue.

**Comment by gaelj** [comment]
> http://localhost/Bonobo.Git.Server this doesn't look like a sensible base URL 

it's the default URL that you guys defined....

**Comment by willdean** [comment]
@gaelj The URL is an IIS setup thing.   Don't wade into pointlessly insulting people who might be trying to offer free help.
