### ISSUE TITLE
Prevent Git history re-writes with denyNonFastForwards

### ISSUE THREAD

**Issue by flaviocarmo** [jakubgarfield/Bonobo-Git-Server#597]
Hi, some users on my server manage to rewrite the commit history by doing a `git push --force` . Searching on the git docs, i found on [Git Book](https://git-scm.com/book/ch8-1.html) that to prevent this, the following setting is needed on the git server:

`git config --system receive.denyNonFastForwards true`

If i run this on the server machine, it will change the git client config, right? 

How can i do this on Bonobo? i cant found a git.config file for the bonoboserver?

Thansk

**Comment by willdean** [comment]
I think you should just be able to run this on the server which is running Bonobo, and then it will affect actions which take place on that server.    If you've tried this and it didn't work, please come back and reopen this.
