### ISSUE TITLE
I have a few questions.

### ISSUE THREAD

**Issue by jvmbatista** [jakubgarfield/Bonobo-Git-Server#599]
Hi all, I've been using the server for a while now but I have a few questions that I couldn't figure out.

1- Do we have a limit of repositories?
 - We might need something like 50/60 repositories for starters.

2- How to set up users permissions?
 - I need to setup Users/Teams permissions in a read/write manner. Something like Dev and Dev(ReadOnly). This would be done either via repository or Team.

3- Where can I find the users that accessed a repository that have the anonymous option enabled(since that they have to use the account details when checking out a repository)?

Best Regards
João

**Comment by willdean** [comment]
1 - No, there's no limit
2 - I don't think you can do that - the latest version at GH which isn't quite released yet might have better options there
3 - There's no logging like that in Bonobo
