### ISSUE TITLE
Cannot work after install it by follow installation tutorial : WIN 10/VS2015

### ISSUE THREAD

**Issue by CTotophe** [jakubgarfield/Bonobo-Git-Server#604]
Hi!

I am trying to run bonobo git server on my win 10. I have already install VS 2015 and IIS tools. 
I converted the 5.2.0 zip to an application. But I run http://localhost/Bonobo.Git.Server, I have a blank page with no error. 
I have any idea. 

Thanks for your help.

**Comment by willdean** [comment]
@CTotophe It's a bit beyond the developers on the project to be able to help with general IIS setup issues - you'll need to find a basic guide on getting ASP.Net applications running under IIS.

You shouldn't need Visual Studio to get Bonobo running, and that's a very complex tool if you're not familiar with it.

You might find that running `dism /online /enable-feature /featurename:NetFx4Extended-ASPNET45` at a Administrator command prompt helps, but I think probably you've got something simple wrong in the IIS setup.

**Comment by CTotophe** [comment]
@willdean I understand, I think too that the problem is IIS config. I will continue to search.

I know that Bonobo shouldn't need Visual Studio. I would like work visual studio and GIT. Actually, I work with subversion.

Thank @willdean

**Comment by CTotophe** [comment]
@willdean I understand, I think too that the problem is IIS config. I will continue to search.

I know that Bonobo shouldn't need Visual Studio. I would like work visual studio and GIT. Actually, I work with subversion.

Thank @willdean

**Comment by CTotophe** [comment]
@willdean I resolved my problem, I reinstall all IIS components.

Thanks :)

**Comment by willdean** [comment]
Cool!  Thanks for letting us know
