### ISSUE TITLE
Images previews are not available

### ISSUE THREAD

**Issue by cantabria** [jakubgarfield/Bonobo-Git-Server#610]
After update to last build, when I browse a repository, previews  of image files are not available.
Even if the "src" attribute value is set, the <img> tag shows only the value of "alt" attribute (filename). 

As I can see, on GET request ('/Bonobo.Git.Server/Repository/Raw?encodedPath=images%2Ficon.png'), the Bonobo.Git.Server returns only an 'HTTP/1.1 302 Found'.

The dowload anchor works correctly.

**Comment by lkho** [comment]
this is a routing bug since /Repository/Raw?encodedPath=... does not have the tree/repo ID inside the url, so it redirects to the /Repository/Index.

pr #613 should be fixing such routing bugs and also some image preview problem.

**Comment by willdean** [comment]
I couldn't merge #613 as-is right now, but I took the fix for this specific issue and committed it in 0c3ae5d.
