### ISSUE TITLE
404 on browsing to *.git within app

### ISSUE THREAD

**Issue by djjohnjosephuk** [jakubgarfield/Bonobo-Git-Server#612]
Browsing to any of the repository URLs ('General URL' from the repository details page) with the .git extension gives a 404. Committing and pushing to that URL from git commands is fine, it's just browsing to the URL within the app that doesn't work.

I've tried adding .git as a file extension within IIS but this did't do anything. The 404 is handled by bonobo rather than IIS so i'm hoping there's a simple setup missing.

There is nothing in the logs apart from the SQLIte native library loading error which from what I have read is not related.

Any ideas?

**Comment by willdean** [comment]
You can't browse to the Git URLs, they're just intended to be for use with the Git http protocol.

I don't think this is considered to be a bug (it doesn't stop you doing anything), but it's probably an opportunity for improvement.

See #449 for some past discussion of this.
