### ISSUE TITLE
Repository directory in network mapping.

### ISSUE THREAD

**Issue by holiiveira** [jakubgarfield/Bonobo-Git-Server#620]
In the repositories directory configuration, I'm having trouble using a directory that is mapped to the network, for example: `Z:\repoTest`

I tried configuring my application pool with a user who allowed access to the mapping, but I was not successful.

There may be other settings that I do not know or `Directory.Exists` does not work well with network mapping.

Note: If I use an absolute path, everything happens perfectly.
Example: `\\192.168.0.10\repo\repoTest`

**Comment by mauricio-sonegatti** [comment]
As far as I know... in windows the mapped network drives are linked to the current user, software that run in form of services can´t use that directory.
Same principle may apply to bonobo running from iis, but I digress.

**Comment by willdean** [comment]
Instead of an explicit IP address, could you live with a UNC path to a named server instead?  \\servername\share\...?

**Comment by holiiveira** [comment]
Yes, I can use it. It's just that I was curious about not working on a mapped network drive. I thought I might have failed in some configuration.

Thanks for the feedback.
