### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by martinrotter** [jakubgarfield/Bonobo-Git-Server#622]
I followed your install guide to a letter.

Yet, this [shows up](https://snag.gy/UBI9Oj.jpg).

**Comment by holiiveira** [comment]
This is what worked for me:

Windows Server 2012, IIS 8.5. Should work for other versions too.

1. Go to server manager, click add roles and features
2. In the roles section choose: Web Server
2.1. Under Security sub-section choose everything (I excluded digest, IP restrictions and URL authorization as we don't use them)
2.2. Under Application Development choose .NET Extensibility 4.5, ASP.NET 4.5 and both ISAPI entries
3. In the features section choose: .NET 4.5, ASP.NET 4.5
4. In the web server section choose: Web Server (all), Management Tools (IIS Management Console and Management Service), Windows Authentication - if you are using any of it.

**Comment by willdean** [comment]
@holiiveira's comment is almost certainly on the right lines - here's similar info from SO:

http://stackoverflow.com/questions/9794985/iis-this-configuration-section-cannot-be-used-at-this-path-configuration-lock

I'm going to close this - reopen it if you're still having problems.
