### ISSUE TITLE
Tree listing shows only first 5 commit messages

### ISSUE THREAD

**Issue by KY4U** [jakubgarfield/Bonobo-Git-Server#630]
When browsing a repository that contains more than five folders / files, only the first five listings will show the commit message and commit date.

I'm using the latest code from the master branch.

![image](https://cloud.githubusercontent.com/assets/13239124/21184294/cec93702-c1d9-11e6-8933-1f5f260c2346.png)

**Comment by willdean** [comment]
Sorry to say that this doesn't repro here.

Those messages / dates should come from an AJAX request to http://[server]/Repository/Tree/[repo guid] - if you just do an ordinary browser GET on that URL you get the page without the details, then the page itself requests it again, and the AJAX request is served up with the details in it.  (Not my idea...)

Would you mind having a look at the AJAX request with your browser's dev tools, and see if all the messages/dates are correctly included - if they are, then it's a client-side problem, if they're not it's a server-side problem.

There may also be something in the data which is causing the browser to choke - this may be apparent if you have the browser dev-tools console open while fetching the page.

**Comment by KY4U** [comment]
I was able to reproduce on my end.  When browsing a repo, a couple commit messages are displayed, then the dev tools show the following error:

_2261c144-afc8-4b7a-96cd-fd73350fbfea?encodedPath=AerialViewer%2FAerialViewer:484 Uncaught TypeError: Cannot read property 'CommitMessage' of undefined
    at HTMLTableRowElement.<anonymous> (2261c144-afc8-4b7a-96cd-fd73350fbfea?encodedPath=AerialViewer%2FAerialViewer:484)
    at Function.each (jquery-1.4.4.js:652)
    at init.each (jquery-1.4.4.js:276)
    at Object.detailsLoaded [as success] (2261c144-afc8-4b7a-96cd-fd73350fbfea?encodedPath=AerialViewer%2FAerialViewer:483)
    at Function.handleSuccess (jquery-1.4.4.js:6168)
    at XMLHttpRequest.xhr.onreadystatechange (jquery-1.4.4.js:6002)_

No other commit messages are shown after the above error occurs.

I found another repo that produced a similar error:

_Uncaught TypeError: Cannot read property 'CommitMessage' of undefined
    at HTMLTableRowElement.<anonymous> ..._

**Comment by willdean** [comment]
For some reason which I'm not able to see at the moment just by looking at the code, it must be serving up a different number of files in the summary information which draws the table to when it serves up the detail.

Would you be able to share any more information which could help here - ideally the repository (could be just the .git directory I think, no actual files), or the JSON which is returned by the AJAX call to the Tree method.  At the very least you could check the Files array in the JSON and see if it has some missing items, or if it just has the first few items and then stops.

Without a repro here it's really hard to know how to proceed.  I have tried various odd/blank commit messages, and it's not that.

**Comment by willdean** [comment]
Having repro'd something which looks very like this, I realise that it's not showing a truncated list of messages, it's showing the messages which belong with the level above in the file hierarchy.

I have just committed a fix for this in 656e58b - once this has built, would you be able to try it?

**Comment by KY4U** [comment]
I have noticed that the commit message shown in the folder / file listing was not always the correct message.  You may be on to something when you said it belonged to the level above.  I look forward to testing this code change.

**Comment by willdean** [comment]
@KY4U I am just making a public fool of myself by committing things onto Master which break the tests...  When I've finished with this then you should be able to try it...

**Comment by KY4U** [comment]
It appears that I'm getting the correct commit messages (thank you), however, there is some serious lag time during the second jquery request for that information.

![image](https://cloud.githubusercontent.com/assets/13239124/22425197/f7e5d434-e6c7-11e6-86b9-d00d65ec386e.png)

![image](https://cloud.githubusercontent.com/assets/13239124/22425219/1152e8ee-e6c8-11e6-92cb-24073918d030.png)

![image](https://cloud.githubusercontent.com/assets/13239124/22425421/ff703856-e6c8-11e6-92f4-3fca77b6c665.png)

Retrieval time for the commit information ranges from 3-30+ seconds.  I haven't determined a contributing factor for the range difference.

**Comment by willdean** [comment]
I think it's the length of time which that operation can take which lead to someone in the past splitting it into the separate page request followed by an AJAX request to get the details.

I don't fully understand `GetTreeModelsWithDetails`, but I can believe it has some sort of n^2-ish behaviour, perhaps if you have a directory with a large entries of files that is the child of a directory with a large number of entries?

I can't find anything here which looks slow as I browse through it - do you see any relationship between the size of directories and the delays?

**Comment by KY4U** [comment]
I thought that to be the case but here are some stats:

- 4 subdirs and 3 files: 5 seconds (60 commits in repo)
- 11 subdirs and 20 files: 6 seconds (60 commits in repo)
- 0 subirs and 20 files: 1.5 seconds (60 commits in repo)
- 9 subdirs and 60 files: 1.5 seconds  (3 commits in repo)
- 1 subdir and 1 file: 6 seconds (660 commits in repo)
- 4 subdirs and 4 files: 9.5 seconds (660 commits in repo)
- 6 subdirs and 60 files: 15 seconds (660 commits in repo)
- 20 subdirs and 50 files: 6 seconds (70 commits in repo)
- 1 subdir and 20 files: 12 seconds (160 commits in repo)

So far nothing is jumping out at me that might be causing the delay.  I was leaning towards the number of commits in the repo but my results aren't remaining consistent.

**Comment by willdean** [comment]
@KY4U Those are hardly large repos/directories...

I think the only thing to do would be to run a profiler or at least add some StopWatch prints to GetTreeModelsWithDetails to see where the time's going.  

I don't ever see anything more than a couple of seconds delay here.

**Comment by KY4U** [comment]
I'll poke around a bit with the code to see if I can narrow down the issue.  The main hurdle seems to be cleared.  The commit messages are displaying correctly, albeit somewhat slowly at times.  That could easily be something on our end.

**Comment by willdean** [comment]
Time for an SSD...
