### ISSUE TITLE
403 error while trying to clone the repository using git bash

### ISSUE THREAD

**Issue by sanjoo88** [jakubgarfield/Bonobo-Git-Server#631]
I have installed the latest version of bonobogitserver. Configured everything as instructed. I can create repository from the bonobogitserver UI. But when I am trying to push any changes or clone the repository using GIT bash I am getting 403 error. I am trying to configure it in a azure windows server 2016 on IIS. 

![image](https://cloud.githubusercontent.com/assets/18001913/21324201/c821bf52-c646-11e6-9ff4-3baeeaead464.png)

Is there any port I need to allow or something. While I was testing I disabled the Windows firewall on the server. Also the Anonymous Authentication is allowed on the website as well. Please suggest me if I am doing anything wrong or  I am missing anything.

Thanks in advanced

**Comment by holiiveira** [comment]
I tested in my environment: Server 2008 R2 and IIS 7.
Latest version of Bonobo. It worked normally.

Make sure it is not some proxy setting.

**Comment by sanjoo88** [comment]
Yes I think you are right.. It was because of the proxy setting..
