### ISSUE TITLE
In Repository/Clone.cshtml, CheckBoxListFor Error

### ISSUE THREAD

**Issue by TomLan** [jakubgarfield/Bonobo-Git-Server#636]
When I visit Repository page and click Clone page,which always shows 500 Server Error. 
Then I found out in Clone.cshtml, CheckBoxListFor shows 'error'

http://imgur.com/a/YU0Ix

**Comment by willdean** [comment]
@TomLan - Not sure quite what version of the code you have there, and I don't see a 500 error on that page myself.

However - there were some odd characters in that file which I've now removed, and it was worked on recently, so it may be that you'll be OK if you take the latest version from GitHub.

If not, then to diagnose a 500 error we'd need some information from Bonobo.Git.Server.Errors.log which is in app_data.  A quick way to get a good summary of this info is to go to  http://<my server>/Home/Diagnostics - you can attach the result here.

**Comment by TomLan** [comment]
It' worked now. Thank you!
