### ISSUE TITLE
404 error when project name has dot(.) in blob

### ISSUE THREAD

**Issue by husseinjahan** [jakubgarfield/Bonobo-Git-Server#642]
when we want to see our file (Blob action method in Repository Controller) if project name or other folder in path has dot in their name; we get 404 error.

Path has not dot in the name:
![Ok](http://armandar.com/images/ok.png)

Path has dot in the name:
![Not Ok](http://armandar.com/images/notok.png)

**Comment by willdean** [comment]
What version of Bonobo are you running?  If it's 5.2 or lower, can you try taking the latest from GitHub (take a backup first)

**Comment by husseinjahan** [comment]
thank you @willdean , problem solved by installing latest version. but now blame has the same problem!

**Comment by husseinjahan** [comment]
I changed blob view and change URL for showing blame.

I changed this:
`<a href="@Url.Action("Blame", new { id=ViewBag.ID, encodedName = PathEncoder.Encode(Model.TreeName), encodedPath = PathEncoder.Encode(Model.Path, allowSlash: true)})"><i class="fa fa-comments"></i> @Resources.Repository_Tree_Blame</a>`

to this:
`<a href="@Url.Action("Blame", new { id=ViewBag.ID, encodedPath = PathEncoder.Encode(Model.Path, allowSlash: true)})"><i class="fa fa-comments"></i> @Resources.Repository_Tree_Blame</a>`

**Comment by willdean** [comment]
Does that work for branches other than master - I think you might have broken something else.  Can you post a URL which isn't working?  

'PathEncoder' doesn't suppress dots, and maybe that's the real fix.

**Comment by husseinjahan** [comment]
this url return 404:
http://mydomain.com/Repository/880ee2c3-60b3-4d22-87ca-94dd703f54c4/master/Blame/Echap.Utility/AuthHelpers.cs

**Comment by willdean** [comment]
@husseinjahan I've looked into this a bit more, and the problem doesn't repro here *unless* I turn off `runAllManagedModulesForAllRequests` in web.config.

Can you check that you have `<modules runAllManagedModulesForAllRequests="true">` in web.config.

**Comment by husseinjahan** [comment]
@willdean, I've looked in my web.config and `runAllManagedModulesForAllRequests` was true. I don't think the problem is this :(

When I changed  `runAllManagedModulesForAllRequests` to `false`, Even following address also returns an error:
http://git.armandar.com/Repository/5fd46c97-e268-4679-9125-82ac566e4973/master/Tree/Echap.Utility

**Comment by willdean** [comment]
@husseinjahan Thanks for trying that.

Although I don't really understand how it would cause your problem, you are correct that there is a problem with the Blame page, and I have just pushed some revisions to that a minute ago - when they're built you could try them.
