### ISSUE TITLE
Extreme Difficulties in IIS

### ISSUE THREAD

**Issue by bendavidbp** [jakubgarfield/Bonobo-Git-Server#643]
Hi Jakub,

I've been having an infuriating time attempting to get Bonobo to work, so I thought I'd reach out to you here.  The situation: We have two programmers on two network machines running Windows 7, we are also running two Windows Server 2012 R2/IIS VM's on the network - one "development" machine and one "deployment" machine for the purpose of developing an internal web-app.  I am attempting to allow the programmers to code on their individual machines, push the changes to the "production" machine, and any finalized changes will be pushed to the "deployment" machine.  Looking for a git server that works on IIS Bonobo seemed like the ideal fit, but I'm having a hell of a time getting it to work.

I installed Bonobo on both the "Production" VM/machine and the "Deployment" machine.  On each machine individually everything appears to be working fine - I can login admin admin on localhost and create/delete repositories from the web interface or from the command link.  I want to clone the repo on the "Production" machine - which I've called TestRepo.git - onto the "Deployment" machine.  When I use "git remote add [alias] http://[ipaddress]/Bonobo.Git.Server/TestRepo.git" I get the error "Not a git repository <or any of the parent directories>: .git".   I've tried innumerable variations on the syntax there and none of them has worked.  Any help would be greatly appreciated - I've been tearing my hair out for days over this and the documentation is silent on why this may be occurring.

**Comment by willdean** [comment]
@bendavidbp You cannot escape me by moving from SO to GitHub :-)    

Before you do anything else with the git client, make sure:

1. You can get Bonobo up in a web browser on your server machine (I think you can)
2. You can get Bonobo up in a web browser on a remote machine (I am not sure you've got this working).

If you're not getting '2' working, then there is no hope of setting up a git remote, as git is going to use exactly the same mechanism to connect to Bonobo as the web browser is.

It's terribly difficult to document how to make this stuff work, because there are about 100 million ways to fail to set up a asp.net application on IIS so that it works properly - ASP.Net, IIS and Windows Server are all immensely complex and documenting/supporting every possible problem is beyond the capabilities of the tiny handful of people who work on Bonobo.

All I can say is that, once you get it working, Bonobo works absolutely fine as Git server, so it's worth you persisting at this point.

**Comment by bendavidbp** [comment]
*Laughing*  Now that's the first time THAT's happened.  Lol.  I leave work in two minutes and will be coming back first thing tomorrow to get this figured out...thanks for the help so far.  I think it may have something to do with the bindings.  The IP I was using was bound to another folder in IIS, which would explain why the .git "file" wasn't found.  But I just tried to bind the Bonobo.Git.Server app to an ip, but there is no "Bindings" hyperlink in the right hand menu through which I can do so.

**Comment by willdean** [comment]
@bendavidbp Sounds like you're getting there - like I say, treat it as getting a web application to work with a web browser first (local and remote), and only once you've got to that point then try it with git.

If you have specific IPs already bound to other apps, you might be able to just set the default binding to point to Bonobo?

**Comment by bendavidbp** [comment]
Hi Will,

No problem, I didn't think you were stalking or anything, it was actually kind of a fun surprise.  I'm going to keep this thread updated as I go in case anyone else has the same difficulties.  I had bound the IP address of the server to a sub-folder of the wwwroot directory - we were intending on placing the website we're developing in that folder, but it can still be accessed even if the wwwroot directory is the main "website", so I removed the sub-folder "website" (not the folder itself, but it's representation as a website in the IIS Manager) and re-bound the IP address to the "Default Web Site" connection that was the superfolder of Bonobo.Git.Server.   I can now access the Bonobo.Git.Server web page with the IP address from the other computer, the initial website we were creating is still accessible as a subdirectory on the IP instead of being bound to the IP itself, which works fine for us.  

I haven't attempted command line git yet and have a meeting, but I will do so in a bit and report back here with the results.

Kind Regards,
James

**Comment by bendavidbp** [comment]
Awesome, it's working!  Just cloned the repo on the deployment machine onto the production machine.  Thanks for all of your help, Will Dean, that tip about using the browser really did the trick for me - once I got the 404 error and remembered that the URL was actually pointed to a sub-directory the breadcrumbs lead back to what was bound where.

Thanks again, I will update Slashdot as well and accept your answer there and add a comment to further explain the solution.

**Comment by bendavidbp** [comment]
Sorry, meant Stackoverflow.

**Comment by willdean** [comment]
Glad it's working - if you're running Bonobo 5.2 then you should try the not-quite-released 6.0 which you can get from the latest built at AppVeyor.  It has loads of new stuff, and lots of bugfixes, and the only reason we're holding of releasing it is some stuff to do with upgrades for people with less common configs.

I'll close this now, but it's here if anyone finds it useful in future.
