### ISSUE TITLE
Bonobo Git Not Reading Command Line Initialized Repositories

### ISSUE THREAD

**Issue by bendavidbp** [jakubgarfield/Bonobo-Git-Server#646]
I've tried a few ways to bring some newly created repositories into the Bonobo.Git.Server/App_Data/Repositories folder and none seem to work.

At first I simply copied a repo folder from another directory.  Bonobo didn't recognize anything was added to the Repositories directory.  I then attempted to create a git repository from the command line inside the Bonobo.Git.Server folder and Bonobo didn't recognize anything was added to the Repositories directory.

How can I create new repositories for Bonobo to track without using the web interface?  I primarily started with Bonobo so we could push and pull to git from various machines on our network, but I'd rather not be forced into using the interface and far prefer being able to just use git on the command line and have bonobo function just as the connective tissue.

**Comment by willdean** [comment]
@bendavidbp The situation is as follows:

* Bonobo <=5.2 only scans the repo directory for new repos when it starts up - so your manual creations do work, they just haven't been picked-up by Bonobo yet.  Perhaps you could do an `iisreset` from the command line after adding new repos, if that's compatible with other uses of the server 
* Bonobo >=6.0 (you can get this from the AppVeyor artifacts) adds a 'rescan' button to the repository web page which lets it find repos without restarting, but this doesn't really help you avoid the web interface (#454)
* But, more usefully, Bonobo >= 6.0 lets you push a non-existent repo and have it created - see #504, #460, #376

**Comment by bendavidbp** [comment]
Thanks, Will Dean!  I came in this morning and they were sitting there after I logged back in.  Guess I should've applied the "Did you restart your computer?" practice. 

Thanks for the link to the 6.0 builds.  I'm not entirely sure if it's a good idea for me to get into leading edge builds at this point, I'd like to get the hang of 5.2, but am seriously considering it.

Thanks again!

**Comment by willdean** [comment]
@bendavidbp If I were you I'd go to 6.0 now, as it has loads of new features/bugfixes, and we're a hairs-breadth off releasing it.  One of the most complex things internally about 6.0 is the database migration from 5.2, so if you go straight to 6.0 now then you'll never have your data go through that.

**Comment by bendavidbp** [comment]
Sounds good, Will.  If I do so will the same installation/documentation instructions work for 6.0 as did for 5.2 - and is there any need to "Uninstall" 5.2 (I guess I would just delete the directory?).

**Comment by bendavidbp** [comment]
I just gutted the folder and re-gutted it with 6.0 - seems to be working!  Thanks again for the info today, I'll see how things workout with 6.0.

Kind Regards,
Ben David

**Comment by bendavidbp** [comment]
Oh, before it worked I needed to re-do the permissions on the App_Data folder (I'm saying this in case anyone reads this and is in the same situation).
