### ISSUE TITLE
Add environment variable to prevent changing settings in demo mode

### ISSUE THREAD

**Issue by jakubgarfield** [jakubgarfield/Bonobo-Git-Server#647]
Some people like to change admin password for demo.bonobogitserver.com and also change header and footer to vulgar messages.

That messes it up for people that would like to see the demo in action. Unfortunately this happens way too often and I have to manually delete the database.

The environment variable needs to be configurable in Azure Website.

<img width="839" alt="screen shot 2017-03-02 at 8 28 55 am" src="https://cloud.githubusercontent.com/assets/194724/23477270/528c8622-ff22-11e6-9e61-e1164d03ca62.png">

**Comment by willdean** [comment]
Can this just be a setting in web.config?

**Comment by jakubgarfield** [comment]
The web.config won't get overridden when doing Azure deployment (via the git integration), right? If that's the case it would be a perfect solution.

Disallow changing admin password and app settings would be sooo helpful.

**Comment by willdean** [comment]
@jakubgarfield Good question - I don't know.  I suspect we could have a web.config.azure which just added the 'Demo' setting.   (I use those web.config modifiers all the time with one-click-deploy, but I'll find out about Azure git deploy)

**Comment by willdean** [comment]
@jakubgarfield See here:  https://weblogs.asp.net/srkirkland/git-deployment-to-an-azure-website-keeping-configuration-secrets

It looks like you can add an AppSettings entry via the Azure portal - this will get added/overwritten to web.config when you deploy.

Could you add one and then let me know the name/value, and I'll do the code to make that effective.

**Comment by jakubgarfield** [comment]
@willdean just added the demoModeActive with a value of true (but it is very easy to change if you find a better name).

**Comment by willdean** [comment]
@jakubgarfield What stuff do we need to forbid in demo mode?

* Changing anything on Settings/Index page
* Changing admin password
* Creating users?  (With abusive names)
* Creating repositories? (With abusive names)

It seems to me that given a sufficiently bored and cretinous teenager, almost anything can be used for abuse.

Should we perhaps have a session mode where nothing persists beyond a single session?

**Comment by jakubgarfield** [comment]
Settings and users password (the admin/admin) is causing the most pain – that happens all the time.

Abusive user names and repositories are not a major issue (I've seen it just once). I wouldn't invest too much time into implementation.

A better solution for that might be purging the AppData folder (database and repos) regularly – which I'm not sure how to do at the moment – maybe a WebJob?

**Comment by willdean** [comment]
@jakubgarfield Would you mind having a look at #648 please and see if it looks like it does what you want.

**Comment by jakubgarfield** [comment]
@willdean brilliant – works like a charm, thank you!
