### ISSUE TITLE
Use visual studio 2017 to clone/pull/push will cause error.

### ISSUE THREAD

**Issue by MaizaLin** [jakubgarfield/Bonobo-Git-Server#657]
Bonobo-Git-Server is worked fine with Tortoise Git client and visual studio 2015, but when I work with  visual studio 2017 it not work ...

Here is vs2017 error message:

Git failed with a fatal error.
fatal: http://xxxxxx/xxxProjects.git/info/refs not valid: is this a git repository?

Here is the error server log:

w3wp.exe Error: 0 : Error occured and caught in Global.asax - System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bonobo.Git.Server.MvcApplication.Application_AcquireRequestState(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Please fix this issue and thanks very much ！！！

**Comment by holiiveira** [comment]
I did some testing and I had no problem.

Which version of Visual Studio are you using?
Which version of Bonobo?

I tested using Bonobo 6.0.0 and Visual Studio 15.0.0+ 26228.9

**Comment by MaizaLin** [comment]
Oh, thanks!!!

And I'm using Bonobo 5.2.0 and Visual Studio 15.0.0+ 26228.9.

As I know the latest version of Bonobo is 5.2.0 ..... (https://bonobogitserver.com/)

Did I missed something ....???

So could you please give me a link for Bonobo 6.0.0  ?   : P

**Comment by holiiveira** [comment]
Not yet officially released. You can make a project fork to test the new features.

Follow this issue: #587

**Comment by larshg** [comment]
You can also dl an artifact from the appveyor build ie. this one is the latest merge to master: https://ci.appveyor.com/project/jakubgarfield/bonobo-git-server/build/513/artifacts

**Comment by MaizaLin** [comment]
Thanks all and have a good day. : )
