### ISSUE TITLE
GitAuthorizeAttribute throws exception if auth header is malformed

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#664]
`GitAuthorizeAttribute.IsUserAuthorized` assumes that the auth header will contain a value which has username/password separated by a colon.

When a broken client (or proxy, perhaps) passes in an auth header which *doesn't* contain a colon, a `String.Substring` call fails with an argument exception.

This would never happen with a properly formed token, but it seems to me we should check for a colon and if it's not there, just fail the auth.

It's not the main problem in #659 (that looks like a client problem) but it was noticed there (tagging @larshg too for comment)

**Comment by larshg** [comment]
Indeed if the `value.IndexOf(':')` in `value.Substring(0, value.IndexOf(':'))` returns -1 the substring part will throw an arugmentoutofboundexception.

So a simple check for existence of : .

Also if : is used in username or password we should also be able to handle this? or do we block this during creation?
