### ISSUE TITLE
Windows authentication with internal membership service failed

### ISSUE THREAD

**Issue by aPSopt** [jakubgarfield/Bonobo-Git-Server#668]
For details see [http://stackoverflow.com/questions/43293352/bonobo-git-server-authentication-failed-why](http://stackoverflow.com/questions/43293352/bonobo-git-server-authentication-failed-why)
I download and install Bonobo Git Server (6.0.0.532). I add the App_Data folder permissions and I have IIS authentication settings as described in the installation notes - [https://bonobogitserver.com/install/](https://bonobogitserver.com/install/)
I create the user (login: qqq, pass: qqq) and try to clone repository with this user.
But I see authentication failed error all time.

I look in the config and see, that there are turn on internal membership service - it is default behaviour of the bonobo git server. But it is not works. So this is the bug of the bonobo git server or bad documentation.

**Comment by brianhv** [comment]
I'm also experiencing this behavior.

I initially attempted to upgrade from 3.4, and cloning failed. Thinking it was an issue with the upgrade, I then installed 6.0 in a fresh directory and just enabled Windows authentication (via web.config, not via IIS authentication). Cloning still failed no matter how I specified the username.

I went one step further and tried with a completely stock 6.0, with the default cookie authentication. I created a new repository and a new user, giving the new user access to the repository. The new user successfully logs in through the web interface, but fails to clone the repository with an uninformative 401.

This is currently running on Windows Server 2008, IIS 7.5.

**Comment by brianhv** [comment]
This appears to have similarities to #567, which is somewhat old but unfortunately lacking a solution.

**Comment by willdean** [comment]
@brianhv Assuming you're using a normal sort of command line Git client, when you do:

`git clone <git repo>`, do you get asked for credentials?  Or does some credentials helper supply them without asking you?

If it's the latter, could you try disabling that (it's probably configured in your global .gitconfig file in your home directory) and see what happens?

**Comment by brianhv** [comment]
I do get asked for credentials. I've tried providing the username as `brianhv` (as I do through the web), and as `domain\brianhv` (the way the user is displayed in the web interface). The result in both cases has been the terse `fatal:  Authentication failed` message as shown in @aPSopt's stackoverflow post.

At this point I've downgraded back to 3.4 and it's working for now. And it turns out that this time, 6.0 with cookie auth is working; it's only windows authentication mode that fails from the git client. (Which for me is a macOS command-line client.)

Here's an interesting data point. I created a test user while I was set to the Cookies authentication provider, and successfully cloned with it. Then I switched to the Windows authentication provider. Now I can log into the web interface (via a basic auth dialog) with my Windows account. However, the test user can still successfully clone even though it can't log into the web interface.

Is there some way the git request could be using a different authentication mode than the web interface?

**Comment by willdean** [comment]
@brianhv I'm afraid I've lost track of what does and doesn't work for you now.   Earlier you said a clean install of 6.0 didn't work at all using default settings, but now you're saying it does work, is that right?  What was the difference between the two situations?

The git client doesn't use the same auth code as the web interface (for example, Git doesn't use cookies), so it's entirely possible for their to be bugs in one bit and not the other (it seems pretty much a certainty that there's a problem with using Windows auth for Git actions).

I am not the one responsible for the preposterous combination of auth options in Bonobo (no one person is, to be fair), but unless you're willing to look into it yourself, then I'm quite possibly your only hope of getting it fixed at the moment, so you may need to be patient.

I would not recommend that you run 3.4 on a public facing website, if that's what you're currently doing.

**Comment by brianhv** [comment]
It's totally fair to have lost track. It's been a confusing couple of days.

Yesterday, 6.0 never let me clone. Today it does, but only as a non-Windows user account. What changed between yesterday and today? Who knows. I did it again and it worked.

The server is not public-facing. I'd still rather upgrade, but I should be ok for now.

Here's the summary at the moment.

**WIth Cookies authentication mode**

 . | Cookie user | Windows user
-|-------------|------------
Can log into web | Yes | No
Can clone | Yes | No

**WIth Windows authentication mode**

 . | Cookie user | Windows user
-|-------------|------------
Can log into web | No | Yes
Can clone | Yes | No

If there's anything I can do to help diagnose further, I'd be happy to do what I can. I'm not sure how soon I'll have time for a full-on source dive, but I'll see what I can do.

**Comment by willdean** [comment]
@brianhv You have spurred me into sorting out the crapulous logging in Bonobo - this won't of itself fix your problem, but should help.

When there is a build with some more logging in (a sort of provisional 6.1), I will ask you to try that.

**Comment by willdean** [comment]
@aPSopt, @brianhv Would you mind trying the new version from here:

https://ci.appveyor.com/api/buildjobs/6rbxsli3pbpomljf/artifacts/bonobo-git-server-8005633-c48499cda83b14b8d58b80b5c84ee117b8a1d0be.zip

This has two main changes:

* Lots of new logging into app_data/logs which might help us help you
* A reversion of a change to the way Git URLs are authenticated with Windows auth.

**Comment by brianhv** [comment]
With this build, the bad news is that my git client is still saying that authentication failed. The good news is that a lot of other things seem to be correct.

When Windows authentication is enabled and I try to clone with my Cookies account, it fails. This is different than in the released 6.0, and I believe the correct behavior.

When I attempt to clone with my Windows user with an *incorrect* password, I get a log message of
> `﻿﻿2017-04-11 17:22:50.844 -04:00 [Warning] GitAuthWin: Couldn't valudate user "brianhv" in domain "APPLICATIONS"`

When I attempt to clone with my Windows user with a *correct* password, I get:
> `2017-04-11 17:22:56.625 -04:00 [Information] GitAuthWin: Validated user "brianhv" in domain "APPLICATIONS"`

So it looks like the authentication is mostly working, but for some reason the success isn't getting passed through to the front end.

Thank you for looking into this so quickly!

**Comment by willdean** [comment]
@brianhv Thanks for testing.    The bit that I 'fixed' and annotated with the new logging stuff was the initial authentication which applies to all Git accesses, irrespective of anything to do with the repository.   So it looks likes it's approved you as a user, but then denied you access to the specific repo.  

I'll annotate that next.

I have never been able to understand the use case for Windows Auth with internal membership - it's always seemed to me to make no sense, given that you have to manually maintain the internal membership database matching your domain, but clearly someone wanted it enough to code it up at some time, and people do seem to want to use it.

Out of interest, why are you running like this, and why don't you want to / can't you use AD membership?

**Comment by brianhv** [comment]
I have a small number of users (fiveish) and pretty much all of our development tools use the same credentials. So the internal membership database maintenance is minimal, and just flipping a config file setting seemed like a really easy way use those credentials for this as well.

I did notice the recommendation to use the Active Directory Membership Service in the docs. The first thing that stopped me from pursuing it was the need to create Active Directory groups, something which I assumed I'd need to bug my administrator about, and he has enough to do without me bugging him about stuff that we're not yet using for our main projects.

Even if I had overcome that, there were several other options I needed to figure out, and the documentation struck me as terse. For example, it says, "Next, set the ActiveDirectoryMemberGroupName to the name of the members group you created earlier." I looked up to try to find the phrase "members group" and couldn't, and realized I'd need to fully read and not just scan to figure out what to do. It also looks like I'd need to deal with teams, which I'm not currently doing. If some of those things are optional, it's not indicated.

I'll fully admit to laziness here. It might be a matter of spending 5 minutes learning more about AD and reading the existing documentation carefully. But compared to the seemingly simple solution of changing `Cookies` to `Windows`, laziness won.

Is the documentation in source control somewhere? I might be able to take a shot at making that page more scannable if you'd find that valuable.

**Comment by willdean** [comment]
@brianhv Thanks for that - I hope we can make it work for you...  I have just pushed some more logging to that branch, so there'll be a new version to try shortly.

I agree the documentation isn't great, although I think do think brevity is a great quality in documentation!I think some of it was written by people for whom English is not their first language, so if you want to have a go at improving it then please do.  The minimum AD setup is actually very simple - create a group in AD into which you put *everyone* who uses Bonobo (that's the "Members Group") and create another group in AD into which you put those who need to be Bonobo Admins.  The team stuff is optional.

The documentation is in a different GH repo:  https://github.com/jakubgarfield/Bonobo-Git-Server-web - I can take a PR on that repo.

I very much appreciate you taking the time to test stuff and report back - it's incredibly useful as the current tiny puddle of developers don't have decent coverage of all the different configuration options, and that makes it very difficult to fix problems.

**Comment by willdean** [comment]
There's another new version at https://ci.appveyor.com/api/buildjobs/06h12cix3cl9lehm/artifacts/bonobo-git-server-8009128-465a33c9209d31938938658eead82c6a68ea21f5.zip

I suspect the changes I made earlier today to the auth were probably wrong, and I will need to revert them and then try and work through the original route with you - when using Windows Auth with Internal membership, I don't think you should have distinct 'Windows' and 'Cookies' users - you should be ensuring that for every Windows user who needs to log in there is a matching internal user (that's a user in the internal membership database, not really a 'cookie' user).

You obviously have a brianhv/APPLICATIONS Windows user - do you also have a 'brianhv' Bonobo user?

**Comment by brianhv** [comment]
When a user first logs in to Bonobo with Windows credentials, Bonobo automatically creates a user of the form `APPLICATIONS/brianhv`. That's the user to which I've been giving repository access, and that's what was working in 3.4. I do not have a separate `brianhv` user. In addition, when my `AuthenticationProvider` is `Windows`, there's no option in the UI to create a new user.

I'll try that build now.

**Comment by brianhv** [comment]
These log messages look interesting.

>`2017-04-11 20:12:38.601 -04:00 [Information] GitAuthWin: Validated user "brianhv" in domain "APPLICATIONS"`
>`2017-04-11 20:12:38.658 -04:00 [Warning] GitC: SecureGetInfoRefs unauth because User 00000000-0000-0000-0000-000000000000 doesn't have permission Pull on  repo "asdf"`

**Comment by willdean** [comment]
@brianhv There's another new version at https://ci.appveyor.com/api/buildjobs/hgnqi0lp9fny8k4v/artifacts/bonobo-git-server-8022989-e0a7c9d038a9e99674a161c3caa195f610d41f99.zip

This has gone back to the 6.0 behaviour (so may be 'worse' in some respects, but I should never have moved away from this before getting to the bottom of what's happening) but adds a load more logging.

It would be great if you could try this one, thanks.

**Comment by brianhv** [comment]
```
2017-04-12 11:49:21.553 -04:00 [Information] GitAuth: No auth header, anon operations not allowed
2017-04-12 11:49:21.606 -04:00 [Information] GitAuth: Trying to auth user "APPLICATIONS\brianhv"
2017-04-12 11:49:21.606 -04:00 [Information] GitAuth: Going to membership service for user "APPLICATIONS\brianhv"
2017-04-12 11:49:21.606 -04:00 [Verbose] EF: Validating user "APPLICATIONS\brianhv"
2017-04-12 11:49:21.611 -04:00 [Verbose] EF: User "applications\brianhv" validation result Failure
2017-04-12 11:49:21.611 -04:00 [Warning] GitAuth: Membership service failed auth for "APPLICATIONS\brianhv"
2017-04-12 11:49:21.611 -04:00 [Warning] GitAuth: User "APPLICATIONS\brianhv" not authorised
```

**Comment by willdean** [comment]
@brianhv Thanks - what happens if you go to a web page?  It should try to create that user.

**Comment by brianhv** [comment]
Yes, the user exists and is able to log into the web interface.

**Comment by willdean** [comment]
@brianhv Is the user in the EF database (i.e. visible in the web interface) called "brianhv" or "APPLICATIONS\brianhv"?

**Comment by brianhv** [comment]
`APPLICATIONS\brianhv`

**Comment by willdean** [comment]
Is it definitely "APPLICATIONS\brianhv" and not "applications\brianhv"?

**Comment by brianhv** [comment]
Apologies, it is indeed lowercase.

**Comment by brianhv** [comment]
Got a little debugging session going myself here. The program flow is getting into `GitAuthorizeAttribute.ValidateUser(username, password)` with correct information. That method successfully grabs the user object from the database. However, `ComparePassword` returns false because `GetSaltedHash(password, salt) == hash` is false.

**Comment by willdean** [comment]
@brianhv Yes, spot-on.   If you look at the history of GitAuthorizeAttribute.cs you'll see that code to authorise Windows users directly (without going to the membership provider) has been put in and taken out about three times.

I put it back in yesterday, and then took it out again today, but clearly the EF membership provider *cannot* authorise the user, because it doesn't have the password.

What needs to happen is somewhere between the two we've have in the last two days - for WinAuth with EF membership, the auth needs some special handling, but for WinAuth with AD then the membership provider CAN do the auth.

For consistency, I think it's better that the membership provider does always do the auth, but when we're using Windows Auth with EF membership, then the EF membership provider needs to do this correctly, not by uselessly peering at its own hashed passwords.

I will have something else to try shortly.

**Comment by willdean** [comment]
@brianhv The incredible yo-yoing auth code is back in GitAuthAttr - if you watch #671 you can wait for the AppVeyor build to finish and then take the binary artifact, or pull that branch directly if you're in source code mode and you don't want to wait for AppVeyor

I think the missing link might have been that the WinAuth code I added yesterday wasn't building the claims ID properly, which is why your log showed we had no user ID further in.

**Comment by brianhv** [comment]
Thanks! I'll keep an eye on it.

I see why this is a challenge. I'm going to muse on this for a moment, and you're welcome to ignore me.

My goal isn't to use the internal membership provider as such. My goal is to authenticate with Windows credentials, and to control access with the internal system.

There are a few different concerns that need to be handled:
- How do we expect authentication to be provided? (Cookies? HTTP Basic?)
- How do we check authentication? (AD? Local database?)
- How do we check what a user is authorized to do? (AD? Local database?)

It appears as though AuthenticationProviders have their hands in all three while MembershipProviders deal with the latter two.

In my perfect world, I'd be able to use a CookieCredentialProvider, a WindowsAuthenticationProvider, and a BonoboAuthorizationProvider. That's way beyond the scope of this ticket, of course, and there may be obstacles that I'm not seeing yet to teasing these classes apart. I wish I had more time to play around with a design like that.

**Comment by larshg** [comment]
Hey all, sorry for not responding before now, but been busy with other stuff :-)

Indeed it seems that I haven't tested this scenario properly.

Out of curiosity when should we use the authentication classes and should these be used instead ie. move the validateUser and perhaps refrase it to authenticateUser?

When the user is authenticated, we can then use the membership provider to get info about what repositories etc is available to the user?

We do use the authentication class to get the user claims(at least in some cases) ?

**Comment by willdean** [comment]
@brianhv It is very complicated and it has evolved in an odd way - "I wouldn't start here" definitely applies.

There isn't a clear separation between authorisation and authentication (Bonobo is not unique in this regard!) - and as you say, 'membership' spans both.   What's particularly confusing (and unhelpful to my mind) is that when you enable AD membership, you get an entirely different backend, which is a home-brew json-based database which has historically been very unreliable.

Like most ASP.Net projects of a certain age (I have a substantial one at work), it's suffered/benefited from a piece-wise/partial migration to OWIN, which doesn't help the clarity of things.

A few of use made a big effort early last year to try and improve the code quality and testing coverage, which has certainly reduced the inconsistency between some of the different auth mechanisms, but the impracticality of any automated test against AD (shame on you MS) has really made it hard to get it right.

**Comment by brianhv** [comment]
I installed the new AppVeyor build, and cloned successfully with a Windows user!

Your "I wouldn't start here" advice and explanation make sense. Thanks for humoring my musing!

**Comment by willdean** [comment]
@brianhv Thanks very much for testing that.

I am tempted to push a 6.1 release, both to get this fix and to get the logging which has been very helpful.

What do you think @larshg?

**Comment by larshg** [comment]
Sure - its better that it works, even though it could use a proper overhaul - but that will properly not happen sometime soon :-P

**Comment by aPSopt** [comment]
Hmm, as I understand something fixed?

But I installed the bonobo 6.1 release and the authentication with internal membership service still failed. The trouble described in the initial post not changed.

**Comment by larshg** [comment]
Please post the printouts from the log file for us to have something to work with.
Are you using windows authentication with internal membership?

**Comment by aPSopt** [comment]
Where logs placed? I found following:
1)  App_Data\Bonobo.Git.Server.Errors.log
> Native library pre-loader is trying to load native SQLite library "C:\inetpub\wwwroot\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll"...

2) App_Data\Logs\log-20170413.txt
> 2017-04-13 16:31:12.973 +03:00 [Information] Bonobo starting
> 2017-04-13 16:36:22.375 +03:00 [Warning] GitAuth: No auth header, anon operations not allowed
> 2017-04-13 16:36:35.024 +03:00 [Warning] GitAuth: No auth header, anon operations not allowed
> 2017-04-13 16:37:49.934 +03:00 [Warning] GitAuth: No auth header, anon operations not allowed
> 2017-04-13 16:37:53.122 +03:00 [Warning] GitAuth: No auth header, anon operations not allowed
> 2017-04-13 16:38:43.309 +03:00 [Warning] GitAuth: No auth header, anon operations not allowed
> 2017-04-13 16:38:47.656 +03:00 [Warning] GitAuth: No auth header, anon operations not allowed
> 2017-04-13 16:52:10.114 +03:00 [Warning] GitAuth: No auth header, anon operations not allowed
> 2017-04-13 16:52:22.180 +03:00 [Warning] GitAuth: No auth header, anon operations not allowed

**Comment by larshg** [comment]
Are you using a credential helper? If you do can you try disable it temporarily? Are you using got bash or another client?

**Comment by aPSopt** [comment]
I am using tortoisegit. How to disable it credential helper?

**Comment by willdean** [comment]
@aPSopt The fix in 6.1 is for people using "Windows Authentication" with "internal membership".  This is not the default configuration, so if you have not change web.config, then you won't be using "Windows Authentication".

"Windows Authentication" is *not* the same thing as "I am trying to use Bononbo with a Windows client"

**Comment by larshg** [comment]
Are you presented for a username/password dialogue?
Can you try clone using got bash?

**Comment by aPSopt** [comment]
**@willdean** it is defaul configuration as I see. I following by the installation manual and finally in the default 6.1 web.config turned on following options:

> <add key="AuthenticationProvider" value="Cookies" />
> <add key="ImportWindowsAuthUsersAsAdmin" value="false" />
> <add key="MembershipService" value="Internal" />

And I note that it not works now.

**larshg** yes, the same trouble present on cmd usage too. But I find how to disable tortoisegit credential helper and bug disappears.
Ok, its good. 
But how to work with default configuration on the tortoisegit? (with credential helper)

**Comment by larshg** [comment]
Try update to newest credential helper?

**Comment by aPSopt** [comment]
**larshg** thx, now it works

**Comment by larshg** [comment]
Great to hear :-)

**Comment by willdean** [comment]
Thanks @larshg !
