### ISSUE TITLE
Git failed with fata error (URL returns 502) with Visual Studio 2017

### ISSUE THREAD

**Issue by Kempe** [jakubgarfield/Bonobo-Git-Server#669]
When trying to sync my project with local bonobo git server (right now v6.0, but the same happens with 5.2) I get an error saying:
Error encountered while pushing to the remote repository: Git failed with a fatal error.
fatal: unable to access 'http://user@server/Bonobo.Git.Server/Test.git/': The requested URL returned error: 502
Pushing to http://user@server/Bonobo.Git.Server/Test.git

But, with VS 2015 I had no problems at all. 
Any help appreciated ...
Thanks in advance...

**Comment by willdean** [comment]
There's no way to help with this sort of problem without more information, I'm afraid.

You'll need to dig into what the error is on the server (Bonobo logs exceptions to app_data), and also try from a command line client with Curl debugging turned on (easy to look up how to do this).

**Comment by Kempe** [comment]
Thanks for pointing to curl! It shows that it used a http proxy setting defined in windows environment settings! After removing everything works as expected!
Thank you very much for quick response! 
Cool Project, by the way....
