### ISSUE TITLE
IIS 7.5 to many redirects

### ISSUE THREAD

**Issue by lipe1966** [jakubgarfield/Bonobo-Git-Server#675]
After updating the aplication the web site does not open anymore.
I've checked the Permissions, Authentications and etc.
The only clue that I've got was on the conversion to Application that if i click the Test button I receive a message of "Invalid Application Path"

I am using Windows Server 2008 R2 with IIS7.5

**Comment by willdean** [comment]
"conversion to Application that if i click the Test button" - I don't think I understand that bit - can you expand?  What version were you running before?

Make sure you've got .NET 4.6 on your server.

**Comment by lipe1966** [comment]
I am using .NET 4.6
when on the GUI if I click with the right button on the mouse to Convert to Application, it opens a window and there we have a button called "Test Settings", If I click it i receive the message bellow

![image](https://cloud.githubusercontent.com/assets/8996760/24976430/cd44ac12-1f9f-11e7-9ac9-81c3b7e37e56.png)

**Comment by willdean** [comment]
Have a look at this:  http://stackoverflow.com/questions/5794063/invalid-application-path

There are about 100 million ways for IIS to be configured so it won't run a web application, and I'm afraid it's beyond the very limited resources of the Bonobo team to work through them all with everyone, sorry.

**Comment by lipe1966** [comment]
How can I get the prior version of 6.0? That used to work

**Comment by willdean** [comment]
There are some old versions here:

https://github.com/jakubgarfield/Bonobo-Git-Server-Web/tree/master/content/resources/releases
