### ISSUE TITLE
This page can’t be displayed

### ISSUE THREAD

**Issue by sadeghrz** [jakubgarfield/Bonobo-Git-Server#676]
hi i can run Bonobo on my pc but when i try to run it on server IIS tell me "This page can’t be displayed".
browser redirect to this page: http://localhost:1234/Home/Error?aspxerrorpath=/Home/Error
and got the "This page can’t be displayed" error.
try everything even change the windows and nothing changed.

i can host another mvc app as same version like Bonobo.

**Comment by larshg** [comment]
Is there anything in the logs? - you can try disable custom errors `    <customErrors mode="On" defaultRedirect="Home/Error" />` - and maybe get a hint about what is going wrong?

**Comment by willdean** [comment]
As well as @larshg suggestions, start by running the browser on machine which is running IIS.

**Comment by sadeghrz** [comment]
ooo shit i'am donig ...
change server windows just for custome error turn on.....
 .netFramework 4.6 needed for fix

thank you!
