### ISSUE TITLE
Método no encontrado: '!!0[] System.Array.Empty()'.

### ISSUE THREAD

**Issue by ingdotrodriguezbarrios** [jakubgarfield/Bonobo-Git-Server#682]
I have a problem before, installing Bonobo on IIS 8, Windows Server 2012.

This is, stack trace

[MissingMethodException: Método no encontrado: '!!0[] System.Array.Empty()'.]
   Bonobo.Git.Server.App_Start.BundleConfig.RegisterBundles(BundleCollection bundles) +0
   Bonobo.Git.Server.MvcApplication.Application_Start() +104

[HttpException (0x80004005): Método no encontrado: '!!0[] System.Array.Empty()'.]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +12625869
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +175
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +353
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +404
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +475

[HttpException (0x80004005): Método no encontrado: '!!0[] System.Array.Empty()'.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +12642916
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +12482321

I allready instaled .NET Framework 4.6, I verified .Net Framework 4.6 with this tool https://blogs.msdn.microsoft.com/astebner/2008/10/13/net-framework-setup-verification-tool-users-guide/, all appears be ok with .NET Framework. 

I dont now what do!

**Comment by larshg** [comment]
I really seems that it is still missing the .net 4.6 on the server?

http://stackoverflow.com/questions/31253747/method-not-found-0-system-array-empty-asapp-bundleconfig-registerbundl

I really doubt that there is much we can do from here though.

**Comment by larshg** [comment]
@ingdotrodriguezbarrios have you solved this issue?

**Comment by ingdotrodriguezbarrios** [comment]
Yes. i did it, i installed TFS, it come with .net4.6.2, i restarted my server, before Bonobo worked.

Thanks a lot!
