### ISSUE TITLE
Runtime Error after configuring Active Directory Membership Service

### ISSUE THREAD

**Issue by mastrat** [jakubgarfield/Bonobo-Git-Server#688]
Hi everyone,
I'm trying to set up a git for testing purposes. I followed the installation instructions and tried configuring Bonobo for using our AD. After configuration I run into in a runtime error:
`Server Error in '/Bonobo.Git.Server' Application.
Runtime Error 
  Description: An exception occurred while processing your request. Additionally, another exception occurred while executing the custom error page for the first exception. The request has been terminated. 
`
I think my appSettings should be configured correctly:
```
<appSettings>
    <add key="webpages:Enabled" value="false" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />
    <add key="UserConfiguration" value="~\App_Data\config.xml" />
    <add key="DefaultRepositoriesDirectory" value="~\App_Data\Repositories" />
    <add key="GitPath" value="~\App_Data\Git\git.exe" />
    <add key="GitHomePath" value="~\App_Data" />
    <add key="RecoveryDataPath" value="~\App_Data\Recovery" />
    <add key="LogDirectory" value="~\App_Data\Logs" />
    <add key="serilog:minimum-level" value="Information" />
<!-- 
    <add key="serilog:minimum-level" value="Verbose" />
-->
    <add key="AuthenticationProvider" value="Cookies" />
    <!--
    <add key="AuthenticationProvider" value="Windows" />
-->
    <add key="ImportWindowsAuthUsersAsAdmin" value="false" />
    <!--<add key="AuthenticationProvider" value="Federation" />-->
    <!--add key="MembershipService" value="Internal" />
    <add key="MembershipService" value="ActiveDirectory" />
    <add key="ActiveDirectoryDefaultDomain" value="[REMOVED]" />
    <add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" />
    <add key="ActiveDirectoryMemberGroupName" value="gitusers" />
    <add key="ActiveDirectoryTeamMapping" value="Developers=gitusers" />
    <add key="ActiveDirectoryRoleMapping" value="Administrator=gitadmins" />-->
    <!--<add key="FederationMetadataAddress" value="https://sts.domain.local/federationmetadata/2007-06/federationmetadata.xml" />
    <add key="FederationRealm" value="https://git.domain.local" />-->
  </appSettings>
```

A key for ActiveDirectoryDefaultDomain was not in the config and I had to copy it myself. Have I just made a stupid typo that I cant find or am I having other problems?

With best regards
Marcel

**Comment by larshg** [comment]
Hi

Can you post what i says in the logs folder?

You can also try to navigate to /Home/diagnostics on a browser on the server for more info.

The defaultdomain option is not active in the current master - but you can try [this](https://ci.appveyor.com/project/jakubgarfield/bonobo-git-server/build/570/artifacts) artifact.

**Comment by willdean** [comment]
@mastrat Take @larshg advice, but also make sure you can get it working *without* AD login first - that's much more complex than the default configuration - make sure that works first.

**Comment by mastrat** [comment]
Thanks for your reply. 
@larshg I can't browse to /home/Diagnostics or localhost/diagnostics etc. Should there anything listen on that URL? Can the verbose level of logging be changed? Cause the log does only contain information of Bonobo starting:
```
2017-05-09 09:40:41.266 +02:00 [Information] Bonobo starting
2017-05-09 09:53:44.377 +02:00 [Information] Bonobo starting
2017-05-09 09:56:36.778 +02:00 [Information] Bonobo starting
```
I tried the artifact you provided and I run into the same problem. Applied Web.config to the actual installation - same here.
@willdean It works without any problems when I use the internal MembershipService. Site opens and I can login with default credentials.

**Comment by larshg** [comment]
@mastrat can you try turn off custom errors in the webconfig and post what exception is shown?

**Comment by mastrat** [comment]
Of course it was a typo in the Web.config. Thanks for the hint of turning off custom errors. So I realised the comment close tag at the end of the line
> <add key="ActiveDirectoryRoleMapping" value="Administrator=gitadmins" />-->

Seems to work like expected now. Sorry for bothering you guys with such a stupid mistake.
