### ISSUE TITLE
6.2 Release?

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#693]
@larshg I'm thinking of doing a 6.2 release - this would fix the ADFS regression #681, and the various AD issues you've been working on.   

What do you think?   I've had a go at updating changelog.md

**Comment by larshg** [comment]
Yes, lets do that. As there are currently no critical PRs that should be merged first. I have however something to the documentation [here](https://github.com/jakubgarfield/Bonobo-Git-Server-Web/pull/2).

Can you merge that one?

But go ahead with a 6.2 release.

**Comment by willdean** [comment]
Done
