### ISSUE TITLE
6.2 is built as 6.0

### ISSUE THREAD

**Issue by Trapulo** [jakubgarfield/Bonobo-Git-Server#696]
The 6.2 release has bonobo.git.server.dll compiled as "6.0" version

**Comment by willdean** [comment]
@Trapulo - can you say where you're seeing this version number?    I keep updating assemblyinfo files but clearly I'm missing something.

**Comment by Trapulo** [comment]
I downloaded the build from https://bonobogitserver.com/ : it reports 6.0 in Web frontend, so I checked the .dll file from windows explorer, and it results as the 6.0 version.

**Comment by willdean** [comment]
@Trapulo You're quite right, thanks for pointing this out.  I will have a look into what's going on and release a new version when I've worked out where that comes from.

**Comment by willdean** [comment]
@Trapulo I've released 6.2.1 with this corrected (I hope!) - thanks for letting us know.
