### ISSUE TITLE
Port Bonobo to dotnet core(AspNetCore)

### ISSUE THREAD

**Issue by fcharlie** [jakubgarfield/Bonobo-Git-Server#700]
I used `dotnet core` to write a cross-platform git smart HTTP server, the development process is very simple, using `await/async.`  I suggest that Bonobo be fully ported to `dotnet core`, using `await/async` and `AspNetCore`, so that it can better support cross-platform and provide services to more people.

https://github.com/fcharlie/Angelo

**Comment by willdean** [comment]
@fcharlie I have certainly thought about this.  Here are my current thoughts:

* A lot of people seem to use the AD support in Bonobo, which would be difficult/impossible in .NET Core at the moment, and may never be supported off Windows.
* We would want to wait for Core 2.0 which is not released yet (And VS2017.3 Preview is unusably unstable for me)
* I haven't checked what other dependencies we have that aren't available for Core yet.
* Doing basic user support for IIS is already a significant burden on the Bonobo maintainers and expanding that to include more complex setups (Kestrel and Linux) is very unappealing to me.  
* I'm not sure anyone would value Bonobo on Linux unless it did something special (perhaps AD integration)?

Perhaps a bit like you have done, I have been tempted to start from scratch in .NET Core - personally I would kick all the auth out into something like IdentityServer and I would lose all the repro browsing, file-viewing stuff and just make a Git server.

**Comment by Varorbc** [comment]
can you support .net core now@willden
