### ISSUE TITLE
Upgrade from 5.2 to 6.2.1 all repo's disappear

### ISSUE THREAD

**Issue by alainassaf** [jakubgarfield/Bonobo-Git-Server#701]
Just completed an upgrade from 5.2 to 6.2.1. It's not clear from the change log, but are no repos for the 5.2 version compatible with 6.2.1? Do I have to recreate everything? Was there a way to export the repo info from 5.2 prior to an upgrade? I've still got my app_data folder backed up and I can see the repo's under \Bonobi.Git.Server\App_data\ADBackend\Repos.

Thanks,
Alain

**Comment by willdean** [comment]
I think you'll have to set the ownership and details up again for AD, sorry - it should discover all the repos in the file system, though.

They're only json files and it might be possible to come up with some kind of converter/importer.

**Comment by alainassaf** [comment]
I also don't seem to have admin permission any longer. I've set the ActiveDirectoryRoleMapping key to the AD group I used before (which I'm a member of). I can't create new repositories. I get this:


Unauthorized

You don't have permission for the selected action or page.


________________________________

**Comment by alainassaf** [comment]
I think the issue may be because of different domains. Our local AD domain is blabla.local, but our email accounts (due to ADFS) are me@blabla.org. When I check the teams and drill down to my account, it's looking for me@blabla.org. All AD groups are in blabla.local.

**Comment by willdean** [comment]
@alainassaf There could well be domain problems (we've struggled with that) - could you have a look in app_data\logs at today's log and see if it contains anything useful which could help us.

**Comment by alainassaf** [comment]
Here's the log file.
[log-20170616.txt](https://github.com/jakubgarfield/Bonobo-Git-Server/files/1081414/log-20170616.txt)

**Comment by willdean** [comment]
@alainassaf I'm not the AD expert, but could you try playing with the ActiveDirectoryDefaultDomain option in web.config - perhaps try:

`<add key="ActiveDirectoryDefaultDomain" value="blabla.local" />`

**Comment by alainassaf** [comment]
That's what it is set to right now. I also tried blabla.org. I tried Internet Explorer (instead of Chrome) and it appears to be working. The only issue now is the buttons are missing and the layout is not quite right. Not sure how I can show this to you. Let me try a screen shot and attach it.
![6 2 1_layout](https://user-images.githubusercontent.com/25592289/27236671-e4605fa0-5293-11e7-8652-04001ebbf3e1.png)

**Comment by alainassaf** [comment]
I'm going to close this issue as the repo's appear now. Unfortunately, I'll have to rollback and try a parallel upgrade in the future. They way it is now, is not usable for my company.

**Comment by willdean** [comment]
@alainassaf I'm sorry you've had trouble - I can't really help with the AD stuff personally, and we find it impossible to test properly as no two people have the same combination of servers and domain names.

I can't see why the browser would make a difference, so I suspect there is more than one problem going on.  If @larshg is around he might be able to suggest something to try.

**Comment by alainassaf** [comment]
I appreciate it. I know you're all doing this on your spare time and are not getting paid. So thank you for trying to keep this tool moving forward.

**Comment by Nu11u5** [comment]
@alainassaf Your IE issue is due to Compatability Mode being enabled by default for the Intranet Zone.  This can be changed in the IE settings.  It looks like there is an HTML meta tag that can be added to the page source to override this behavior as well.  Might be worth a making a separate bug report.
