### ISSUE TITLE
Browsing to a binary file tries to display as text in the blob preview

### ISSUE THREAD

**Issue by Nu11u5** [jakubgarfield/Bonobo-Git-Server#714]
If you include a binary file in your repo and browse to it in Bonobo the server will try to parse and return the entire file contents as text in the preview.

**Comment by willdean** [comment]
I think it's a little more complex than that - there are a bunch of rules for trying to display binaries as something else (e.g. images), though I don't know much about that.  What sort of file was it?

**Comment by Nu11u5** [comment]
It's a windows executable I'm including as a tool.

**Comment by willdean** [comment]
@Nu11u5 - the logic for deciding whether or not to display files as 'text' has been broken - I will merge a fix for this shortly - thanks for letting us know.
