### ISSUE TITLE
Error: Too many redirects

### ISSUE THREAD

**Issue by Freddyvdh** [jakubgarfield/Bonobo-Git-Server#723]
Hi,

I wanted to update to the latest version, but with it I get the ERR_TOO_MANY_REDIRECTS error.
The old version (5.2.0) works fine.

No logs are generated, so I don't know where I can search for an error.

I path of the 6.2.1 version is C:\inetpub\wwwroot\Bonobo.Git.Server.6.2.1
The URL is http://localhost:8080/bonobo.git.server.6.2.1/

The redirected URL is http://localhost:8080/bonobo.git.server.6.2.1/Home/Error?aspxerrorpath=/bonobo.git.server.6.2.1/Home/Error

Thanks,
Freddy

**Comment by larshg** [comment]
Have you updated tour .net framework to 4.6.x. I think this is required.

**Comment by larshg** [comment]
See #672 etc.

**Comment by Freddyvdh** [comment]
Thanks, that fixed it!
