### ISSUE TITLE
Error 500 on push

### ISSUE THREAD

**Issue by jagDanJu** [jakubgarfield/Bonobo-Git-Server#727]
Hey Guys,

we are using the current version of Bonobo.
We set it up on Windows Server 2012 with `<add key="MembershipService" value="ActiveDirectory" />` authentification.

Login etc. works fine. But if we want to push a commit we get an error code 500.

If i open the *.git URL in Chrome then i get the following error message:

`System.FormatException: Invalid length for a Base-64 char array or string. at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength) at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength) at System.Convert.FromBase64String(String s) at Bonobo.Git.Server.GitAuthorizeAttribute.IsUserAuthorized(String authHeader, HttpContextBase httpContext) at Bonobo.Git.Server.GitAuthorizeAttribute.OnAuthorization(AuthorizationContext filterContext) at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList'1 filters, ActionDescriptor actionDescriptor) at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.b__19(AsyncCallback asyncCallback, Object asyncState)
`
Did anyone have an Idea??

Thanks.

**Comment by willdean** [comment]
Is this possible a duplication of #704 - are there special chars in your password?

**Comment by jagDanJu** [comment]
Yes.. Without special chars it works!
