### ISSUE TITLE
Version 6.2.2 problem with redirection after login

### ISSUE THREAD

**Issue by Mori22** [jakubgarfield/Bonobo-Git-Server#731]
Hi,

I did just install Bonobo Server Version 6.2.2 (Windows Server 2012 R2).

The installation itself went without any problems and I see the login screen when i open

`http://localhost/Bonobo.Git.Server`

When I now enter the default admin details I get an error 404 page that the requested page was not found. The URL of this page is:

`http://localhost/Home/Index`

which does not exist.

When i manually enter the URL

`http://localhost/Bonobo.Git.Server/Home/Index`

I get the correct page and am logged in.

So my guess is that the returnURL on the Login page is somehow wrong. Currently it is set to:

`?returnUrl=%2FHome%2FIndex`

I did try to install the Git Server on a freshly installed server (Windows Server 2016) with the same result. 

I was unable to find a compiled version of a previous version of bonobo so I am unable to test whether this issue is specific to my setup or a general problem with version 6.2.2.

**Comment by willdean** [comment]
@Mori22 You can find older versions (no index, but the binaries are there) at URLs like this:

https://bonobogitserver.com/resources/releases/6_2_1.zip

A complete list of everything that's up there is here:

https://github.com/jakubgarfield/Bonobo-Git-Server-Web/tree/master/content/resources/releases

If you do find an earlier version works better then that would be interesting.

You will find that prior to 6.x the database format is different, so it's hard to go back that far without restarting on the database.

**Comment by Mori22** [comment]
@willdean I did try the Version 6.2.1 and didn't have problem with the redirection: 

When I enter the admin credentials i get redirected to the correct page

When I checked the ReturnUrl in Version 6.2.1 the value there is:

`ReturnUrl=%2FBonobo.Git.Server%2FHome%2FIndex`

So my guess would be that the issue i described is problem within version 6.2.2 and could be relevant for any user who updates to this version.

Anyway I will just stick to Version 6.2.1 until the issue is resolved.

**Comment by willdean** [comment]
@Mori22  Thanks for checking this - I suspect this is perhaps something to do with #710 - I'll have a look.

**Comment by willdean** [comment]
@jeffgaroutte would you mind having a look at this and see if you think anything in #710 might be involved?

**Comment by oharab** [comment]
Is the issue with the [RepositoryController](https://github.com/jakubgarfield/Bonobo-Git-Server/blob/735ea519b22c904729680c789c693db9a977ea13/Bonobo.Git.Server/Controllers/RepositoryController.cs#L44) not taking into account any virtual directories.
` public ActionResult Index(string sortGroup = null, string searchString = null)
        {
            var unorderedRepositoryDetails = this.GetIndexModel();
            if (!User.Identity.IsAuthenticated && !unorderedRepositoryDetails.Any())
            {
                return RedirectToAction("Logon", "Home", new { returnUrl="/Home/Index" });
            }`

**Comment by Guido11** [comment]
I experience the same problem
Version 6.2.1 works fine and the login page redirects to the right page in ReturnURL
https://testcodesafe.chsys.org/Bonobo.Git.Server/Home/LogOn?ReturnUrl=%2FBonobo.Git.Server%2F

Version 6.2.2 redirect to a different location Home/Index
https://testcodesafe.chsys.org/Bonobo.Git.Server/Home/Logon?returnUrl=%2FHome%2FIndex

**Comment by willdean** [comment]
@oharab Thanks - I think you're right - it should be using a method to create the URL, not just a text string.

**Comment by willdean** [comment]
I've just posted a PR which should address this - once AppVeyor's built it, would anyone who's struggling with this be able to download the zip from the AppVeyor artefacts and try it out?

**Comment by Mori22** [comment]
@willdean would love to test it but there seems to be a problem with the changes as AppVeyor just outputs an error and no usable zip files

**Comment by willdean** [comment]
@Mori22 Yes, the unit tests are broken, sorry.  I am struggling to make time to deal with this at the moment, but will post here again when it's fixed.

**Comment by Mori22** [comment]
@willdean don't worry this isn't a big deal as version 6.2.1 runs perfectly stable. If anything you deserve praise for reacting so fast at all!

**Comment by jeffgaroutte** [comment]
line 44 should be 
`return RedirectToAction("Logon", "Home", new { returnUrl= Url.Action("index", "Home") });`

that should address the unit test issue and virtual directories.
