### ISSUE TITLE
AFDS broke on 6.3.0

### ISSUE THREAD

**Issue by bluewalk** [jakubgarfield/Bonobo-Git-Server#736]
After updating to 6.3.0 ADFS has stopped working. On login you do not get redirected to the ADFS page. It simply shows the login form, entering details in that form does not log you on either.

Reverting to 6.2.1.588

**Comment by willdean** [comment]
@bluewalk Thanks for this - I suspect this is related to #710 which has had some other issues around login.

**Comment by devaraja666** [comment]
It also happen on me with AD authentication in version 6.3.0, it shows the normal AD authentication but after that it goes to the login form. If i manually go to /Repository/Index it works normally.
