### ISSUE TITLE
Facilitate Pull-Requests

### ISSUE THREAD

**Issue by Duikmeester** [jakubgarfield/Bonobo-Git-Server#74]
This is more like a question of where I can find documentation how this works creating a pull-request and accepting them in Bonono.

Using SourceTree I get the error: You don't have any remotes which have extended integration settings configured.

Where can I find information about this, as I would like to make it myself.

**Comment by alexchandel** [comment]
This should be part of a broader Bonobo web-based issue tracker (like GitHub's `/issues`). PRs provide a forum for proposing and discussing changes, as opposed to just merging and pushing.

A simple interpretation of pull requests is a directed edge between branches or commits (`master <- test`) representing a proposed merge commit. If there are no merge conflicts, accepting the PR would simply execute a pull/merge.

**Comment by whosa** [comment]
When you file a pull request, all you’re doing is requesting that another developer (e.g., the project maintainer) pulls a branch from your repository into their repository. This means that you need to provide 4 pieces of information to file a pull request: the source repository, the source branch, the destination repository, and the destination branch.

https://www.atlassian.com/git/tutorials/making-a-pull-request

**Comment by spoiledtechie** [comment]
I would love to see the ability to facilitate pull requests/forks as well.  Throwing my hat in the bucket.

**Comment by spoiledtechie** [comment]
I think, to the very least, if we can't get pull requests/forks etc, it would be GREAT if we can at least add comments to a line of code in a commit.  One that comment, I would have a checkbox that allows me to send the commiter an email with the code and comment.  Therefore they can review the comments as well as reply to the commenter with another email notification.

**Comment by jakubgarfield** [comment]
I'd be happy to see a pull request with any of these Issues/Pull requests/Code comments to bonobo.

**Comment by RedX2501** [comment]
If PRs come in for these features we wil integrate them but for such needs i'd recommend to go to GitLab for it.

**Comment by Duikmeester** [comment]
We have started using TFS with excellent support for Git now-adays.

**Comment by Benew** [comment]
Do you know how Bonobo usually settle conflicts?

**Comment by RedX2501** [comment]
Bonobo does not do any handling of conflicts. There is a regular git bare repository at the end which does all the handling. Regular git does not have any support for pull requests of any kind.

**Comment by Benew** [comment]
I was refering to the animal.
