### ISSUE TITLE
Pushing requires authentification

### ISSUE THREAD

**Issue by forReason** [jakubgarfield/Bonobo-Git-Server#746]
Hello,

I can login to http://myserver.com/git with my credentials. Also pushing with visual studio worked fine until now. Now it keeps asking for a usernam and password.

I tired to open up http://myserver.com/git/project.git and it asks for a password and username. It doesnt accep the user/password combination i login with.

best regards,

![grafik](https://user-images.githubusercontent.com/12736950/31116257-b38a5588-a825-11e7-9829-66c920b0017f.png)

julian

**Comment by forReason** [comment]
Update: This error seemingly only occurrs when I have enabled the option "use windows authentication in iss" probably its not an issue of bonobo git

**Comment by Nu11u5** [comment]
Per the setup instructions the IIS web application is supposed to be set up with anonymous authentication only.  Bonobo uses it's own internal authentication methods that are configured in the web.config file.
