### ISSUE TITLE
Can be used in the android studio？

### ISSUE THREAD

**Issue by yedajiang44** [jakubgarfield/Bonobo-Git-Server#779]
I have been used successfully in Visual Studio, and experience is great, but now I don't know how to use the andtoid Studio...can you give me some advice？

**Comment by willdean** [comment]
I'm sorry, we can't help with this sort of stuff.  Bonobo is just a Git server, and Android Studio will treat it the same as any other Git server.

**Comment by yedajiang44** [comment]
@willdean Thank you for your response, I have been solved, thank you again for the Shared project
