### ISSUE TITLE
Most of the projects showing missing

### ISSUE THREAD

**Issue by PranjalGohain** [jakubgarfield/Bonobo-Git-Server#781]
![1](https://user-images.githubusercontent.com/23078404/35645740-d8b0bfb0-06f2-11e8-8f95-241b9127c8a3.png)

Hi Team,

    I have been working with my customer on bonobo Git for few months now. The problem is my expired projects all goes into the missing state when i try to remove them or delete them. I had stopped IIS services and then delete the log files but still unable to remove them. Really need some guidance here.

**Comment by willdean** [comment]
There should be a delete button (trash can icon) on the right of each repository line, which lets you delete it.

That said, current versions have lots of additional icons on the screen which you don't have - perhaps you're running a very old version?

**Comment by PranjalGohain** [comment]
Hi Willdean thanks for your response.
I just see 2 options in the right side which says on the copy git url and the copy git personal url.. 
I had deleted the missing repositories from my application and even from the repository folder. Deleted the logs as well.... Is there any trace file which is still holding these values.

**Comment by willdean** [comment]
I'm not sure why you can't see them, but I don't know what version you're running or if you're an administrator.

The entries you're seeing come from the database which, unless you've changed things to use SQL Server, is a Sqlite database held in app_data\bonobo.git.server.db.  If you really can't get Bonobo into a state where it shows you the delete button, you could use one of the many Sqlite admin tools which are around to delete the appropriate entries in the database.

It sounds to me like your user is not the Bonobo administrator, though.

**Comment by PranjalGohain** [comment]
ah ok... i guess i will have to try doing that then. I was using with root user though.

Any idea what username and password i have to use to open the database file..

**Comment by willdean** [comment]
You don't need any special credentials to open a the sqlite file - it's just a file, it's not a database server like SQL server.

**Comment by PranjalGohain** [comment]
I would like to close this thread. All thanks to Willdean... There was this issue with the screen resolution which was not displaying the delete option.. I copied the entire work-space to my local and was able to see all the options with the same bonobo version... Thanks a lot... And yes honestly if anyone wants to use git which is opensource and in an GUI format for Windows then definitely i would suggest Bonobo.. Its an awesome application.. All thanks to the creators....
