### ISSUE TITLE
[Question] DirectoryContext builtin users / Ad authentication using local builtin users

### ISSUE THREAD

**Issue by generik0** [jakubgarfield/Bonobo-Git-Server#784]
HI

Great application. Thanks!! Really good work.

I am trying to get the security to work with the builtin users. So basically work like the Active directory, but only with local machine accounts.
I know this might seem as little strange, and not useable for distributed systems. But it has its purpose for my needs....

Any ideas?

i have tried the domain as: "domain.local", ".", "127.0.0.1", "local"

Maybe the DirectoryContext does not support the bultin users?

**Comment by cbaerike** [comment]
Hi,

Local machine accounts will not work with the AD routines. Technically, the domain name for local accounts is your server name, not "domain.local". However, even with that setting your server won't reply to LDAP requests, which is what all the Active Directory routines in .NET rely on.

I'm afraid you'll either need to set up a domain controller, or use the non-AD membership option in Bonobo.

**Comment by generik0** [comment]
Great. Good to know. Thanks...
