### ISSUE TITLE
HTTP Error 500.24 - Internal Server Error

### ISSUE THREAD

**Issue by pawanadubey** [jakubgarfield/Bonobo-Git-Server#787]
Hi all,
I followed the document for installing the application, I have deployed the application in C:\inetpub\wwwroot\Bonobo.Git.Server. Given IIS User all the permission, disabled the authentication. I even tried searching on internet but did not get anything.
I get below error when I browse:
Error Summary:
HTTP Error 500.24 - Internal Server Error
An ASP.NET setting has been detected that does not apply in Integrated managed pipeline mode.

Detailed Error Information:
Module : ConfigurationValidationModule
Notification: BeginRequest
Handler: Static file
Error Code: 0x80070032
Requested URL: http://localhost:8080/Bonobo.Git.Server
Physical Path: C:\inetpub\wwwroot\Bonobo.Git.Server
Logon Method: Not yet determined
Logon User: Not yet determined

Most likely cause:
•system.web/identity@impersonate is set to true.

And when I disable ASP.NET Impersonate in Authentication, I get below error:

Runtime Error :
Description: An exception occurred while processing your request. Additionally, another exception occurred while executing the custom error page for the first exception. The request has been terminated. 

Please let me know how can I get this up and running.

I'm using windows server 2008 R2, that is in domain.

**Comment by braibaud** [comment]
Hi, 

I had the same issue and fixed it by adding

`<validation validateIntegratedModeConfiguration="false" />`

under the `<system.webServer>` node in the `web.config` file.

Ben

**Comment by pawanadubey** [comment]
@braibaud Thanks for the input. It did work 👍
