### ISSUE TITLE
Unable to install bonobo git server 6.3 

### ISSUE THREAD

**Issue by yashali** [jakubgarfield/Bonobo-Git-Server#792]
I have posted this question on stackoverflow.com  as well. 

https://stackoverflow.com/questions/49272016/bonobo-got-server-6-3-starting-fails
I am trying to install a bonobo git server 6.3 on a Windows 2012 r2 machine. I have iis 8.5, installed .Net framework 4.6. I have anonymous auth enabled, iis users have full control on the folder, default app pool on the Bonobo.Git.Server, which is an application under default website, has .NET CLR version 4.0 and pipeline mode integrated, i haven't changed the advanced settings of the bonobo application in iis. Localhost is under trusted sites as well

When i browse this happens : 

![img_20180314_130443](https://user-images.githubusercontent.com/7327340/37390801-3e55f3fa-278f-11e8-8cd9-e2d1ab3d338b.jpg)

The log file also indicates the same. What am i doing wrong? Have i missed something?

The last line in the prerequisites is for Windows 10 and not for Windows server 2012,right?
I have followed all the steps in the installation guide.  But the exception hasn't gone away. Can someone help? The log just says : bonobo starting. And nothing else

**Comment by yashali** [comment]
![15210164806741027220532](https://user-images.githubusercontent.com/7327340/37391275-af0d2928-2790-11e8-9a4e-1d50ec4fb9d1.jpg)
This is after turning custom errors off.

**Comment by willdean** [comment]
I think you should try install .NET 4.6 again, as it looks like this problem:

https://stackoverflow.com/questions/31253747/method-not-found-0-system-array-empty-asapp-bundleconfig-registerbundl

**Comment by PraveshDev** [comment]
I think you have not done the following : -
![convert to application](https://user-images.githubusercontent.com/19771284/38248671-db107468-3766-11e8-8622-343dce2d3ca1.PNG)

**Comment by yashali** [comment]
Thanks!
