### ISSUE TITLE
fatal: unable to access -  The requested URL returned error: 500

### ISSUE THREAD

**Issue by JulioBandeira** [jakubgarfield/Bonobo-Git-Server#797]
Hello, I'm trying to clone bobono.server.git, but it returns this error:
$ git clone http: //admin@10.16.0.133: 8081 / siad_enterprise.git
Cloning into 'siad_enterprise' ...
fatal: unable to access 'http: //admin@10.16.0.133: 8081 / siad_enterprise.git /': The requested URL returned error: 500.

Has anyone ever experienced this?

Note: I use proxy.
          Windows Server 2012, IIS8.

**Comment by willdean** [comment]
Are you absolutely sure that the user which your app-pool is running as has permission to access your Git repository directories?
