### ISSUE TITLE
feature request: read only access to repositories

### ISSUE THREAD

**Issue by joerg1985** [jakubgarfield/Bonobo-Git-Server#798]
We are using Bonobo Git Server with authenticated users only, we had some pushes to repositories by error. Now we would like to give some teams / users only read access to some repositories. 

Currently it is only possible to grant read and write rights to a user or team. Is it possible to change this in a future version of Bonobo Git Server?

Kind regards

**Comment by chkpnt** [comment]
You could write a `pre-receive` hook script, which rejects the push, if the user isn't authorized.

Several environment variables are available for the script to implement this task:
```sh
AUTH_USER="userid@example.com"
AUTH_USER_DISPLAYNAME="John Doe"
AUTH_USER_ROLES="..."
AUTH_USER_TEAMS="..."
...
REMOTE_USER="userid@example.com"
```

**Comment by joerg1985** [comment]
@chkpnt thanks for the hint.
