### ISSUE TITLE
Active Directory server setup

### ISSUE THREAD

**Issue by rcohn** [jakubgarfield/Bonobo-Git-Server#809]
Hello -

Is there a definitive source for an example of setting up the Bonobo git server for Active Directory usage?  The example in the Bonobo documentation does not seem to work properly.  Here's what I have in the Web.Config file:

    <add key="MembershipService" value="ActiveDirectory" />
    <add key="ActiveDirectoryDefaultDomain" value="companyname.com" />
    <add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" />
    <add key="ActiveDirectoryMemberGroupName" value="git_Engineering" />
    <add key="ActiveDirectoryTeamMapping" value="Developers=git_Engineering" />
    <add key="ActiveDirectoryRoleMapping" value="Administrator=git_Admin" />

Does this look about right?
Thank you.

**Comment by KonstantinVRT** [comment]
It is not the question of Bonobo config only. IIS/site should be configured correctly as well.
Your web.config should also have this line:
<system.web>
    <authentication mode="Windows" />
</system.web>

But besides it we need an example of working IIS/site config.
