### ISSUE TITLE
Convert to application does not seem to work correctly for me...

### ISSUE THREAD

**Issue by Palloquin** [jakubgarfield/Bonobo-Git-Server#821]
Hi there,

I'd love to get started with Bonobo, but fail at installing.

Following the install guide I try to convert the Bonobo.Git.Server folder to an application. The result should be like this image:
![image](https://user-images.githubusercontent.com/3383944/47721785-2837b000-dc51-11e8-98ae-6c607499a506.png)

How ever, I end up with this:
![image](https://user-images.githubusercontent.com/3383944/47721817-3b4a8000-dc51-11e8-8bed-d77e4e0b15bc.png)

The forms and interface parts never appear... What could I be doing wrong?

When trying to connect to the server after this, I get a 403 error:

> 403 - Forbidden: Access is denied.
> You do not have permission to view this directory or page using the credentials that you supplied.

Help?

**Comment by willdean** [comment]
You don't appear to have any application pools, which may suggest you don't have something missing, like the .NET framework or ASP.NET components of IIS.

Have a look at #718 

It often feels like no two installations of Windows + IIS are the same, so getting the list of prerequisites right is hard.

**Comment by Palloquin** [comment]
Hi Willdean,

Thank you for your quick response!

I actually do have application pools:
![image](https://user-images.githubusercontent.com/3383944/47722663-3981bc00-dc53-11e8-9748-bede2ee71750.png)

These are the roles I have installed:
![image](https://user-images.githubusercontent.com/3383944/47722740-6504a680-dc53-11e8-8c2e-2ad7c4ec4692.png)

I was expecting not to need classic asp or the .net 3.5 tools?

**Comment by willdean** [comment]
OK, sounds like you have the right stuff.  You do also need to make sure that the user that the app pool is running at has permission to the folder where you've put the Bonobo files.

**Comment by Palloquin** [comment]
Yup, done that too, this should be cutting it, right?
![image](https://user-images.githubusercontent.com/3383944/47723107-1d324f00-dc54-11e8-9900-2014cb01e2ac.png)

So, after converting, should I have just the bonobo.git.server application, or also the forms and interface ones?

**Comment by Palloquin** [comment]
I'm not sure what did the trick, but I installed all of these:
![image](https://user-images.githubusercontent.com/3383944/47723544-03ddd280-dc55-11e8-88ee-b5fd5dc83e9b.png)

And now I get a logon screen!

Thanks!
