### ISSUE TITLE
Creation of installation package on my own from Bonobo-Git-Server sources

### ISSUE THREAD

**Issue by it3xl** [jakubgarfield/Bonobo-Git-Server#832]
Hello, I've tried to install [6.5.0 release](https://github.com/jakubgarfield/Bonobo-Git-Server/releases) from GitHub on Windows Server 2016 x64 (no SP).
This isn't possible as it isn't compiled and requires Visual Studio (Roslyn .NET Compiler Platform) on a target machine.

I've tried to install  project publishing results that was created by Visual Studio 2017 (v.15.9.10) from the [source project](https://github.com/jakubgarfield/Bonobo-Git-Server/tree/master/Bonobo.Git.Server).
It is also broken and gives errors like "Unable to load DLL 'SQLite.Interop.dll'".

If I'll install 6.5.0 official installation package from [bonobogitserver.com](https://bonobogitserver.com/), then everything works fine.
And Git-diff shows me a bunch of light differences from what I've created with VS Project Publishing and what I've downloaded.

Is it a wrong Idea to create a Bonobo Git Server installation package on my own?
Do you have some Continues Integration magic that isn't shared?
Did I missed something or should I use some extra build technology?

I'm just curious, because I was a little shocked when I couldn't deploy a .NET project. ))
Thanks.

Plus, [bonobogitserver.com](https://bonobogitserver.com/) is blocked in my network and I can't download an official installation package directly and fast.

**Comment by willdean** [comment]
There isn't any hidden magic in the process which builds the release files on bonobogitserver.com - it's just Appveyor running the yml file at https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/appveyor.yml

Maybe you can work through the commands in that to see how it differs from what you've been running?

**Comment by it3xl** [comment]
Oh, thank you, I see. Appveyor, YAML-file appveyor.yml.
OK. Got it.
Indeed, who builds without a CI in our days?
