### ISSUE TITLE
"CodeDom provider type missing" exception after upgrading to 6.5.0

### ISSUE THREAD

**Issue by Nu11u5** [jakubgarfield/Bonobo-Git-Server#833]
After upgrading from 6.2.1 to 6.5.0 I get the following error in Event Viewer:

    The CodeDom provider type "Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" could not be located. (C:\inetpub\wwwroot\Bonobo.Git.Server\web.config line 140)
       at System.CodeDom.Compiler.CompilerInfo.get_CodeDomProviderType()
       at System.Web.Configuration.CompilationSection.GetCompilerInfoFromLanguage(String language)
       at System.Web.Compilation.BuildProvidersCompiler.ProcessBuildProviders()
       at System.Web.Compilation.BuildProvidersCompiler.PerformBuild()
       at System.Web.Compilation.CodeDirectoryCompiler.GetCodeDirectoryAssembly(VirtualPath virtualDir, CodeDirectoryType dirType, String assemblyName, StringSet excludedSubdirectories, Boolean isDirectoryAllowed)
       at System.Web.Compilation.BuildManager.CompileCodeDirectory(VirtualPath virtualDir, CodeDirectoryType dirType, String assemblyName, StringSet excludedSubdirectories)
       at System.Web.Compilation.BuildManager.CompileResourcesDirectory()
       at System.Web.Compilation.BuildManager.EnsureTopLevelFilesCompiled()

Browsing to any page in the server application yields:

> **Server Error in '/Bonobo.Git.Server' Application.**
*Runtime Error*
Description: An exception occurred while processing your request. Additionally, another exception occurred while executing the custom error page for the first exception. The request has been terminated. 

**Details:**

Windows 10 Enterprise 1607
.Net Framework 4.6.2

**Comment by willdean** [comment]
Do you know what version of the .NET Framework you have on there?

(The ridiculous instructions for working out what are [here](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed) )

**Comment by Nu11u5** [comment]
The version of .Net installed is 4.6.2.

The error seems related to the new Rosyln .Net compilers needing to be installed for ASP.Net.  However all of the instructions imply you are working with the project in Visual Studio, not doing a deployment.

https://devblogs.microsoft.com/aspnet/enabling-the-net-compiler-platform-roslyn-in-asp-net-applications/

**Comment by Nu11u5** [comment]
I've snagged NuGet from https://www.nuget.org/downloads and can "install" the referenced package using the command:

    nuget install Microsoft.CodeDom.Providers.DotNetCompilerPlatform

However running this from `\inetpub\wwwroot\Bonobo.Git.Server` so that the package is installed under this directory doesn't resolve the issue.  Assuming this is even the right direction.

**Comment by willdean** [comment]
I suspect upgrading to a later version of .NET would probably fix it, but I can see you might not want to do that, and it is *supposed* to run on 4.6.  

My guess is that #702 broke this for some systems - I'll look and see if we can bundle anything else in the .zip to fix this.

**Comment by willdean** [comment]
Can you have a look in the Bonobo bin directory and check the version of Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll?  Also check that you have a bin/rosyln directory, and that it has the same permissions as the bin directory (i.e. the user that the asp.net process runs as has the same permissions on both directories).

**Comment by Nu11u5** [comment]
Ok let's put this one down as a PEBKAC error.  I had absent-mindedly downloaded the .zip archive from the GitHub Release files instead of the binarys hosted on https://bonobogitserver.com/.

Version 6.5.0 works fine.
