### ISSUE TITLE
[bug] Password Length max 50 Charakters

### ISSUE THREAD

**Issue by m4m-simon** [jakubgarfield/Bonobo-Git-Server#835]
I've changed my admin Passwort to a new 64 Charakter Password.
When i tried to log back in with the new Passwort, it says that only 50 Charakters are allowed. So I lost my access to the system!!!
Luckily i was able to restore a backup of the "Bonobo.Git.Server.db" from few hours before.

**Comment by digitalcoyote** [comment]
I  had a couple of users run into this issue as well, If I get some time, I'll look into getting a PR together to fix it.

**Comment by digitalcoyote** [comment]
I think I may have correctly added the validation, but I needed to boot into Windows (working with Rider on Linux Mint) and I've got so many updates that have to install before it will be usable... I'll try to test my code tomorro
