### ISSUE TITLE
client

### ISSUE THREAD

**Issue by mythrandir52** [jakubgarfield/Bonobo-Git-Server#845]
does anyone have a recommendation for a windows client to work with bonobo.  I have stuff setup on closed networks and most of the windows clients want to point to github.   I have a lot of client doing no code development with various tools so i need a way to version control their stuff.

**Comment by willdean** [comment]
Any Git client should work - just because they have easy setup for Github doesn't mean they wouldn't work with Bonobo.  Personally I use the ordinary command line client a little and Git Extensions a lot.  Some of my colleagues use Sourcetree instead.    GitKraken also works OK.
