### ISSUE TITLE
Bonobo doesn't recognise a new repository directory

### ISSUE THREAD

**Issue by YSivak** [jakubgarfield/Bonobo-Git-Server#858]
Bonobo doesn't show new (edit: repository) folder in repository directory on repositories page, rescan directories does nothing.
Tried restarting IIS and checking configuration but nothing helped.
It worked before and permissions are the same as other folders.

**Comment by willdean** [comment]
Is there actually a bar repository in the folder? 

There needs to be a repo there, not just a folder.

**Comment by YSivak** [comment]
Yes, of course. forgot to mention it's a repository.

**Comment by willdean** [comment]
You'll probably have to investigate this a bit more locally - perhaps using something like procmon to watch Bonobo actually walk the directories?

Basically, Bonono looks up the names of all the directories within the repository directory, and then checks if each one corresponds to the name of a repo in the database already.  If it doesn't, this Bonobo calls `LibGit2Sharp.Repository.IsValid` to ask it if there's a repository in the folder.

Other than permissions issues, I'm not sure why LibGit2Sharp would fail to recognise a folder as containing a repo, but procmon might give a clue.

Simply running `git init --bare MyTest` in the Bonobo repo base directory might also give some information about whether it's something specific about your repo or something more general.

**Comment by willdean** [comment]
Closing because of no response - if you get any further and it's a Bonobo problem, please reopen
