### ISSUE TITLE
Store Everything include Repositories to Database

### ISSUE THREAD

**Issue by hxmcn** [jakubgarfield/Bonobo-Git-Server#865]
Thanks for your team build such a wonderful and free Git Server!

When I Choose SQL Server as my storage system,  I found just a  few data such as accounts, permissions are saved in SQL DB, the Repositories Contents  is still saved  as disk files under App_Data\Repositories folder.
**So, can you let Bonobo save everything to database including Repositories contents?**
Save data to Database made backup whole Bonobo‘s data  and shifting to other server easy and more safe since disk files are easy be modified/deleted by malice software.  And there are many sophisticated database backup system can be used.
Thanks!

**Comment by willdean** [comment]
Thanks for your comments.   Bonobo is just a wrapper on a copy of Git, so this would need to have a 'SQL database backed' version of Git - I don't know such a thing exists, but I think it's unlikely.   

I do see what the advantages would be (nice to have everything in one place), but I don't think it's practical, sorry.
