### ISSUE TITLE
Login Error:  The provided anti-forgery token was meant for a different claims-based user than the current user

### ISSUE THREAD

**Issue by rozniak** [jakubgarfield/Bonobo-Git-Server#874]
Bit of an odd one this - a user that has never signed into Bonobo before tried signing in today and received a simple 500 error page. I took a look in the logs, they get validated and everything, and then this exception occurs:

```
2020-07-27 10:49:20.820 +01:00 [Error] 500 Exception caught in Global.asax
System.Web.Mvc.HttpAntiForgeryException (0x80004005): The provided anti-forgery token was meant for a different claims-based user than the current user.
   at System.Web.Helpers.AntiXsrf.TokenValidator.ValidateTokens(HttpContextBase httpContext, IIdentity identity, AntiForgeryToken sessionToken, AntiForgeryToken fieldToken)
   at System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1c(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__4(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

Our setup is using `CookieAuthenticationProvider` with the AD integration, and the user here has exactly the same group membership as my own unprivileged account and another colleague.

**Comment by rozniak** [comment]
Unfortunately I'm absolutely no expert in ASP.NET other than having glossed over a bit of theory - Bonobo is the most I've really come into contact with ASP.NET code. I had a glance over `HomeController.LogOn(LogOnModel model)` and `CookieAuthenticationProvider.SignIn(...)` and couldn't really see much wrong.

I did have a tiny tweak though - I read up a bit on what *might* cause the error and came across some stuff referring to how `View()` and redirects are done post sign-in and sign-out. In `CookeAuthenticationProvider.SignIn(...)` I have commented out the redirect section like so:

```
public override void SignIn(string username, string returnUrl = null, bool rememberMe = false)
{
    ClaimsIdentity identity = new ClaimsIdentity(GetClaimsForUser(username), CookieAuthenticationDefaults.AuthenticationType);
    var authprop = new AuthenticationProperties { IsPersistent = rememberMe, RedirectUri = returnUrl };
    HttpContext.Current.GetOwinContext().Authentication.SignIn(authprop, identity);
    //if (!String.IsNullOrEmpty(returnUrl))
    //{
    //    HttpContext.Current.Response.Redirect(returnUrl, false);
    //}
}
```

And I have amended the switch case for `ValidationResult.Success` in `HomeController.LogOn(LogOnModel model)` to end in a `RedirectResult` rather than `EmptyResult` like so:
```
case ValidationResult.Success:
    string targetUrl = Url.IsLocalUrl(model.ReturnUrl) ? model.ReturnUrl : Url.Action("Index", "Home");

    AuthenticationProvider.SignIn(model.Username, targetUrl, model.RememberMe);
    Response.AppendToLog("SUCCESS");
    if (Request.IsLocal && model.DatabaseResetCode > 0 && model.Username == "admin" && ConfigurationManager.AppSettings["AllowDBReset"] == "true" )
    {
        ResetManager.DoReset(model.DatabaseResetCode);
    }
    return new RedirectResult(targetUrl);
```

I stopped the service, dragged in the new DLLs and started it again - the user was able to sign in but it was a bit weird. Apparently it was pretty much hung doing nothing, until they clicked 'Sign In' again with the network developer tools open. I *had* signed in myself successfully after the restart and before their attempt so not sure what that is about.

Trouble is I don't know whether this is fixed by my change (I expect not?) or perhaps the restart of the IIS worker running Bonobo...

Any pointers would be appreciated, unfortunately I'm having trouble reproducing it because it works on my accounts!

**Comment by willdean** [comment]
Are you sure the problem is specific to their account rather than their machine/browser?
Usually you get these sort of errors because of a particular flow through various login/logout pages, rather than something about a specific user account.

**Comment by rozniak** [comment]
I was debating that, I'm not sure why it would work now though if it were purely their browser.

Essentially I had sent a link to one of the repositories on the server, obviously it asked him to sign in before he could access it and that's when he got the problem.

**Comment by rozniak** [comment]
Still occurring actually, which makes sense.

What is happening:
- User enters AD creds on sign in page
- Presses sign in - browser waiting on `Processing request...`
- Nothing happens, pressing sign in again generates the 500 but they are signed in

So perhaps the 500 can be ignored as that would be like you said, the flow through sign in, them clicking it twice would probably cause that issue. I guess the question I should be answering is why is it getting stuck on auth for them, they are present in the ADBackend and the logs mention successful validation.

**Comment by willdean** [comment]
[Slightly obsoleted by your most recent comment, but I've written it now...]

It's usually a flow problem, it's caused by the login form being issued with a CSRF-prevention field which turns out to be considered invalid by the time it gets submitted along with the form.    You can probably recreate something similar by opening two login forms in two tabs and submitting one then trying to submit the second.  (Obviously that's not what happened here, but it might be a similar effect.)

I looked after one ASP.NET-based system where we just saw them every so often with some combination of use of the back button, etc.  I think sometimes the browser finds some cached version of a page which is invalid when it's actually submitted?

**Comment by willdean** [comment]
Like you say most recently, the 500 is probably not the main problem here, that's just a side effect of the logging-in again when they're already logged in (it's also a sign that they did get logged in initially, which is why the get the CSRF cookie error on the second attempt).

So the issue is perhaps something to do with not getting the redirect correctly after the sign in.  I don't have the time to look at the code right now, but will try to later.  If you have a reliable repro of this then that would be great.

**Comment by rozniak** [comment]
Just adding some extra logging around the function calls during sign in - I've tried reproducing it on both my machine and my Windows 10 test environment with Chrome and Firefox, no luck on getting the problem though.

Hopefully when he signs in again I might have a better idea based on how far it got according to the logs.

**Comment by rozniak** [comment]
So the logging suggests that it's stuck after the `return new EmptyResult();` - all of the stuff in `HomeController.LogOn()` completes, and then the request/response hangs. After clicking sign in again it will cancel the request from the client and issue a new one which succeeds.

**Comment by willdean** [comment]
I don't really know why it's returning EmptyResult - that seems odd, but it shouldn't cause the browser to hang - it would just display a blank page.  (It's just an empty 200 basically).

I guess Bonobo thinks it's already set up the redirect, though it seems like an odd way to arrange things.

Is there a ReturnUrl parameter on the URL or not during this process?

**Comment by rozniak** [comment]
I did think that bit of the code was weird - the redirect appears to be set up inside of the `AuthenticationProvider`, which is what I commented out and replaced with a `RedirectResult` in the controller itself (though I have since reverted it).

I am currently looking into why it's hanging, I assume it's something IIS related or our router - must be something outside of Bonobo I reckon

**Comment by rozniak** [comment]
I will close this issue because the 500 response is normal behaviour then, and I think that the particular hanging problem the user is getting that causes them to then do a double sign-in is something to do with our network or IIS, not Bonobo.
