### ISSUE TITLE
Is the current commit 6.5.0?

### ISSUE THREAD

**Issue by reneqvist** [jakubgarfield/Bonobo-Git-Server#886]
When I clone the repository, the properties file says 6.2.0.0?

**Comment by willdean** [comment]
Yes, it's out of date, sorry - looks it doesn't get updated reliably.  If you look at the commits you'll clearly see 6.5 being committed.

**Comment by reneqvist** [comment]
Okay, so its just the properties file which is out of date?, if I pull the current commit, it is 6.5.0?

**Comment by willdean** [comment]
Yes
